### ISSUE TITLE
Refprop 10, Excel and Licensing

### ISSUE THREAD

**Issue by RaySA19** [usnistgov/REFPROP-issues#100]
I recently purchased Refprop 10 and paid $325. I am not sure if program file already had the excel add-in when I downloaded the software or I added it later.

Anyhow, I couldn't get excel sheet to work so I decided to delete the excel sheets from program file and follow steps provided on the site how to download excel add-in. I came to find out that the excel sheet I downloaded from site is version 9 and my Refprop is version 10 and I can't get it to work. Would you please advise what I can do to fix this? Should I uninstall the Refprop software and re-install it, if I do, would you please provide me my key or some kind of info that I don't have to pay. Is there any customer support on the phone can assist me and walk me through this so I don;t have to email back and forth? 

 

Also I want to ask, on how many computer I can install my Refprop 10 without paying again?

**Comment by EricLemmon** [comment]
The Refprop installer does not require any key or other security item to install the program.  Because this is a scientific program, we tend to trust our customers knowing that they are generally professionals and abide by certain ethics of conduct.  Thus you can reinstall the program any time needed on the machines that you use.

The Refprop license is for a person, not for a machine, and therefore you can install the program on all machines that are for your use only.  We are more interested that users have correct thermophysical properties than we are about selling the product, and have tried to make the single-user license as simple as possible.

In your situation, the best thing to do to fix the problem is to simply reinstall the program.  It will replace all existing files with the ones that come with version 10.  Once done, you will find the refprop.xls file and the add-in refprop.xla in the directory where the program was installed.

If you have lost the installer, please contact us directly to obtain another one (eric.lemmon@nist.gov).

**Comment by RaySA19** [comment]
Thanks Eric for your quick response, much appreciated. Would you please guide on how to re-install ref prop 10. When I go to program file, I only see an option for uninstalling which is named " unis000". 

Also, how do I install the copy I paid for in another computer, if I go to the following link on another computer, it's going to ask me for payment option and without entering it, it won't allow me to re-install it. Please advise
 https://www-s.nist.gov/srd_online/index.cfm?fuseaction=home.main&productID=SRD23V10

**Comment by EricLemmon** [comment]
Go to Control Panel and there you will find an item about uninstalling programs.  In Windows 7, it's called "Programs and Features".  Then find Refprop on that list, right click, and there should be an option to uninstall it.  However, even though we recommend uninstalling the program, it is not generally necessary.

Do you still have the installation file that you first received when you purchased the program?  If so, just run that again and all will work.  If not, email me directly.

**Comment by RaySA19** [comment]
Thanks. It seems the excel file is fixed now. I found the executable file for re-installation under 'D0wnload". So in order to download this copy in another computer of mine, do I need copy all the files from program file including the executable file into another computer and run the .EXE file?

Another question: I am trying to calculate flow exergy in excel sheet, I don't see a symbol for that in the excel instruction under symbols, I know in refprop, the flow exergy is under Units>properties>special , what do I enter in excel to calculate flow exergy?

**Comment by RaySA19** [comment]
eric,

I would appreciate if you could respond to my comment in previous email/email I sent on Jan 31st when you get a chance. I have similar question about flow exergy in Matlab, what symbol would evaluate the exergy or do I need to type the flow exergy in matlab? 
Also, I see in the matlab the units are fixed and they are all in SI system, how can I change the units to English system or assign a specific unit for each property?

**Comment by EricLemmon** [comment]
To install the program on another machine, simply copy the executable called NIST2310.EXE to the other machine and run it.  Do not copy all the other files that were installed, just the installation file itself.

**Comment by EricLemmon** [comment]
For exergy, the command in Excel to obtain this property is simple:  Exergy.  For a closed system exergy, the command would be CExergy. 

For matlab, it depends on whether or not you are using the new Python based connection to the DLL or the old refpropm.m file.  For the python based system, I believe the inputs are the same as they would be in Excel.  For refpropm.m, there is no available option to calculate it because that method ran out of characters that could be used for the different properties (it also does not support unit conversions).  We are no longer supporting the refpropm.m file, and you should change to the python based method if possible.  It is by far more simple, adds all new features of Refprop 10, and matches the Excel spreadsheet, I believe (Ian can correct me if I am wrong).

**Comment by RaySA19** [comment]
Thanks Eric for your prompt response, that was very helpful. I think I have the old python, I will get the new one you recommended.  
Is there any sample Matlab codes like the ones you all created for excel. If there is any, would you please email it to me. Would you please provide a simple line of code for calculating a property where we assign SI, English or an specific unit for each property.

**Comment by EricLemmon** [comment]
Take a look at the following site and see if it gives you everything you need:

https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB

**Comment by RaySA19** [comment]
Thanks.
