### ISSUE TITLE
Differences between REFPROP version 9 and 10

### ISSUE THREAD

**Issue by AndreasGrenner** [usnistgov/REFPROP-issues#102]
Comparing some old calculation results of REFPROP version 9 with new ones of REFPROP version 10 I made some observations which I cannot explain. 
 
For both version I used the same input, I calculated the entropy for pure nitrogen e.g. at 124.2 K and 33.71 bar, reference state: ”default reference state”.
 
Version 10: Results of entropy: 110.69 kJ/(kmol K) and “ideal gas entropy”: 123.07 kJ/(kmol K)
 
Version 9: : Results of entropy: 110.69 kJ/(kmol K) and “ideal gas entropy”: 136.87 kJ/(kmol K)

Why is the ideal gas entropy different between the two versions?

**Comment by EricLemmon** [comment]
This is a bit complicated to explain and deals with the question of the proper input that should be used to calculate the ideal gas entropy, which is obtained by integrating the ideal gas heat capacity from the reference state to the temperature of interest and then adding to this a contribution from the ideal gas pressure and density (the value is simply the natural logarithm of the ideal gas density).

As an example, assume T=200 K and P=20 MPa.  The densities and ideal gas entropy in version 10 are:
Inputs:  T=200 K, P=20 MPa
Dreal=13.287 mol/dm^3
Dideal=12.027 mol/dm^3
Sideal=135.10 J/(mol-K)
The ideal entropy in version 9 is 
Sideal=135.93 J/(mol-K)

In version 10, if you instead enter temperature and the ideal gas density instead of your input pressure, then you obtain an ideal gas entropy of:
Inputs:  T=200 K, D=12.027 mol/dm^3
Sideal=135.93 J/(mol-K)

Thus the difference between versions 9 and 10 is simply a matter of which density should be used to calculate the ideal gas entropy.  Version 10 correctly uses an input density calculated from the ideal gas law:  D=P/RT (which is the value of 12.027 above).  Version 9 used the density from the equation of state (the real-gas density), which was incorrect (depending on how you define the ideal gas entropy in terms of which inputs should be used).

Ironically, the "ideal" part of equations of state is not "ideal" to understand, but by far more complicated to implement than the real-gas part of the equation of state, which appears complex due to the number and type of terms in the equation.  (Although, if you are trying to implement the real gas part in Excel, then it becomes complicated.  We highly recommend using VBA code in Excel to do this rather than placing each part of each term into the cells in a spreadsheet, making it very difficult to debug.)

**Comment by AndreasGrenner** [comment]
The ideal gas entropy results of version 10 are still not clear to me. 

I assume that the ideal gas entropy at constant temperature varies only for the term "-R ln (p/p0)". Doing the calculation for pure nitrogen and the following arbitrary chosen conditions

at 124.2 K and 33.71 bar: version 9 --> 136.87 J/(mol K); version 10: --> 123.07 J/(mol K)
at 124.2 K and 1.01325 bar: version 9 --> 166.01 J/(mol K); version 10: --> 165.92 J/(mol K)

The term "-R ln (p/p0)" is for 33.71 bar with p0 = 1.01325 bar and R = 8.3145 J/(mol K) --> -29.139 J/(mol K) and zero for p = 1.03125 bar, respectively. Hence, the differences between the ideal gas entropy results at 33.71 bar and 1.01325 bar should have the same delta (-29.139 J/(mol K)). This is the case for version 9 but not for version 10 where the delta is -42.85 J/(mol K) instead of -29.139 J/(mol K).

**Comment by EricLemmon** [comment]
The problem here is that you entered the real gas pressure into Refprop to calculate the ideal gas entropy.  You would need to enter the ideal gas pressure to make versions 9 and 10 agree.  For example, at 124.2 K and 1.01325 bar, the compressibility factor is 0.98956.  This means that the ideal gas pressure is 1.0027 bar (=P*Z).  If you then enter T=124.2 K and P=1.0027 bar, the ideal gas entropy is 166.01, which matches version 9.

**Comment by AndreasGrenner** [comment]
Thank you for this clarification. We can reproduce now the values of version 9 with version 10. Our thinking is more aligned with version 9.

**Comment by EricLemmon** [comment]
Can this issue be closed now?

**Comment by AndreasGrenner** [comment]
Yes. Thank you for the support.


Outlook für iOS<https://aka.ms/o0ukef> beziehen

________________________________
Von: Eric Lemmon <notifications@github.com>
Gesendet: Donnerstag, Februar 14, 2019 12:52 AM
An: usnistgov/REFPROP-issues
Cc: Andreas Grenner; Author
Betreff: Re: [usnistgov/REFPROP-issues] Differences between REFPROP version 9 and 10 (#102)


Caution: The identity of the sender of this message could not be verified as it originates from the Internet. Please pay attention!

Can this issue be closed now?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fusnistgov%2FREFPROP-issues%2Fissues%2F102%23issuecomment-463424510&data=02%7C01%7Candreas.grenner%40linde.com%7C04b9f9f2dd1e44689a1408d6920e4c13%7C1562f00709a44fcb936be79246571fc7%7C0%7C0%7C636856987446191599&sdata=Vj%2BSfZyoCxTJNsXpe4aYhsOVxFokACyJfTwhedp%2BOME%3D&reserved=0>, or mute the thread<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAtB6tTIBTVf2uiQQQ0XDUzlShzU6AA1Vks5vNKUzgaJpZM4acbZV&data=02%7C01%7Candreas.grenner%40linde.com%7C04b9f9f2dd1e44689a1408d6920e4c13%7C1562f00709a44fcb936be79246571fc7%7C0%7C0%7C636856987446191599&sdata=hG4h86c8JKlV12RmgKDY3Xw%2Fs0ahN0QMxJlLhSTpDeg%3D&reserved=0>.

The information contained in this email and any attachments may be confidential and is provided solely for the use of the intended recipient(s). If you are not the intended recipient, you are hereby notified that any disclosure, distribution, or use of this e-mail, its attachments or any information contained therein is unauthorized and prohibited. If you have received this in error, please contact the sender immediately and delete this e-mail and any attachments. No responsibility is accepted for any virus or defect that might arise from opening this e-mail or attachments, whether or not it has been checked by anti-virus software...

Die Datenschutzerklärungen der Unternehmen der Linde Group mit Sitz in der EU finden Sie hier: dataprotection.linde.com<http://dataprotection.linde.com>
