### ISSUE TITLE
Problem with Custom Mixture in RefProp 10.0

### ISSUE THREAD

**Issue by wmhmitchell** [usnistgov/REFPROP-issues#103]
I want to use Refprop 10.0 to do some property calculations on a mixture of pure substances inside an Excel spreadsheet.  I have previously done this successfully with Refprop 9.0.

My example is an 80/20 mixture of Isobutane and Butane.  I have used the Substance/Define New Mixture function to set it up, and am able to save it in the REFPROP/MIXTURES directory, using the file name 80_20_Isobutane_Butane.MIX.

It does appear in the list of mixtures. But I am unable to see it in the REFPROP/MIXTURE directory using Internet Explorer.

The real problem, though, is that when I use the mixture as the substance in REFPROP function in Excel, it does not work.

I use the name 80_20_Isobutane_Butane.MIX.  This is the way I used it in the old 9.0 version, but it’s not working for me here.  I’ve also tried it without the .MIX suffix, without success.

It returns this error code:  #[SETMIX error 101] Error in opening mixture file: 80_20_Isobutane_Butane.MIX.

Can you help me out?

Thanks

**Comment by EricLemmon** [comment]
Depending on the security level on your machine and whether you have permission to write to the Program Files directories, Microsoft started using ghost directories for overly protected systems so that it appears that the file is there but really it is not.  These ghost directories are hidden, and thus you generally do not know that such a scheme is going on.  The new file is in your user's directory under the following hidden subdirectory:

AppData\Local\VirtualStore\Program Files\REFPROP

You can either move the file to the real location (in Program Files), or uninstall Refprop and then reinstall it outside of the Windows directories in a new place such as your user's directory or in the root drive of your computer.  Once you do that, Windows will stop making the ghost directories and place the file in the correct place.
