### ISSUE TITLE
Reciprocating compressor performance with REFPROP

### ISSUE THREAD

**Issue by cstroh76** [usnistgov/REFPROP-issues#108]

**Comment by cstroh76** [comment]
In the very early work on simulating reciprocating compressor performance, use was made of a compressibility factor Z along with pv^k=const for  an alleged  path of constant entropy.

Am I safe to say that I no longer need the compressibility factor or an exponent K  but merely use the specific volume and entropy at suction conditions provided by mixture data and the specific volume at discharge conditions along with the same entropy found at suction conditions using the same mixture data available today?

**Comment by EricLemmon** [comment]
Simple equations such as pv^k=constant have many assumptions behind them, generally assuming ideal gas or taking into account only small corrections due to the compressibility of the gas.  With the equations of state that we develop, it is no longer necessary to use these simple equations, and in fact we highly discourage their use because the answers they provide deviate from real gas properties as the pressure and/or density increases.  In the critical region, the values are completely wrong and should never be used.  

Today's high accuracy equations (those used in Refprop and other similar software such as Coolprop) are quite complex and take months to develop.  However, the end result is a product that represents the real properties of the fluid better than any other method available.  To view the complexity and accuracy of typical equations of state, see the publication on R-125 found here:

https://pages.nist.gov/REFPROP-docs/#refprop-is-a-program-not-a-database-containing-measurements

With these equations, you can enter your inputs directly into the iterative solvers provided by the software and they will return any property you request.  You can also use the software to make plots such as P-H or T-S and then plot your state points directly on the plot.  Refprop allows you to right click on the plot to add data points.  If you have a table open, it will add the data points to the table as you click on the plot (and calculate the other properties).  When done, double click on the plot and tell it to join the points with a line.

**Comment by EricLemmon** [comment]
Can this issue be closed now?

**Comment by cstroh76** [comment]
Yes, thanks for the help.
