### ISSUE TITLE
Refrigerant properties do not match those from other companies

### ISSUE THREAD

**Issue by ghost** [usnistgov/REFPROP-issues#114]
I am using Refprop 9.1 and the properties coming from the program are slightly different from those used in other companies and from the spec sheets from the manufacturers.  How can I tell which properties are correct?

**Comment by EricLemmon** [comment]
Several years ago we searched the literature for all available measurements and collected some additional data that had not yet been published.  We then fit the data and updated the parameters for mixtures of R32, R125, R134a, R1234yf, and R1234ze(E).  This was then made available to the public towards the end of 2015.  The parameters are contained in a file called HMX.BNC that is located in the Refprop\fluids directory.  It is an ASCII file and you can edit it with Notepad if you are curious to see what's in there.  It contains every single mixture we have fitted over the years up to that point in time (about 600 binary mixtures total).  This is the work of many thousands of hours of fitting going back to about 1992 (and this number does not include all the time that the experimentalists required to make the measurements that were vital to this work).  If you would like to obtain this file, please email me directly (eric.lemmon@nist.gov).

If you are using version 10 of Refprop, you do not need a new mixture file.  All of the fits for these five components from 2015 were left unchanged in the final release so as to not require industry to update a second time in such a short period.  However, that will not be the case in future versions.  Many new measurements are becoming available and the fits will be redone.

As a side note, even though we have only fit binary mixtures, we have learned over the years that once these are fitted correctly then no ternary or higher order interaction parameters are required.  Sometimes it may seem that a particular multicomponent mixture is not fitted within the experimental uncertainties, but we have found that refitting the binaries to obtain more accurate parameters results in more accurate calculations for the multicomponent mixture (being within their experimental uncertainties).  Fitting mixtures is quite tricky because of the need for measurements (including density and speed of sound) not only in temperature-pressure space, but also at different compositions.  Furthermore, measuring just the vapor pressure is not sufficient as with pure fluids because we require the equilibrium compositions in the other phase to obtain an accurate fit.  Only a few binary mixtures are measured so well that a full model can be developed.  The rest are done as well as we can, but there will always be room for improvement.

**Comment by paarfi** [comment]
This is a bit like the old saying that a man who has one watch knows what time it is, but a man who has two watches isn't so sure. No source of refrigerant properties is going to match the real fluids exactly. But NIST Refprop is generally considered to be the gold standard in the refrigeration industry. 

If you have specific examples that you are concerned about, I'd suggest posting an issue here so they can look at it. No software is ever completely bug free, including Refprop. But generally speaking, I'd recommend trusting the properties from NIST Refprop over any other generally available source.

**Comment by EricLemmon** [comment]
Thanks for these nice comments, it's good to hear when people are pleased with the software.
