### ISSUE TITLE
Provide Information about REFPROP

### ISSUE THREAD

**Issue by sukrit2018** [usnistgov/REFPROP-issues#126]
1.  Can you give us a small snapshot of the database? We would like to understand how the data is structured.
  2.  Are these computed data or experimental data?
  3.  We would like to understand how dense is the physical property data?
  4.  Does this data set contains melting point and boiling point of materials?
  5.  How much physical property data do we have for mixtures?

**Comment by ianhbell** [comment]
What is the question here?

**Comment by sukrit2018** [comment]
Can you give us a small snapshot of the database? We would like to understand how the data is structured.
Are these computed data or experimental data?
We would like to understand how dense is the physical property data?
Does this data set contains melting point and boiling point of materials?
How much physical property data do we have for mixtures?

**Comment by sukrit2018** [comment]
Dear Ian,
  I have not used git before and thus was not sure how to submit my inquiry. I highlighted my inquiry below.

thanks,
sukrit

Description

  1.  Can you give us a small snapshot of the database? We would like to understand how the data is structured.
  2.  Are these computed data or experimental data?
  3.  We would like to understand how dense is the physical property data?
  4.  Does this data set contains melting point and boiling point of materials?
  5.  How much physical property data do we have for mixtures?
Steps to Reproduce

  1.  [First Step]
  2.  [Second Step]
  3.  [and so on...]
Expected behavior: [What you expect to happen]
Actual behavior: [What actually happens]
Versions
REFPROP Version: [REFPROP version you are using]
Operating System and Version: [OS you are running REFPROP on]
Access Method: [How you are accessing REFPROP (i.e. Python, other wrapper)]
Additional Information
If possible, please post examples and/or screenshots of the issue.

**Comment by EricLemmon** [comment]
These are all good questions!  There are a lot of resources that we have put together to help with this, but they only answer a few of these.  The following give snapshots of how the program works:

https://pages.nist.gov/REFPROP-docs/
https://trc.nist.gov/refprop/REFPROP.CHM
https://trc.nist.gov/refprop/REFPROP.PDF
https://refprop-docs.readthedocs.io/en/latest/

The properties that come from the program are all computed from high accuracy equations of state.  These equations are quite complex and can take up to a year to develop.  To see some of the complexity, take a look at the following:

https://trc.nist.gov/refprop/FAQ/R125.PDF
http://www.gerg.eu/public/uploads/files/publications/technical_monographs/tm15_04.pdf

The equations of state are built on the experimental data that are available.  At NIST, our group is composed of both equation of state developers and experimentalists who measure density, speed of sound, heat capacity, vapor pressure, viscosity, thermal conductivity, and so on.  Without them our equations would be drastically diminished in their accuracy.  However, they cannot measure everything so many of the equations that are available in Refprop have much higher uncertainties than others.  Thus the "density" of the physical property data (including "density" measurements!) varies greatly from fluid to fluid.

The boiling points come naturally from the equation of state.  The paper on R-125 above gives some of those details.  The melting points (or more specifically, freezing liquid points) require an auxiliary equation, and not every fluid has been measured, and thus we do not have melting lines to go with them.  In those cases, the equation is limited by the density of the fluid at the triple points.  

_Please note_ that Refprop does not calculate solid properties, it only knows the boundary for liquid states (when a melting line equation is available).

Mixtures are a totally different story because the possible states available are (almost) infinitely more than those for the pure fluids.  It is thus not possible to measure every mixture for all properties as I listed above.  Those that are well measured are listed in the GERG TM-15 document above.  For many others all we have are a few bubble-point measurements.  Take a look at the following document for more information:

https://pubs.acs.org/doi/abs/10.1021/acs.jced.6b00257

Our knowledge in fitting pure fluids is quite advanced, but we still have much to learn with mixture fitting.  It is so much more complex, especially when mixtures contain helium, hydrogen, or water.

**Comment by EricLemmon** [comment]
I've updated this thread to remove some of the extraneous material.  Hope that's OK!

Can this issue be closed now?
