### ISSUE TITLE
Extrapolation of property calls in the solid phase

### ISSUE THREAD

**Issue by AndreasGrenner** [usnistgov/REFPROP-issues#128]
For dynamic simulation a steady course of enthalpy is desirable. Hence, it may occur that an enthalpy call is close to or already in the solid phase. Usually REFPROP refuses property calls in the solid phase with the message "pressure above melting pressure." Is there a way to parametrize REFPROP in such way that extrapolation into the solid phase is possible?

**Comment by ianhbell** [comment]
For sure this is a common problem in simulations of all kinds.  I had issues with things like this when I was designing ACHP and PDSim.  

Do you get an error message (and still a value), or just an error message?  How are you calling REFPROP? If you are calling through CoolProp, it dies if there is any error message with ierr>0.  If calling REFPROP directly, then you are responsible for dealing with the error code, and it will sometimes give you both a number and an error code.

P.S. Please fill out the entire issue template so that we don't waste time asking for information that is requested in the issue template.

**Comment by AndreasGrenner** [comment]
Thank you for your helpful answer. Since I got an error code calling REFPROP directly I did not check further for values in the result vector. But, REFPROP still give the results requested. I will extend my code for dealing with that error code. Issue is solved. Thanks again.
