### ISSUE TITLE
Fluid Information online

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-issues#129]
This is just an idea, but maybe you could also put the Fluid Information online, so that it is possible to see (or show to colleagues) what papers you implemented even without a RefProp license.
Including also the alternative variants, as in the Fluid Information window (PS: The drop down menu for switiching is a bit hard to find in the Fluid Information window).

**Comment by ianhbell** [comment]
You have in mind something like this for CoolProp, right: http://www.coolprop.org/fluid_properties/PurePseudoPure.html#list-of-fluids ?  Indeed this is a topic that has been raised more than once, but we have not yet reached a satisfactory conclusion.  

Now that we are storing the DOI of the papers in the fluid files, the process of mapping from DOI to paper bibliography information is much easier, and it should be possible, in many cases, to extract the BibTeX directly from CoolProp for the given DOI (and auto-generate an HTML entry with pybtex).  Deciding how/where to store that information so that people know what is implemented/available is a harder question.

**Comment by thorade** [comment]
I actually had the single fluid pages in mind, like:
http://coolprop.org/fluid_properties/fluids/R22.html
With readable, permanent (or, long-living) URLS!
But the overview list is also great, and it links to the single pages.

Does the RefProp Fluid Information use the info from .fld files only, or is there some large .bib file?
If possible, it might also be nice to not just generate the DOI link, but additionally link to the Google scholar cluster page, like this one:
https://scholar.google.com/scholar?cluster=14347212806209996995
Because that will also find pdf files if they are available somewhere on the internet.

Probably easy to find, but this SO question might be relevant for converting DOI to bibtex:
https://tex.stackexchange.com/questions/6848/automatically-dereference-doi-to-bib/361003

**Comment by ianhbell** [comment]
Indeed, crossref is the answer to DOI resolution nowadays!  Probably we would want to use crossref to generate the bibtex/HTML and then cache that information.  Maybe 2 or 3 lines of Python to do that I would imagine between requests and pybtex libraries.

Yes, I had in mind exactly what you mention, an overview page like for CoolProp, and detailed pages for each fluid.  With maybe also similar consistency plots, hopefully showing even better consistency!

I'm not a big fan of "Files somewhere on the internet" due to IP concerns, but pointing to the journal (via the DOI) and letting people take it from there is something I can get behind.

**Comment by EricLemmon** [comment]
I've added the "feature-request" label to remind us to come back to this issue.  If there are no further comments now, could you close this issue?
