### ISSUE TITLE
FluidInformation DOI for alternative EoS

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-issues#134]
Very minor issue: 
In the FluidInformation window, I can switch to different equations of state, and they usually mention a DOI. But the DOI shown below the window does not update (so I cannot click it, forcing me to do 1-2 clicks in my browser...)

**Comment by EricLemmon** [comment]
I believe this issue is fixed now, could you try the new GUI and let me know?

**Comment by ianhbell** [comment]
Doesn’t seem fixed to me...

**Comment by ianhbell** [comment]
The DOI link goes away, but the proper DOI link doesn't appear.  E.g.,
![image](https://user-images.githubusercontent.com/11966765/55347439-26794f00-5472-11e9-8b29-6ad3630b5458.png)

**Comment by EricLemmon** [comment]
This one was actually fixed shortly after this issued was created, but I did not report so because the updated DOIs were made to the current fluid files, not to those in Refprop 10.0.  We do not want to distribute the new set yet because of various reasons, such as mismatched pure fluid equations of state and their mixture models.  But they will all be available when version 10.1 is released.

**Comment by thorade** [comment]
Thank you!
