### ISSUE TITLE
Humid air properties in REFPROP 

### ISSUE THREAD

**Issue by CarlHerr** [usnistgov/REFPROP-issues#135]
Why doesn't REFPROP support moist air?  It would be a great addition to REFPROP's capabilities.

**Comment by ianhbell** [comment]
Indeed, this is true.  That's why I worked out the algorithms for all the necessary calculations in REFPROP: https://www.sciencedirect.com/science/article/pii/S014070071730381X .  But there are a number of challenges with getting this working, most especially the problems with the mixture model itself.  It just doesn't produce very reliable numbers for humid air.  A better approach is that of ASHRAE RP-1485, which is also implemented in CoolProp: http://www.coolprop.org/fluid_properties/HumidAir.html#humid-air .  

Are you doing exotic psychrometric calculations (non-standard air, weird states, etc.)?  If not, the implementation in CoolProp should probably suit your needs.

**Comment by CarlHerr** [comment]
I was not aware of the CoolProp implementation, I will check it out, thank you.  All our calculations are very standard and most times perfect gas relations are good enough.  
The appeal of having it as a part of REFPROP is that a single add-on in excel would take care of refrigerants and moist air.

**Comment by EricLemmon** [comment]
I'm closing this issue, but the label "feature-request" will remind us to keep this request open in our work flow as time permits.
