### ISSUE TITLE
Gaps in property data from REFPROP GUI

### ISSUE THREAD

**Issue by detlor** [usnistgov/REFPROP-issues#140]
### Description

I am curious about the gaps in property data from the REFPROP GUI for mixtures such as the one listed below. These gaps occur for multiple of the hydrocarbon mixtures I run but this one is more unique with a specific gap at 220K. From my understanding, REFPROP is unable to generate property data for some mixtures due to lack of experimental data. However, I am uncertain why it is unable to generate the information specifically at 220K. Additionally, should I be concerned about the data returned for 130K as the mixture is close to a phase change and there is no data generated between 180-130K? 

Thank you for your time.

### Steps to Reproduce

1. Mixture: 0.3 butane, 0.49 methane, 0.21 nitrogen (molar basis)
2. Temperature range 110-300K
3. Pressure of 300 psia

**Expected behavior:** Property data at 220K.

**Actual behavior:** No property data generated at 220K. 

### Versions

**REFPROP Version:** 9.1
**Operating System and Version:** Windows 10  
**Access Method:** REFPROP GUI

### Additional Information

If possible, please post examples and/or screenshots of the issue.
![Capture](https://user-images.githubusercontent.com/48929182/54956279-9e4cf400-4f1d-11e9-9f70-cec9c6de1307.PNG)

**Comment by ianhbell** [comment]
Note: I modified your issue slightly.

Did you get any error message popups when you evaluated this table?

**Comment by detlor** [comment]
Yes. I have posted the error message below. The same message appears for each temperature where the data is missing. However, I do not understand why this would be occurring at 220K as data is generated for 180-210K and 230-290K.

Looking more closely, data is even generated from 210-219K and 222-230K. 

![Capture](https://user-images.githubusercontent.com/48929182/54957288-4fed2480-4f20-11e9-8f92-0f17445b8af5.PNG)

![Capture](https://user-images.githubusercontent.com/48929182/54957537-0a7d2700-4f21-11e9-8972-ead6f1f1fa5d.PNG)

**Comment by ianhbell** [comment]
Mixtures are hard, and calculations for mixtures are never going to be as reliable as for pure fluids.  In the GUI, an option that can help is to calculate the isopleth of the phase envelope:

![image](https://user-images.githubusercontent.com/11966765/54957674-0cdb8300-4f19-11e9-8f31-bdcbf351739d.png)

See also https://github.com/usnistgov/REFPROP-wrappers/issues/106

**Comment by detlor** [comment]
It appears I do have that box checked.

It is not crucial for my project for this specific data point be generated. However, I am trying to gain a better understanding of why there is difficulty generating information for a specific temperature and pressure when the property information around this point is being generated by REFPROP.

**Comment by EricLemmon** [comment]
The problem you are seeing is due to the difficulty in calculating properties of a complex mixture with widely varying boiling points.  Take a look at the picture below, it shows a pressure-temperature diagram of the saturation line (in red) and multiple isochores.  It also shows that there is no liquid phase solution.  Such a mixture causes iterative VLE algorithms to fail more often than those for other simple mixtures.  Furthermore, the nitrogen equation of state that is the international standard has problems below its triple point, which does not matter when calculating pure fluid properties only, but does matter when used in mixtures with other fluids that have very long saturation lines, such as butane.  You are asking for state points that are on the very edge of failure due to this issue.  The nitrogen equation is 23 years old now, which is quite remarkable that it has held its ground for so long.  But because of the problems, we are now in the process of developing a new equation for this fluid, and then we will need to redo all the mixture parameters as well.

Version 10 of Refprop does calculate the properties in the range where you see holes because of improvements to the iterative algorithms.

![image](https://user-images.githubusercontent.com/42392984/54998265-549ef080-4f93-11e9-9b78-841161ab2f09.png)

**Comment by detlor** [comment]
Thank you for the response. The explanation was very helpful!

**Comment by EricLemmon** [comment]
Can this issue be closed now?
