### ISSUE TITLE
Different enthalpy values for Air

### ISSUE THREAD

**Issue by starkerm** [usnistgov/REFPROP-issues#150]
Dear all,

within my company we are struggling with an enthalpy value for air. Maybe you can enlighten us.
I´ll explain it with an example:
 
Pressure = 0,81 MPa
Temperature = 293K
Medium = Air
 
The REFPROP command “=REFPROP(“H”;”air”;”TP”;”MOLARSI”;293;0.81)” leads to an enthalpy value of 12095,3 kJ/kmol.
With the composition of Air “=REFPROP(“H”;”nitrogen;oxygen;argon|.78;.21;.01”;”TP”;”MOLARSI”;293;0.81) the result will be 8390,3 kJ/kmol.
With our experience we can tell, that the Value of around 8400 kJ/kmol is the correct one.
 
Do you have an explanation for this deviation? 
 
I am looking forward to your feedback. 
 
Kind regards

### Versions

**REFPROP Version:** [REFPROP 10.0]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [MS Excel Ribbon]

**Comment by ianhbell** [comment]
An important consideration here is that caloric properties (enthalpy, entropy) are relative properties: https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences .  For mixtures, you may need to fiddle with the SETREFdll function if you want to change the reference state.

**Comment by EricLemmon** [comment]
There are two equations of state available for air in Refprop, one is a mixture of nitrogen+argon+oxygen and the other is a pure fluid equation of state under the assumption that air can be treated as a pure fluid because its composition does not change.  These are both documented in this work:

Lemmon, E.W., Jacobsen, R.T, Penoncello, S.G., and Friend, D.G., Thermodynamic Properties of Air and Mixtures of Nitrogen, Argon, and Oxygen from 60 to 2000 K at Pressures to 2000 MPa, J. Phys. Chem. Ref. Data, 29(3):331-385, 2000. doi: 10.1063/1.1285884

The reference states for enthalpy and entropy for these two models are completely different; the mixture combines the reference states of the pure fluids and the pseudo-pure fluid equation uses a reference state of h and s equal to zero at the normal boiling point of the liquid.  However, Refprop will allow you to change the reference state to anything you would like.  Below is a picture of the output from the program for both models.  I included the same state points in each table, one at 300 K and 10 MPa, one at the saturated liquid at 100 K, and one at 100 K and zero pressure.  In the third table I changed the reference state (under Options/Reference State) so that the enthalpy is zero at that last state.  Note how the change in enthalpy (or entropy) between any two state points is the same in all three tables.  At the bottom of this discussion is a second picture showing the screen I used to change the reference state.

The reference states in Excel can also be changed.  There are some other issues on this github site that discuss this:

https://github.com/usnistgov/REFPROP-wrappers/issues/133
https://github.com/usnistgov/REFPROP-wrappers/issues/142
https://github.com/usnistgov/REFPROP-wrappers/issues/149

And be sure to see the comments in the link Ian provided above.

![image](https://user-images.githubusercontent.com/42392984/55430312-049fcb00-554b-11e9-87b7-c1dda5e1b208.png)

![image](https://user-images.githubusercontent.com/42392984/55430626-d8387e80-554b-11e9-9818-8bc523cbe80f.png)
