### ISSUE TITLE
Bug in mixing rule

### ISSUE THREAD

**Issue by kestrel26** [usnistgov/REFPROP-issues#153]
### Description

With Refprop version 9.1, I defined a new refrigerant blend of R32 and R1234yf. I used the window of "View Mixing Parameters" to check the mixing rule. Then I selected KWT for mixing rule. When I click the button of "Apply", the value of gamma changed from 1 to 0 automatically. 

### Steps to Reproduce

1. Defined a new refrigerant blend of R32 and R1234yf
2. Open the window of "View Mixing Parameters", and select the mixing rule of KWT
3. Click the button of "Apply", the value of gamma changed from 1 to 0 automatically

**Expected behavior:** [What you expect to happen]
It is expected to set the mixing rule parameters based on literature, then I may get better property predictions of the defined mixtures.

**Actual behavior:** [What actually happens]
The value of gamma changed from 1 to 0 automatically, when I click the button of "Apply", and I cannot reset the parameters successfully.

### Versions

**REFPROP Version: 9.1 [REFPROP version you are using]  
**Operating System and Version: Windows 10 [OS you are running REFPROP on]  
**Access Method:** [How you are accessing REFPROP (i.e. Python, other wrapper)]  

### Additional Information

If possible, please post examples and/or screenshots of the issue.
![image](https://user-images.githubusercontent.com/49324626/55657882-5a7da880-57c1-11e9-990e-bf5c63d8e245.png)

**Comment by ianhbell** [comment]
Thanks for the report. I have tidied up your issue post slightly.

**Comment by EricLemmon** [comment]
I have not checked to see if this is a bug in version 9.1 or not yet, for several reasons:
1) Changing the interaction parameters yourself is a very dangerous thing to do.  You might be able to get two or three points to match, but all other properties will become much worse than the values we supply.
2)  Any change you make needs to be verified by experimental data over large ranges of temperature (and hopefully pressure) before you use it for any calculations that might impact the design of a system.  We have data to do this, but some of it is confidential that we cannot share.  But we are always glad to share the sources of other data that have been published.
3) If you are trying to change the 9.1 values to newer published values, then please contact us and we can help with the change by adding them directly to the hmx.bnc file.
4) If you are trying to update the 9.1 values to those that are in 10.0 for refrigerants, we already have a hmx.bnc file that  we distribute to users of 9.1 for that very purpose.  Send us an email and we'll send it to you right away! 
5) If you are trying to fit your own experimental data, again, we can help with that to make sure that the fit is correct.
6) Using the KWR, KWS, and KWT mixing models is not recommended.  These are the old LJ4, LJ5, and LJ6 models that came from my dissertation almost 25 years ago now.  They were translated to the KW form so that we could mix and match the models, but doing so requires some alterations internally.  You should stick with the other KW models available in the HMX.BNC file.
7) The GUI for version 9.1 of Refprop is no longer being updated.  You are always welcome to use the beta version for Refprop 10.1 if you would like!  It contains all the latest features (and all the new bugs, of course!).  If you would like this, please send me a personal email (eric.lemmon@nist.gov).
