### ISSUE TITLE
REFPROP 10 GUI: PDFLSH does not give correct Cv, Cp around saturation line

### ISSUE THREAD

**Issue by ghost** [usnistgov/REFPROP-issues#155]
This is for REFPROP 10 GUI, fluid R32:
I use "Calculate -> Saturation Points", put P = 1 MPa and get
T = 279.774026367850000 K
D_l = 1031.937154858310000 kg/m3
Cv_l = 0.942099183400726 kJ/kgK

then I use "Calculate -> Specified State Point" and put P = 1MPa and D = 1031.937154858310000 kg/m3, but it cannot compute Cv or Cp. I guess PDFLSH gets into the two-phase region and cannot compute Cv, Cp. But PHFLSH and TDFLSH work fine.

**Comment by ianhbell** [comment]
What value for the vapor quality do you get?  Guessing it is just above 0?

**Comment by ghost** [comment]
On REFPROP GUI, I got "0.000000000000000" and REFPROP Fortran also gives "0.000000000000000D+000". I thought it got to the two-phase region but I was wrong.
Also, I can get around this problem by calling PDFLSH to get h_l, then call PHFLSH with P and h_l and can get the correct Cv and Cp.

**Comment by ianhbell** [comment]
Depending on your definition of the “two-phase region”, Q=0 could be two-phase or homogenous; I’d vote for two-phase, since strictly Q=0 is an infinitely small amount of vapor in equilibrium with a liquid phase, which is, in important ways, different than a homogenous liquid phase, even if the densities are the same.  I could see arguments in either direction.  Lots of things are discontinuous at the boundary, especially derivative properties (see for instance https://www.mdpi.com/1996-1073/7/3/1621)

**Comment by EricLemmon** [comment]
Rather than calling PDFLSH, PHFLSH, and so forth, in this situation, you really should be calling one of the saturation routines, such as SATT, SATP,  TQFLSH, or PQFLSH, when you are at the saturation boundary.  The last two will always return Cv, Cp, etc, when q=0 or 1.   The first two will return the liquid or vapor density, and then you can use these to call THERM (or the new REFPROP or ALLPROPS routines).  T and D are the independent variables in the equation of state, and all of the flash routines will return these two values (along with the phase compositions if needed), and from these all other properties can be obtained through the routines in the PROP_SUB.FOR file.  

**_But be warned:_**  If your q comes back >0 and <1 from a flash routine, do NOT call THERM to get the properties.  In this situation, subroutine THERM will return metastable values in the 2-phase, not the true saturation values.  The flash routines will only return properties that are thermodynamically defined in the 2-phase (see below).  For Cv, Cp, and SND, these properties are typically not defined in the 2-phase, and no value will be returned.

You can however, use the values coming back from the flash routines to get the properties in the liquid and vapor phases.  For example, if you call TPFLSH for a mixture and q comes back between zero and one, this routine will also return the vapor and liquid densities along with the vapor and liquid compositions that are in equilibrium with each other.  These will not be the same as your input compositions (except in the rare case when at the azeotropic point in a mixture).  You could then use T, Dl, and zliq to get the liquid properties at the liquid composition, and T, Dv, and zvap to get the vapor phase properties.  

Each phase has its own Cv, Cp, and SND, and you should not combine these to get an overall mixture value.  Imagine two very differently shaped objects such that in one of them sound can transfer from wall to wall quickly through the liquid phase that is in contact with much of the walls simply due to its shape.  In the other one, which has the same T, P, and q, but designed so that the vapor is in contact with the walls more so than the first object, then the speed of sound will take more time to travel through the vapor from one side to the other.  Thus the container and the phases have to be carefully examined to understand the true characteristics.  However, something such as enthalpy does not depend on the shape of the container and is thus thermodynamically defined for values of q between 0 and 1.  Enthalpy, energy, and entropy will always be returned by the flash routines (those containing the letters FLSH in the routine name).
