### ISSUE TITLE
Can't find ttrp of mixture

### ISSUE THREAD

**Issue by yuycsmart** [usnistgov/REFPROP-issues#171]
### Description
I can't find the triple point temperature of mixtures.

### Steps to Reproduce

1. [First Step]
From refprop software(GUI), I can't find the triple point temperature of mixtures(define new mixture or predefined mixture) from fluid information or anywhere.

2. [Second Step]
From refprop 10.0 help document, I can't find the triple point temperature of mixtures,only find the pure fluid function for outputting triple point temperature, INFOdll.

**Expected behavior:** [What you expect to happen]
Get the triple point temperature of mixtures.

**Actual behavior:** [What actually happens]
None, only the pure fluid function for outputting triple point temperature, INFOdll.

### Versions

**REFPROP Version: 10.0 
**Operating System and Version: Win 7  
**Access Method: c++

**Comment by ianhbell** [comment]
Well, strictly speaking, REFPROP doesn't _ever_ calculate the triple point of mixtures.  This is because in general we don't know where it is.  To know the location of the triple point of mixtures requires that we have the ability to model the solid phase of the mixture (as well as the liquid and gas phases, as we conventionally do).  With VERY few exceptions, we don't have the ability to do that.  Hence, the best that we can do (and what is done in REFPROP), is to say that the _minimum_ temperature of the mixture is equal to the mole-fraction-weighted-average of the triple points of the pure components forming the mixture.  That's all we can do...  The _minimum_ temperature of the mixture can be obtained through the DLL and/or the GUI.

**Comment by yuycsmart** [comment]
I got it, thanks.
