### ISSUE TITLE
Transport property computation for pure fluid siloxanes

### ISSUE THREAD

**Issue by lsciacov** [usnistgov/REFPROP-issues#181]
I am trying to compute thermodynamic and transport properties for some siloxanes (namely, D6 and MDM), but I am having some problems for the viscosity and thermal conductivity.

This is a Viscosity vs Pressure plot (x-Axis Range: 0.5-1.5 MPa; y-Axis Range: 10-50 uPa-s, isochores from 50 to 300 kg/m^3) for D6:

![Selezione_002](https://user-images.githubusercontent.com/36572530/60506217-af986000-9cc5-11e9-8872-4dd91766a44f.png)

Using the Fortran subroutines, the viscosity isocontours on a P-V diagram for D6 look like this:

![d6_visc](https://user-images.githubusercontent.com/36572530/60503952-fcc60300-9cc0-11e9-8f1a-0196b109569d.png)

A discontinuity is visible at p/pc = 1.18; the same is observed in the plots of the thermal conductivity, both for D6 and MDM. I was expecting smoother profiles; is this the expected behavior?

**REFPROP Version**: [Refprop 10.0]
**Operating System and Version:** [Linux]
**Access Method:** [GUI (Wine), Fortran subroutines]

**Comment by EricLemmon** [comment]
I apologize this has taken so long to resolve.

This bug has now been fixed, but is only available in a beta version since we have not fully verified that it has not impacted other transport calculations.  This will happen as the beta is tested by us and others and then the changes will be made available as a minor update to Refprop.

If you would like the beta version, please contact me directly:  Eric.Lemmon@nist.gov
