### ISSUE TITLE
H2O: 6.35%, CO2: 3.38%, N2: 72.97%, O2: 17.29% Mixture Transport Properties

### ISSUE THREAD

**Issue by jafarialireza** [usnistgov/REFPROP-issues#183]
I would like to calculate the transport properties of a mixture including H2O: 6.35%, CO2: 3.38%, N2: 72.97%, O2: 17.29%. But thermal conductivity and viscosity are not calculated.
Could you please guide me on this regard?
![image](https://user-images.githubusercontent.com/52477944/60560353-fa77ad80-9d81-11e9-8686-9b8936f8b9a7.png)

**Comment by ianhbell** [comment]
REFPROP does not support the calculation of transport properties for mixtures containing water at larger concentrations.  An error is returned from the DLL in general:
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
import numpy as np

RP = REFPROPFunctionLibrary('D:\Program Files (x86)\REFPROP')
MOLAR_BASE_SI = RP.GETENUMdll(0,'MOLAR BASE SI').iEnum
hFld = 'WATER*CO2*ARGON*N2'

y = [6.35, 3.38, 72.97, 17.29]
zmass = np.array(y)/np.sum(y)
RP.SETFLUIDSdll(hFld)
r = RP.REFPROPdll('', 'PT','VIS;TCX',MOLAR_BASE_SI, 0, 0, 103000, 630+273.15, zmass);
print(r.ierr, r.herr)
print(r.hUnits, r.Output[0:2])
```
yields
```
541 [TRNPRP error 541] Transport equations are not available for mixtures with water at molar concentrations greater than 5%.
VIS array('d', [-9999990.0, -9999990.0])
```

**Comment by ssb2040** [comment]
@EricLemmon Has this problem been resolved or is there work around?
I was trying to compute the thermal conductivity of a H2O, O2, and N2 gas mixture. 
The gaseous H2O was 8% mol. frac. and the software output the same error mentioned earlier. 
Please advise.

**Comment by EricLemmon** [comment]
We don't have an update for this yet.  It requires experimental data in order to fit the parameters necessary to calculate properties.  For some systems we can estimate the parameters when the two fluids are similar, but water + cryogens is about as non-ideal as it comes.  If you know of experimental data, you could pass them on to Marcia Huber (marcia.huber@nist.gov) and she can evaluate if the data are sufficient to develop the necessary parameters.
