### ISSUE TITLE
fluid file for R-1130(E)

### ISSUE THREAD

**Issue by HightopRaven** [usnistgov/REFPROP-issues#184]
any chance that a REFPROP v10 formated fluid file will be available for R-1130(E)?
[trans-1,2-dichloroethene]
this fluid first appeared in ASHRAE 34-2016 edition and it is a component of the blend R-514A that has been commercialized into products now sold in the market; are there any suitably accurate property data sets to use to create the fluid file? (and as a future follow up question, are there suitable binary interaction parameters with one or more suitably selected components to use it within refrigerant blends such as R-514A)

**Comment by ianhbell** [comment]
Good question!  I think the answer is a no, I don’t believe we have one already.  I took a peruse through the thermodynamic data in ThermoDataEngine for this fluid, and there isn’t too much, so it would be pretty hard to prepare a high-accuracy EOS for this fluid.  Also, it’s not a small task to do that for a new fluid.

Finally, isn’t this fluid banned due to ozone depletion considerations, or is the ODP low enough due to the double bond?

**Comment by EricLemmon** [comment]
Researchers in Japan are currently measuring trans-1,2-dichloroethene, and then a pure fluid equation of state will be developed.  But equations of state are quite complex so this is not a quick process.  

Concerning ozone depletion, indeed the double bond makes this molecule susceptible to the sun's energy, and it breaks apart quite rapidly once released into the atmosphere.

**Comment by HightopRaven** [comment]
R-514A blend components by mass are:
74.7%  R-1336mzzz(Z)
25.3%  R-1130(E)

While R-1130(E) may not be very interesting or attractive as a single component refrigerant, it has already found commercial use within R-514A as a replacement for R-123 used in "low pressure" chillers with centrifugal type compressor. While the ODP of the blend R-514A is non-zero, it was sufficiently low that it has EPA SNAP approval as of May 2016 (with ODP = 0.00006 per USA EPA).

https://www.chemours.com/Refrigerants/en_US/products/Opteon/Stationary_Refrigeration/products/Opteon_XP30.html 

https://www.epa.gov/snap/substitutes-centrifugal-chillers

I understand that a suitable data set may not be published or otherwise in the public domain at this time, but very certain based on commercialization status that at least one refrigerant manufacturer has enough data for an EOS model for thermodynamic properties (but uncertain of the uncertainty level!); and probably also some data for at least some of the transport properties.


![2019-07-10 23_01_57-Clipboard](https://user-images.githubusercontent.com/39253715/61019063-d8c08c80-a366-11e9-985d-2ce19d03a90a.png)

**Comment by HightopRaven** [comment]
Additional info on R-514A:
https://www.fluorineproducts-honeywell.com/refrigerants/wp-content/uploads/2019/01/Kobe-Conf-2018_Kujak-Slides.pdf

**Comment by EricLemmon** [comment]
Their equation is possibly a Peng-Robinson type equation, which will have quite high uncertainties in density (perhaps 10%).  If it is not a PR equation, then they most likely have proprietary data that were used to develop the equation, and without that we cannot develop an equation that could be made available to all.  We have always followed a policy that equations of state in Refprop are "reference" quality, as specified by the "Ref" in "Refprop".  Users of Refprop have come to expect the level of uncertainty that our program gives them.  

It is possible for anyone to add their own Peng-Robinson equation to Refprop, although the process is not simple and is only valid for vapor pressure and density, unless an ideal gas heat capacity equation is available.  And even then, it does not include transport properties.  Furthermore, using this PR equation in mixtures will have even higher uncertainties since interaction parameters are not available for the mixture.
