### ISSUE TITLE
Determine actual reference state in use

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#198]
In the GUI, it is not possible to determine which reference state is _actually_ in use, only to change it from the default.  It would be very useful to be able to determine that without looking at the fluid file, which is the only solution for that problem I am aware of.

**Comment by EricLemmon** [comment]
The GUI has been modified now so that this is shown at the top of the reference state screen.  An example is shown below, note how the top line says "(the default state for this fluid is NBP)".

![image](https://user-images.githubusercontent.com/42392984/65379260-b7432180-dc82-11e9-8327-5c4bb7faa80e.png)
