### ISSUE TITLE
Multiple BNC files

### ISSUE THREAD

**Issue by DrIceCold** [usnistgov/REFPROP-issues#21]
Allow for custom (multiple) XXXX.BNC file(s) to be read after the standard HMX.BNC.

**Comment by EricLemmon** [comment]
This is something we have been considering, but it will not happen for some time due to a number of other issues that require our attention at the moment.  I'm going to close this issue, but will keep it on our list of future enhancements.  Please feel free to write us from time to time to see how the work is going (eric.lemmon@nist.gov)

**Comment by EricLemmon** [comment]
See #80
