### ISSUE TITLE
Correct reference to mixture parameters of R1234yf/R32 in HMX.BNC files

### ISSUE THREAD

**Issue by yodifone** [usnistgov/REFPROP-issues#211]
Hi NIST-Team.

I have some issues for the mixture information given in some different versions of the HMX.BNC file.

In all versions the reference publication for R1234yf/R32 mixtures is the one from Akasaka et al.

When I go for DOI:10.1016/j.fluid.2013.07.057 I see that in the HMX.BNC from REFPROP 9.1 exactly the parameters given by Akasaka et al. are used.

Some time ago we received a changed version from a refrigerant supplier. This file comprised completely different parameters than in REFPROP 9.1. In REFPROP 10 now there are the same parameters used as within the HMX.BNC we got from this refrigerant supplier. 

We were thinking that these differences could be related to the fact that lots of designated refrigerants based on R1234yf/R32 mixtures contain a substantially smaller share of R32 as experimental data were available when Akasaka et al. elaborated these parameters, see Fig. 6.

And unfortunately parameters for TC and VC are not given anymore. Will this be changed in near future? Was this work done for new parameters by NIST or by any third parties (refrigerant manufacturers?) ?

What should be the correct reference for this work? Akasaka et al. are no longer responsible for setting up these new parameters, right?

And my two most important question is:

1. To what extent these changed parameters reflect better the real mixture behavior? What was wrong with the work from Akasaka et al.?
2. Can we trust these new parameters more?

Kind Regards.

**Comment by ianhbell** [comment]
@EricLemmon will chime in on the particular model, and I'll show some data analysis of the model in REFPROP 10.  I took the data from TDE, which includes both bubble-point and dew-point data. These data (markers) were taken from

2013 kam dan 1
Kamiaka, T.[Takumi]; Dang, C.[Chaobin]; Hihara, E.[Eiji]
Vapor-liquid equilibrium measurements for binary mixtures of R1234yf with R32, R125, and R134a
@ Int. J. Refrig.@, 2013, $36$, 965-971

2017 hu yan 0
Hu, X.[Xiaozhen]; Yang, T.[Tao]; Meng, X.[Xianyang]; Bi, S.[Shengshan]; Wu, J.[Jiangtao]
Vapor liquid equilibrium measurements for difluoromethane (R32) + 2,3,3,3-tetrafluoroprop-1-ene (R1234yf) and fluoroethane (R161) + 2,3,3,3-tetrafluoroprop-1-ene (R1234yf)
@ Fluid Phase Equilib.@, 2017, $438$, 10-17

and the isochoric tracer was used to generate the curves.  The code is below, and the picture is here: 

![px_traces](https://user-images.githubusercontent.com/11966765/65470633-3ffbc200-de29-11e9-8da3-1b6ba10c6b1b.png)


Short answer, is that we fit the bubble-point data, upon which the model was developed, well, but don't provide a good representation of the dew points.

``` python
# tracer is at https://github.com/usnistgov/isochoric/
import VLEIsoTracer as vle

import numpy as np
import pandas
import scipy.interpolate
import matplotlib.pyplot as plt

vle.load_REFPROP("D:/Program Files (x86)/REFPROP")
TracerClass = vle.REFPROPIsolineTracer

backend = 'REFPROP' # Placeholder, not used
fluids = 'R32&R1234YF'.split('&')

df = pandas.read_csv('R32_yf_VLE.csv')
Tnoms = [273.15, 283.15, 293.15, 303.15, 313.15, 323.15, 333.15]
for T_K in Tnoms:
    gp = df[(df['Temperature (K)'] - T_K).abs() < 0.1]
    try:
        tracer = TracerClass(TracerClass.imposed_variable.IMPOSED_T, T_K, backend, fluids)
        tracer.set_forwards_integration(True)
        tracer.polishing(True)
        tracer.trace()
        _data = tracer.get_tracer_data()
        x_32 = np.array(_data.x).T[0]
        y_32 = np.array(_data.y).T[0]

        print(T_K)

        line, = plt.plot(gp['(L) Mole fraction of R-32'], gp['Phase boundary pressure (kPa)']*1000, 'o')
        plt.plot(gp['(G) Mole fraction of R-32'], gp['Phase boundary pressure (kPa)']*1000, '^', color=line.get_color())
        for Q, comp in [(0,np.array(_data.x).T[0].tolist()),
                        (1,np.array(_data.y).T[0].tolist())
                        ]:
            plt.plot(comp, np.array(_data.pL), color=line.get_color())

    except BaseException as BE:
        print(T_K, BE)

ax = plt.gca()
ax.set_xlabel('$x_{R-32}$ / molar')
ax.set_ylabel('$p$ / Pa')
ax.set_yscale('log')
plt.savefig('px_traces.pdf')
plt.tight_layout(pad=0.2)
plt.show()
```

**Comment by EricLemmon** [comment]
Here's some background on refrigerant mixtures and the interaction parameters.

April 4, 2013, Refprop Version 9.1:  R1234yf was a new fluid when version 9.1 was released in 2013.  The only mixture in the HMX.BNC file that contained this was CO2/R1234yf.  Interaction parameters for the mixture R32/1234yf were NOT included in this version.

Aug. 15, 2013:  The Akasaka paper showed up several months after 9.1 was released and those parameters were added to the HMX.BNC file.  However, this file was distributed on a very limited basis and most people did not have access to it.

Oct. 20, 2015:  Multiple confidential datasets from several companies were collected and the data were fitted.  We are not allowed to release the data; these companies made the data available only for the purpose of updating the interaction parameters for use in Refprop to standardize the property values throughout industry.  However, the R32/1234yf mixture was NOT refitted, and the Akasaka values are still used.

Feb. 16, 2017:  The HMX.BNC file created in 2015 was permanently fixed and no further changes would be made to it for version 9.1.  This version has been distributed throughout all of the refrigeration industry and has been used as their standard since that time.  The size of that file is 298,280 bytes.

June 4, 2018:  Refprop 10 was released with a new HMX.BNC file.  However, we made the decision to leave all refrigerant pure fluids and mixtures the same as in the Feb 2017 version (with the same values as in 2015) so that the new version would not require any change by industry.  The R32/1234yf mixture still uses the Akasaka values.

Today:  Our group at NIST were recently funded to make numerous high accuracy measurements on a wide variety of refrigerants.  We have also been in the process of refitting R32 and R134a (they are both more than 20 years old now).  All of the interaction parameters for mixtures of R32, R125, R134a, R1234yf, R1234ze(E), and more will be replaced with this new work when done in several years.  A new sub-version of Refprop 10.0 will be released at that time with all of the new equations of state and mixture models.

It is important to realize that although the current mixing parameters may not represent the experimental data perfectly, industry had spent years updating to the values released in 2015, and releasing new interaction parameters would have consequences far exceeding the gains from slightly higher accuracies. 

More in a few minutes...

**Comment by EricLemmon** [comment]
Answers to your other questions:

1)  The HMX.BNC file you got from the supplier may have been the same as the 2017 version (check the number of bytes), or it may have been something where they refitted the coefficients to match their own data.  We highly discourage companies from releasing such versions as it only causes confusion as to which is the official NIST release.

2)  The TC1 and VC1 lines in the HMX.BNC file are generally not used.  The coefficients are simple fits to the critical lines of the binary mixtures.  Calculated values from these equations gives Refprop a rough estimate of the behavior in the critical region, but they are not used in actual calculations.  If the values of the coefficients are all zero, it simply means we have not regressed the critical line values, in which case Refprop uses other methods to estimate the critical region behavior.

3)  We only use interaction parameters in Refprop based on our own fits or on published values in a journal that shows deviations to data, behavior of the model, etc.  We never use parameters from industry, rather they are required to send us their confidential data and then we fit them ourselves (or they need to publish their data and fits, and then we can use those).

4)  I need to explain the words "We" and "own" in the 3rd item.  Ian Bell and I work at NIST and do much of the fitting of pure fluids and mixture models.  But behind us we have quite a number of colleagues (mostly at universities) that work with us to develop these models.  Ian and I supervise all fitting of pure fluids and mixture models, which means that we spend a lot of time training others to fit, and then evaluate their fits until we are satisfied they are done.  Ryo Akasaka is one of our colleagues, and he is still extremely involved in the work.  You will find many publications with him and us together as authors.

I hope we have answered your questions here.  If not, please let us know!

**Comment by RyoAkasaka** [comment]
The mixture model for R32/1234yf in REFPROP 10.0 were fitted also to densities and sound speeds in addition to VLE data, although most mixture models for refrigerant mixtures are normally done only to VLE data. I expect it works reasonably in most cases, at least in engineering applications. In fact, heat transfer analysis or evaluation of drop-in tests for this mixture has been successful with the mixture model. As stated by Eric, this model will be accordingly updated when new equations of state for R32 and R1234yf are available.

**Comment by yodifone** [comment]
Dear all.

All issues are clarified now for us. We were just wondering about these changes in HMX.BNC that came from our perspective from "external parties" that have nothing to do with REFPROP maintenance (refrigerant supplier).

Your replies were more than I expected. Thanks a lot for this feedback!

Kind Regards
