### ISSUE TITLE
Checkboxes in plotting dialog

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-issues#212]
In RefProp 10, when doing a T,d plot, there is an option "swap density for specific volume", but the resulting plot is the same T,d plot no matter whether the box is checked or not.

Changing the x-Axis from Density to Volume will update the check box, 
but changing the check box does not update the x-Axis field.

Also, the "Add s and v lines at saturated temperature" checkbox seems to be broken. To reproduce: Check it, then plot, then uncheck and plot again. Second plot has s and v line even though it should not.

**Comment by EricLemmon** [comment]
The "swap density for volume" option is only for plotting isochores, but at nice intervals of volume instead of density.  This option does not apply to the x-Axis.  There is however a way to make plots for just about anything.  In the middle of the plot menu is a box called Axis Scaling.  On the right hand side of the box are two pull down menus.  You can select any property in those two boxes and those will become your x and y axes.  Once you have this set up, use the Plot/Other Diagrams menu to return to the same setup that you just created to make modifications.

The "s and v lines..." option is something I added over a decade ago for someone who wanted a plot where temperatures were specified, and then an isochore and isentrope would be plotted at the saturated vapor values of the given temperature.  I'm sure this has some practical use somewhere, but you are the first to try this (that I know of beyond the person who requested it).  Below is a plot demonstrating this feature; I asked it to plot isotherms only, and it filled in the other two.  Note how all three colors meet at the same location on the vapor saturation line.

![image](https://user-images.githubusercontent.com/42392984/65937897-8aa7ac00-e3de-11e9-8a4c-ade5eb5bf416.png)
