### ISSUE TITLE
REFPROP Uncertainties

### ISSUE THREAD

**Issue by jbaviation** [usnistgov/REFPROP-issues#215]
I'm trying to quantify uncertainties for humid air calculations performed using REFPROP.  After a substantial amount of digging, I can’t seem to find conclusive documentation supporting an uncertainty comment from ASME MFC-7.  The highlighted comment in the ASME MFC-7 excerpt below suggests REFPROP uncertainties are published and available, yet none of the referenced sources from the ASME standard lead to uncertainty values.  Are there any write-ups or documentation on uncertainty quantification of humid air REFPROP tables?

![RP_Uncertainty](https://user-images.githubusercontent.com/23302791/66154717-1b9fa280-e5ec-11e9-8902-c24323170e56.png)

**Comment by ianhbell** [comment]
I am sure that @EricLemmon will chime in here too, but a direct estimation of uncertainty for the critical flow function is not as trivial as any of us would like.  For a specified temperature and pressure, we can provide pretty reasonable estimates for uncertainty for directly measureable properties like speed of sound and density by referencing the relevant paper where the model is described. For mixtures, this is much more difficult.

In this case, estimation of uncertainty is complicated by the fact that the properties rho^* and c^* are properties that are calculated from equating the entropy and enthalpy with the stagnation state.  Therefore, that calculation introduces additional uncertainty that is very challenging to properly assess.  As a lower limit on the uncertainty, you could consider the uncertainties arising from rho^* and c^* for the throat values of T, p.  But that would ignore the question of the uncertainty in the H,S calculation, or as in the case of REFPROP, tracing to the throat condition from the stagnation state.

**Comment by EricLemmon** [comment]
Take a look at this issue:
https://github.com/usnistgov/REFPROP-issues/issues/161

I uploaded two papers from Aaron Johnson, also of NIST, that might help you with your questions, these can be found at:

https://trc.nist.gov/refprop/Documents/Real_Gas_Corrections_for_CFVs.docx
https://trc.nist.gov/refprop/Documents/Critical_Flow_Factor.pdf

My name is only on the one paper because I helped work out the code in order for him to do the work, he is the real specialist in the area of critical flow functions.
