### ISSUE TITLE
x-axis on p-x diagrams labelled incorrectly

### ISSUE THREAD

**Issue by kjschultz527** [usnistgov/REFPROP-issues#216]
### Description

x-axis on p-x (and T-x?) diagrams is labelled incorrectly.

### Steps to Reproduce

1. Load a predefined binary blend, eg, R421A.
2. Create a p-x diagram.  Note that x-axis is labeled "Mass Fraction".  Copy plot to Excel as picture.
3. Create a corresponding saturation table.  Copy table values to Excel.  Add columns to convert mass fractions to mole fractions.
4. Create chart of the table values, plotting Pbbl and Pdew against both mass and mole fractions.
5. Overlay chart on top of REFPROP plot.  Note that Pbbl and Pdew curves overlay when plotted against **Mole Fraction**, not Mass Fraction.
![image](https://user-images.githubusercontent.com/47403689/66429489-be399600-e9dd-11e9-87e0-da91609a53f7.png)

### Versions

**REFPROP Version:** [REFPROP v10  (DLL version 10.0.068)]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [Accessing REFPROP through its GUI]

**Comment by EricLemmon** [comment]
I opened up the GUI and made some calculations.  You can see them in the first picture below.  In the tables, the top lines are the bubble points and the bottom are the vapor points.  This is shown by the fractions in the respective liquid and vapor columns that match the bulk values of R421A.  In the graph, the black dots are the calculated mole fractions and the red dots are the calculated mass fractions.  The bubble point and dew point lines are for the mole fractions.  Note that the red dots don't belong on that plot because they are mass fractions, whereas everything else, including the x axis, are mole fractions.

I then went into Excel and entered the formulas shown in the second picture.  The calculated values match up exactly with what is in the GUI.  For example, the .697742 in Cell A1 is the same as the vapor phase mass fraction in the middle table in the GUI picture.

(As a side note, to check that I was really using Refprop 10, I put in "=REFPROP("DLL#")" in the spreadsheet and it returned 10.0).

![image](https://user-images.githubusercontent.com/42392984/66451516-fced4180-ea19-11e9-882d-f839df6195d5.png)


![image](https://user-images.githubusercontent.com/42392984/66451607-6d945e00-ea1a-11e9-9a81-c7c73d934be5.png)

**Comment by kjschultz527** [comment]
The problem I was trying to point out is that when making a px diagram, the GUI labels the x-axis as “Mass Fraction” by default when in fact it is in Mole Fraction.  There is no way for the user to know any different (without doing the check I did by coincidence).  I suppose “px” should be the key that the composition is in mole fraction (x).  But the default label should then be “Mole Fraction”, not Mass Fraction.  So, a very simple fix.

Don’t see any option to choose “Mass Fraction” anyway.  Only option is “Composition”, but doesn’t indicate which units (ie, Mole or Mass).
[cid:image003.jpg@01D57E73.43EA6030]

Small bug, but it cost me a half day of work that I had to redo after discovering that the x-axis was mole fraction, not the mass fraction that it was labeled with.  (Was trying to estimate BIPs for a new binary by overlaying the px diagram on a chart with data points.  I would have done everything in Excel and not found this issue, except that I’m using PR EoS for one of the fluids and there’s that big bug in the way.)

**Comment by EricLemmon** [comment]
The picture that you posted above did not come through (I think because you replied by email rather than posting it directly into the github webpage).  I'm not sure that we are seeing the same problem and thus my comments here may not apply.  If so, please let me know what I missed.  

In the Options/Units menu, you can first press the SI button, which then changes the two upper right options both to mass fraction.  You can then change the option in the box labeled "Composition" to "Molar Basis" and then all your plots, inputs, outputs, etc. for composition will be based on moles.  The GUI has been in use for more than a decade now with minimal changes, and this issue has not been reported before.

![image](https://user-images.githubusercontent.com/42392984/66892341-a8613d80-efa8-11e9-838f-d6b65b48f9ca.png)

**Comment by kjschultz527** [comment]
The Select Units window displayed above indicates that Composition is on a **Mass Basis** by default.  But again, the x-axis in px chart at the top of this string is in **Mole Fraction**, even though the Select Units window and the default x-axis label indicate it is Mass Fraction.  I think the px chart above was done correctly and is conclusive.  It appears that the px (and Tx?) chart is generated on a **mole basis** irrespective of the composition basis selected.  I'm surprised that no one has discovered this before. ??
   So, in the px chart you created above, how did the x-axis come to be labeled **Mole Fraction**?  By default or did you actually change the label? Or did you select **Mole Basis** in the Select Units window?
   Did some more playing with GUI px chart.  I get the same picture whether I pick Mass Basis or Mole Basis -- x-axis is **mole fraction** ...
![image](https://user-images.githubusercontent.com/47403689/66921972-c9974d80-efeb-11e9-99fb-69ffbfbfdc28.png)

**Comment by EricLemmon** [comment]
I see that now!  And indeed it is a serious bug in the GUI.  I too am amazed that this has not been reported before, however the code to do this replaced some older code in versions 7.0 to 9.1, so the time frame for people reporting it is much shorter than I thought.

Can you send me a personal email (eric.lemmon@nist.gov).  I will send you an updated GUI, but please realize that this GUI has seen a lot of changes in the section that we use to develop equations of state, but some of that has leaked into the regular code that everyone else would use.  So please watch carefully and report anything you find that is wrong.

I've pasted in a picture below of methane + hexane to show that it appears to be fixed.  I used this mixture since the molar masses are quite different and it is easy to see the differences in the plots.

![image](https://user-images.githubusercontent.com/42392984/66960468-bdca7c00-f029-11e9-80c8-f8501348e03d.png)
