### ISSUE TITLE
SETUP Error 117 - Estimation of mixing parameters is not possible

### ISSUE THREAD

**Issue by CallieAYYC** [usnistgov/REFPROP-issues#22]
[SETUP error 117] Estimation of mixing parameters is not possible for most mixtures containing water, helium, hydrogen, neon, carbon monoxide, fluorine, methanol, or ethanol.

For most hydrocarbon mixtures I work with, it will tend to have at least one or more of these components in it. What does the error message actually mean? It doesn't prevent me from plotting charts or calculating any specified state points as far as I can see within the REFPROP GUI.

Are the results I obtain inaccurate? Does it calculate the properties without these specific components? Are there certain properties that will be inaccurate but others ok? Is it something I just ignore?

If anyone could help me clarify this, it would be greatly appreciated.

![setup error 117](https://user-images.githubusercontent.com/39857380/40876791-53e928b8-6669-11e8-88ec-af85db4d1a33.PNG)
 
Kind Regards
Alex

**Comment by CallieAYYC** [comment]
Edit: I posted the above post before trying the same predefined mixture on latest version of 10a. It appears the latest GUI will not load the predefined mixture anymore if SETUP error 117 appears. Is this the intended behaviour?

Kind Regards
Alex

**Comment by ianhbell** [comment]
Correct behavior or not: https://github.com/usnistgov/REFPROP-issues/issues/22#issuecomment-394088706 ?

**Comment by ianhbell** [comment]
So is this resolved?  If so, please close the issue

**Comment by CallieAYYC** [comment]
Hi Dr Bell,

The issue has been resolved but the question I originally posed has not, which was what effect does Error 117 cause to the end result.

If the question should be better posted somewhere else I can do that and close the issue.

Kind Regards
Alex Chu

________________________________

**Comment by ianhbell** [comment]
That is in fact a good question, to which the answer, annoyingly, is: it depends.  Without knowing what kinds of mixtures you are looking at, it is hard to answer conclusively.  But generally, anytime that you see an error code of 117, you should consider the results with significant skepticism, even if you are able to carry out calculations.  Even if the offending binary mixtures that are causing this issue to be raised are only present in the ppm level, that can still be a problem.  For instance if you have a mixture of methane + ethane, and then a few ppm of hydrogen or H2S, the phase equilibrium behaviors can be *totally* different.  **Caveat emptor**, basically.  For many of these mixtures, you might want to ask the question - well, how far off is the model from reality, to which the answer is, probably, "I have no idea" because you are unlikely to have very accurate measurements at the particular mixture composition and the state point you are interested in.  Without that, it is very difficult to make any assessment of the possible range of error.

**Comment by CallieAYYC** [comment]
Hi Dr Bell,

Thank you very much for the comprehensive answer. It is good to get an understanding of the issue. Mainly I am looking at phase envelope of a mixture and making sure I am either staying in one phase or another keeping away from 2-phase. I’ll make sure to keep a wide tolerance around the curve.

Thanks very much for the answer I will close the topic as solved.

Kindest Regards
Alex

________________________________
