### ISSUE TITLE
GUI calculate specified points named input

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-issues#237]
In the GUI, some named input can be used, I am aware of `crt` and `trp`.
Could you also add `ref` for reference state? And this maps, depending on ref statef to:

- IIR `T=273.15L` (which is the same as entering `T=273.15` and `Q=0`).
- ASHRAE `T=233.15L`
- NBP `p=0.101325L`

![image](https://user-images.githubusercontent.com/314571/72708889-fb2c3180-3b63-11ea-9184-a98c91301449.png)

Sidenote: Entering `p=0.101325` works better if tables use 6 digits!
![image](https://user-images.githubusercontent.com/314571/72785130-cdf68680-3c2a-11ea-9869-4e08fc1c2f0b.png)

**Comment by ianhbell** [comment]
I like this idea a lot and it ought not to be too tricky to implement

**Comment by EricLemmon** [comment]
The three options for ASH, IIR, and NBP were indeed simple to implement, but to add the OTH and OT0 reference states required some modification to the DLL.  I'll send you a link where you can download just the EXE, or the DLL as well if you wish the OTHER reference states.

I added a few other things as well.  You can now enter NBP for the normal boiling point.  When entering ranges for saturation tables or isoproperty tables, you can use "Tc" to enter the critical temperature, Pc for the critical pressure, Dc for the critical density, Ttrp for the triple point temperature, and Tnbp for the normal boiling point temperature.  You can enter the following as well for the EOS limits:  Tmax, Tmin, Pmax, Dmax.

Concerning the number of digits, you can change that yourself and then save those options so that it will always start with six digits.  Simply go to Options/Save Current Options and then save it as defaults.prf.  This applies to all other changes that you make as well in other menus (such as the start up fluid) so that all new sessions will start with your favorite options.

**Comment by thorade** [comment]
Thanks a lot, I will test it in the next couple of days!

**Comment by thorade** [comment]
I downloaded the new files and it seems to work as expected; if I find anything I will report it.
From my side this could be closed, thanks!

**Comment by ianhbell** [comment]
Go ahead and close then :)

**Comment by thorade** [comment]
Today I used this nice feature for water, and it seems to return wrong state (line 1), could you try to reproduce?

![image](https://user-images.githubusercontent.com/314571/93888597-827c0700-fce8-11ea-8927-ac4371328b14.png)

**Comment by thorade** [comment]
Sorry, water uses OTH not NBP, closing again.
