### ISSUE TITLE
Validity of Refprop v. 10 with non-predefined mixtures?

### ISSUE THREAD

**Issue by rllopis** [usnistgov/REFPROP-issues#241]
Dear Eric,
I am Prof. Rodrigo Llopis, from Spain.

There is an interesting issue it should be nice to have an answer from Refprop developers in relation to the accuracy of non-predefined mixtures in Refprop v 10.

In the last years a lot of researchers are evaluating/optimizing new refrigeration cycles (similar to CO2 transcritical cycles), using different refrigerant mixtures (CO2-Ethane, CO2-R32, etc…). Scientists use directly Refprop results based on standard mixing rules, since Refprop is the worldwide reference database. However, my experience with similar mixtures experimentally and Refprop results indicate that there are discrepancies in the real behaviour in relation to that provided by Refprop v.10, especially at low pressures (evaporating level). I suppose it is normal, because Refprop Developers haven’t experimental data with these new mixtures at the moment and only standard mixing rules can be used.

The question is: **It is reasonable to use Refprop 10 results for mixtures not validated yet to evaluate and optimize complicated cycles or it isn’t?**

Thank you very much for your support in advance,

Rodri (rllopis@uji.es)

**Comment by ianhbell** [comment]
Hi Rodri,

My (personal) opinion is that one should be pretty cautious with the estimation scheme in REFPROP for mixtures where no binary interaction parameters have been fit.  In our recent study (https://doi.org/10.1016/j.ijrefrig.2019.05.035) we tried to roughly estimate the uncertainty caused by the estimation scheme in REFPROP, and it doesn't seem to be too horrible to use the estimation scheme for refrigerant mixtures.  Here I mean refrigerant in the classical sense (halogenated alkanes), not mixtures of refrigerants with CO2, which are not NEARLY as symmetric (and easy to model) as HFC-HFC mixtures for instance.

The use of estimation schemes is really only useful for rough answers: _is a mixture going to yield a 20% better COP than R-134a?_  I would definitely not trust it to split hairs of +- 2% in COP.

The core problem is one of education I think.  Many people don't have any idea what is happening inside REFPROP, and they blindly trust the answers coming back without any consideration about whether the results should be believed.  Having written a complete implementation of these models and accompanying algorithms (www.coolprop.org), I have an understanding of how the bits fit together, but that took me two years full time, and is understandably outside the realm of possibility for most users.  Nonetheless, when reviewing papers, make sure to politely ask the authors to think about their modeling approach and verify that it is acceptable.  I have for instance noticed that the estimation scheme is not as good for HFC-HFO mixtures.

**Comment by EricLemmon** [comment]
I've written up some information about mixing rules and prediction schemes in Refprop, you'll find it here:

https://github.com/usnistgov/REFPROP-issues/issues/248

**Comment by HightopRaven** [comment]
Issue 248 (https://github.com/usnistgov/REFPROP-issues/issues/248) is very useful for REFPROP users. Note that a URL for the GERG model is out of date (http://www.gerg.eu/public/uploads/files/publications/technical_monographs/tm15_04.pdf is no longer valid), instead see https://www.gerg.eu/wp-content/uploads/2019/10/TM15.pdf (from https://www.gerg.eu/media-centre/technical-monographs/).

**Comment by ianhbell** [comment]
Thanks I updated the URL
