### ISSUE TITLE
vapor at T<T_trp

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-issues#244]
At temperatures below the triple point temperature, a vapor phase can exist at low pressures, see e.g. the phase diagram on Wikipedia:
https://en.wikipedia.org/wiki/Triple_point
https://en.wikipedia.org/wiki/Phase_diagram

Properties of this vapor phase can also be calculated with RefProp:
![image](https://user-images.githubusercontent.com/314571/73526198-fb081d80-4410-11ea-8acd-4d6029e83e22.png)

As I understand it, the vapor phase can exist even far below the triple point, as long as the pressure is low enough!? Same question, in other words: in a p,T diagram, does the sublimation line start in the 0,0 origin, or does it cross the axes elsewhere? Does it depend on the fluid?
The usable range in RefProp might be limited by the availability of an accurate sublimation line, but it still seems the usable range is smaller than necessary. 

Or is it the availability of experimental data, and therefore the equation of state? For Carbon dioxide I can go very far below the triple point temperature. Does the vapor phase behave sufficiently ideal to allow extrapolation beyond the experimental data set?
Would it be possible to extend the range in RefProp?

The error message in case of failure might also be improved. 

Thanks for considering.

**Comment by thorade** [comment]
Note: I had to edit several times!

**Comment by ianhbell** [comment]
You should be able to get to zero pressure (zero density) along the isotherm corresponding to the triple point temperature. I believe (@EricLemmon correct me if I'm wrong), that the point T=0,p=0 should be the endpoint of the sublimation curve, although there might be multiple crystal phases, and additional solid-solid-vapor triple points to worry about.

**Comment by ianhbell** [comment]
If we don't know where the sublimation curve it, it seems reasonable to take a conservative approach.  You could always plug in T,D, and not allow a phase equilibrium calculation, which will not check the sublimation curve.  At these super low pressures, the assumption of ideal-gas to get the density (or initial density guess if you want a more precise answer) would be quite reasonable.

**Comment by EricLemmon** [comment]
In order to calculate properties for a fluid in the vapor phase for a pure fluid below its triple point, the FLD file must contain a section labeled SBL, which gives the code an equation to locate the sublimation point for any temperature.  If you look in the Substance/Fluid Information window under the Sublimation Line tab, it will show if this is available.  If it is not, then all calculations stop at the triple point.  An equation for helium has not been developed since there is no sublimation line, rather a line of vapor and superfluid helium in equilibrium.  We could, however, put in a pseudo-equation that would make this possible if the pressures along that line have been measured.  

Saying that the equation ends at T=0 and P=0 is a bit misleading since there is no such state (unless you literally could remove every molecule from the space of interest, good luck!)  The sublimation line is a logarithmically based equation, and thus it extends to as low as anyone would ever dare go.  The limitation is the machine precision in trying to calculate properties at such extremely small values.

**Comment by EricLemmon** [comment]
Has this issue been resolved?  It's been about a month since your initial questions and we'd like to know if there anything else.  Also, note the "feature-request" label I added to this to remind us to come back and correct this problem some time in the future.

**Comment by thorade** [comment]
Thanks, all questions are answered for now.

**Comment by bin-cui** [comment]
I still have one question regarding:

> In order to calculate properties for a fluid in the vapor phase for a pure fluid below its triple point, the FLD file must contain a section labeled SBL, which gives the code an equation to locate the sublimation point for any temperature. If you look in the Substance/Fluid Information window under the Sublimation Line tab, it will show if this is available. If it is not, then all calculations stop at the triple point. An equation for helium has not been developed since there is no sublimation line, rather a line of vapor and superfluid helium in equilibrium. We could, however, put in a pseudo-equation that would make this possible if the pressures along that line have been measured.

@EricLemmon Is it only possible to get the property values from the superheated gas or is it also possible to determine the saturation state on the sublimation line below the triple-point when SBL is given (speaking of Parahydrogen)? 
If not, is the assumption of enthalpy very close to the sublimation line = enthalpy on the sublimation line sufficient?

**Comment by ianhbell** [comment]
Please see the docs for ALLPROPSdll, which also apply to REFPROPdll: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/ALLPROPSdll .  Long story short, you can obtain the sublimation pressure from the sublimation curve.

**Comment by ianhbell** [comment]
But see the cautions in https://github.com/usnistgov/REFPROP-issues/issues/362

**Comment by ianhbell** [comment]
So you might want the legacy function: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SUBLTdll (there is also a SUBLPdll)
