### ISSUE TITLE
Helium4 at 0.8K < T < 2.1768

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-issues#245]
RefProp has several equations of state for helium implemented, including the EoS by McCarty and Arp:  
https://link.springer.com/chapter/10.1007/978-1-4613-0639-9_174

That EoS should also cover the region below 2.1768K, the green region called suprafluid in this phase diagram (sorry, in German):
https://commons.wikimedia.org/wiki/File:He4_de.svg
https://en.wikipedia.org/wiki/Lambda_point

Still, I cannot enter values in that region in the GUI after selecting the EoS. Or would I have to edit the .fld file to make it point to the other EoS? Or change something else, like edit limits?

I would like to do some comparison between RefProp and HEPAK:
http://www.htess.com/hepak.htm

Note: I first thought this was the same issue as #244, but it seems helium is just a very special thing.

**Comment by ianhbell** [comment]
Helium is indeed a "very special thing".  Superfluid helium is not included in the model in REFPROP 10; documentation on the EOS for helium-4 is in the works as we speak.

**Comment by EricLemmon** [comment]
We have an old version of a DOS based Refprop that included superfluid helium-4 (the same one as HEPAK), but the model from that never made it into the graphical versions of Refprop because we had expected to have a new model by now, but the work on that model has gone on for over a decade.  It is being done by Vince Arp, now far past the age that most survive and yet he is still as sharp as ever.  He is one of the authors on that first publication you cited above (now over 30 years old).  

Including this model will require quite a bit of new code since it will be completely unlike all other models now available.  It will be part of the helium.fld file, but will not be listed as "FEQ", "BWR", "ECS" or any of the others that are available.  Thus, just dropping the lower limit in the FEQ model in the helium fluid file will lead to disaster.  Do not do that!!!

**Comment by EricLemmon** [comment]
I am closing this issue for now since there is nothing more we can do at the moment with Helium-II, but I have added the "feature-request" flag to remind us that it still needs to be addressed in the future.

**Comment by thorade** [comment]
Thanks

**Comment by thorade** [comment]
NIST Internal Report, NIST IR 8474
An Equation of State for the Thermodynamic Properties of Helium
Diego O. Ortiz Vega, Kenneth R. Hall, James C. Holste, Allan H. Harvey, Eric W. Lemmon
https://doi.org/10.6028/NIST.IR.8474

**Comment by nist-aharvey** [comment]
It should be noted that the EOS documented in NIST IR 8474 is just for "regular" helium; it is not valid in the superfluid region.
