### ISSUE TITLE
miniREFPROP.EXE GUI odd error error report for sub-cooled liquid water

### ISSUE THREAD

**Issue by aikkiqa** [usnistgov/REFPROP-issues#270]
### Versions

**REFPROP Version:** minirefprop Feruary 2000 release
**Operating System and Version:** Win 10
**Access Method:** GUI  

### Additional Information
![MiniRefProp error message](https://user-images.githubusercontent.com/62070850/76442414-ac4e8b80-639f-11ea-8dac-77c8fba6d69e.JPG)
Substance: water
Reference state: default
Specified state points within liquid phase are trapped out as being solid phase.
Iso-property table returns proper phase state for specified state point.
![minirefprop isoprop table](https://user-images.githubusercontent.com/62070850/76443619-7ca08300-63a1-11ea-9596-896c5ddcb7c8.JPG)

**Comment by ianhbell** [comment]
Recommend to first check the melting line values (with 26.9M in the pressure cell).  That will show where the melting line is.
![image](https://user-images.githubusercontent.com/11966765/76448583-f3894c00-63a0-11ea-986e-e7e6ac2fcc75.png)
yielding
![image](https://user-images.githubusercontent.com/11966765/76448672-161b6500-63a1-11ea-9a34-7c45408f4d47.png)
On my side, that calculation worked:
![image](https://user-images.githubusercontent.com/11966765/76448768-46630380-63a1-11ea-842b-13db4dce0712.png)

**Comment by EricLemmon** [comment]
There's a problem with the water equation of state where the equation turns around (unphysically) resulting in states that appear to have the correct behavior, but are very much in error.  These states are far below the lower limit of the formulation, but version 10 will occasionally lock on to one of these states because the tests used to determine its validity all pass, aside from being at a temperature lower than the melting line (resulting in the error message you see).

I believe I have your email address and will send you an update.  If anyone else is reading this and needs the update, send me a personal email to obtain the new DLL (eric.lemmon@nist.gov).

**Comment by EricLemmon** [comment]
Also see #67 and #40
