### ISSUE TITLE
EOS to calculate liquid ethane density using Refprop

### ISSUE THREAD

**Issue by ldovalxx** [usnistgov/REFPROP-issues#276]
Hi Dr. Eric,
 I have an application to determine liquid Ethane density with good accuracy using an EOS.
 The composition of the ethane stream is normally, for example:
 Mix* = 99.235 Ethane, 0.51 Methane, 0.255 Propane or sometimes Mix* = 99.429 Ethane and 0.571 Methane. But the ethane purity is always > 99%. The pressure is ranging from 750 - 850 psig and temp: 45 - 65 oF.
 So, my question is: what is the best EOS (or approach) to be used to calculate the density of liquid ethane using Refprop? The EOS for pure Ethane assuming 100% of Ethane or EOS GERG 2008 assuming the mixtures described above for binary and ternary mixtures ? I have made a comparison between these two EOS (pure ethane and GERG 2008) using Refprop and I have got a maximum difference between them of order of 1% for the above cases and conditions. Gerg TM 15 2007, is claiming an accuracy for ternary mixture of 0.1 to 0.5 % and 0.1 to 0.2% for the binary mixtures of C1 and C2. For pure Ethane we can get 0.03 to 0.05% for the above conditions for temp and pressure.
 Also, TM 15 tested the binary and ternary mixtures with ethane concentration less than 99% (mole fraction) not allowing the validation of the EOSs for the concentration level presented above.
 Thank you
Luiz

**Comment by EricLemmon** [comment]
Hi Luiz,

Most definitely the mixture model will give you the better answer.  In your situation here, you can view it as a small correction from a pure fluid (where in reality a pure fluid can never be obtained).  For example, when we make equations of state, we look closely at the impurities in the samples that people used for making measurements, and then sometimes we correct those values with our mixture models if the authors of the paper indicate what the impurities are.  That way we can give industry a better "pure fluid" equation.  When industry then uses our equations of state, they can use the pure fluid models without correcting for their impurities if they are not so concerned about accuracy, but if they are then they should try to correct the calculations with the use of the mixture models to account for the impurities in their fluid.  

When an uncertainty is reported for a mixture equation of state, assuming that it is a k=2 confidence level of uncertainty (or a 95% band of the difference between the data and the equation), then that uncertainty is close to the maximum errors that might occur, often somewhere between 20% to 80% in composition.  At states very close to the pure fluid, the uncertainty will be much less, to the point that it reaches the uncertainty in the pure fluid equation of state.

One last comment about mixture models, when you use Refprop you should use the default settings for your calculations if you are concerned only about accuracy.  The difference between the models comes only in the choice of the pure fluid equations of state.  The GERG-2008 model uses slightly less accurate (pure still very good) equations for the pure fluids, whereas Refprop uses the most current and most accurate equations available.  For the mixture, the same interaction rules are used in both cases, unless we have updated them as well since 2008.  The only reason the GERG-2008 is in the program as an option is for people who need to be compliant with that standard.

Eric

**Comment by ldovalxx** [comment]
Hello Dr. Eric,

Thank you very much for your elegant answer as usual. We cannot find it in the thermodynamic books. At least, I have never saw it in a book. You should think in write a book one day. I will be the first one to buy it. Also, if you have some published papers talking about this subject it will be very welcome to have it or them.

It is always being a pleasure to be in touch with you,

Kind regards,
Luiz

**Comment by EricLemmon** [comment]
Thanks for the nice comments!

I've been asked to write a number of books, but without cloning myself they will probably never happen.  Refprop keeps me far too busy for such fun.

But this is an excellent resource, albeit a very complicate one:

http://www.gerg.eu/public/uploads/files/publications/technical_monographs/tm15_04.pdf

If all your questions have been answered, please close this issue.

**Comment by ldovalxx** [comment]
Good morning Mr. Eric!

Thank you very much for the below email.

I agree with you. Refprop is much better!

Have a good week,

Luiz
