### ISSUE TITLE
Calorie definition issue again

### ISSUE THREAD

**Issue by BFE614** [usnistgov/REFPROP-issues#284]
Calorie Definition and Steam Conversion Option
[Calorie Definition and Steam Conversion Option.docx](https://github.com/usnistgov/REFPROP-issues/files/4497503/Calorie.Definition.and.Steam.Conversion.Option.docx)

**Comment by EricLemmon** [comment]
We're received your comment, but it may take a few days to process due to the need for an updated item.

Eric

**Comment by nist-aharvey** [comment]
The basic calculations in REFPROP use SI units, which means joules (or kJ, or MJ).  So any results in SI units will be the same regardless of that conversion factor, because no conversion needs to be performed in that case.
It is only when you ask for non-SI units (cal or Btu) that a conversion factor is needed, to convert the SI units calculated internally to non-SI units.  In those cases, the choice exists between the more commonly used "thermochemical" value and the "International Table" (steam tables) value that is used for steam tables and sometimes in other contexts. The relationship of the Btu conversion to the calorie conversion is stated in the Preferences help that you quote in your document.

It does look to me like the documentation in the second reference you cite has written the units backwards.
