### ISSUE TITLE
Density being returned as mol/K

### ISSUE THREAD

**Issue by AndFab** [usnistgov/REFPROP-issues#289]
Hi!

I'd like to get the density inside the two-phase region and I thought that the subroutine PHFLSHdll could work. I realized that the density I got wasn't in [mol/L] but [mol/K]. I thought that it was a typo but then saw that it shows up frequently as the unit for density in the documentation. So the thing is that I can't really figure out if it could be used for what I'm after.

So, what I'm wondering is if this density could be used in a way to get what I want? Or do I have to use a subroutine where temperature is one of the input parameters in order to get the density in [mol/L]?

Thanks!

**Comment by ianhbell** [comment]
If densities are mol/K in the documentation, we'll fix it, that doesn't make much sense as a unit of density :)

To your question at hand, I would do a saturation calculation (either QT or PQ), then calculate the two-phase density from v = x*v_g+(1-x)*v_l.  I'm assuming you mean a pure fluid?  If not, this question gets trickier, and then your approach of a PH flash is the right one.

**Comment by ianhbell** [comment]
Another point: I would also check the output units from REFPROPdll (or other high-level functions).  That should be correct.  If that is not correct, then we have a serious bug in the internals of REFPROP.

**Comment by EricLemmon** [comment]
This is something we found some time ago, see:  https://github.com/usnistgov/REFPROP-issues/issues/44

If I remember right, there was some conversion error when the manual was made that caused this, but this has been fixed so that the next time the manual is made then the units will come out correct.  The densities you are getting really are in mol/L, it is only the documentation that is incorrect.

**Comment by ianhbell** [comment]
I fixed the units on the parameter in the online documentation
