### ISSUE TITLE
Problem with PHFLSH for mixtures of nitrogen and oxygen

### ISSUE THREAD

**Issue by AndFab** [usnistgov/REFPROP-issues#292]
Hi! I have a problem with the enthalpy when trying to use mixtures of nitrogen and oxygen. For a certain interval of mass fractions the problem occurs when the mixture transitions from saturated liquid to subcooled liquid. However, for compositions with fractions outside this interval the problem doesn't occur until reaching a bit further below the saturation temperature.  

This happens when the subroutine PHFLSH is used and the following error message is returned:

[PHFLSH error 2] One or more inputs are out of range: Density above upper limit: D = 74.8461 mol/L, Dmax = 50.9576 mol/L. 

The temperature returned is much higher, which corresponds to a completely different enthalpy difference. The thing is that it works fine using temperature as input parameter instead with the PTFLSH to calculate the enthalpy. 

As an example the mass fractions O2/N2 0.206/0.794 was tested and the result from the GUI was used as a reference. I've used the reference state NBP for both the GUI and the calculations with the subroutines. 
<img width="694" alt="O2N2_206_794" src="https://user-images.githubusercontent.com/61552716/81541145-f689c400-9372-11ea-8526-6357e9f82a30.png">
Here are my results for the phase change for the same composition using the PHFLSH for temperature, density, enthalpy and entropy:
<img width="407" alt="O2N2_206_794_IPSEPRO" src="https://user-images.githubusercontent.com/61552716/81545520-4e2b2e00-9379-11ea-80aa-9b28e0c1948d.png">

Another example of the composition O2/N2 0.10/0.90 where the break occurs at a lower temperature and not at the phase change:
<img width="410" alt="O2N2_10_90_IPSEPRO" src="https://user-images.githubusercontent.com/61552716/81548280-55ecd180-937d-11ea-8b43-c766295c35bf.png">

I didn't manage to find any other issues with this specific problem, and it could certainly be a coding mistake when calling the subroutine, but if you have come across this problem before or have an idea of what could be wrong I'd be thankful for you help.

**Comment by EricLemmon** [comment]
Can you send me a private email so that I can have you two several betas that we have available?

eric.lemmon@nist.gov

**Comment by AndFab** [comment]
An email as been sent to your address.

**Comment by EricLemmon** [comment]
This bug has been fixed now.  The equation of state for nitrogen has an incorrect loop at densities far beyond the triple point density (and far outside the region of validity).  This generally causes no problem.  When used as only a pure fluid, Refprop has sufficient checks to ensure that this root is never found.  But mixtures are different because the boundaries are not well known (for example, the freezing liquid state), and thus a root outside the region of validity could be found and the program may not realize this has happened (because the programmer [me] did not add sufficient checks for such a situation - nearly all of the equations of state in use do not have this second loop).  I've now added a check for this and the proper root is found.

If you are reading this and would like an updated DLL, please contact us and we'll send it to you (eric.lemmon@nist.gov or ian.bell@nist.gov).
