### ISSUE TITLE
Liquid phase not properly displayed for CO2

### ISSUE THREAD

**Issue by ETKern** [usnistgov/REFPROP-issues#295]
Greeting,

in REFPROP 10.0 there seems to be a minor error when displaying the liquid phase of CO2 at higher pressures.

At 70 bar it correctly shows the CO2 as a liquid up to 29,3 °C. But at 80 bar it suddenly shows the CO2 as being gaseous.
When entering the same values in the chemistry webbook, it correctly Shows "liquid".

[CO2 70 bar.pdf](https://github.com/usnistgov/REFPROP-issues/files/4642506/CO2.70.bar.pdf)
[CO2 80 bar.pdf](https://github.com/usnistgov/REFPROP-issues/files/4642508/CO2.80.bar.pdf)

**Comment by ianhbell** [comment]
The critical pressure of CO2 is 73.77 bar, so the discussion of liquid or gas makes sense at 70 bar.  At 80 bar, there is no hard and fast way of defining the transition between liquid and gas.  One possible definition is here: http://www.coolprop.org/coolprop/HighLevelAPI.html#phasesi-function .  But plenty of others are also possible, and I now prefer a definition based on the residual entropy of the critical point.  Long story short, answering that question is more tricky than it sounds.

**Comment by ianhbell** [comment]
Here's our very recent paper on this topic: https://scholar.google.com/scholar?oi=bibs&hl=en&cluster=7973761383081456745

**Comment by EricLemmon** [comment]
There was a bug in the GUI that tripped up the selection of the phase flag causing this to be labeled as a gas.  This only happens when P>Pc but T<Tc, and only when calculating a table along an isobar.  If you would like an updated exe, please email me directly:  Eric.Lemmon@nist.gov  (Ignore my out-of-office message, I will get back to you when I log in.)
