### ISSUE TITLE
HELIUM;WATER mixture: wrong entropy calculation?

### ISSUE THREAD

**Issue by MMCampagna** [usnistgov/REFPROP-issues#297]
I am trying to calculate with REFPROP10 the temperature after an isentropic expansion with the following python script

``` 
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

gas='HELIUM'
vapor='WATER'
yv=515.4e-6

T1=296.69 #K
p1=1.68940e6 #Pa
p2=1.0095e6 #Pa

yg=1-yv
y=[yg,yv]
mix = gas+';'+vapor

root = 'C:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
r = RP.REFPROPdll(mix, "PT","S",RP.MOLAR_BASE_SI,0,0,p1, T1, y);
print(r.Output[0])
s2=r.Output[0];
r = RP.REFPROPdll(mix, "PS","T",RP.MOLAR_BASE_SI,0,0,p2, s2, y);
print(r.Output[0])
```

**Expected behavior:** [I expect a Temperature close to  241.5 K, which is the value obtained for yv= 0.]

**Actual behavior:** [I get a Temperature of 155.98 K.]

Is there a problem with the helium-water mixture at the conditions I am using or I am doing something wrong?

**Comment by EricLemmon** [comment]
I transferred your question to the Refprop-issues site since it deals with the models, not the wrappers.

**Comment by EricLemmon** [comment]
I've added some additional information here:  #298 
If these answer your questions, please close this issue, otherwise let us know what additional questions you have.

**Comment by nist-aharvey** [comment]
While Eric and Ian are right that the models in REFPROP are not reliable for this mixture, there is another reason why, even with a good model for the helium-water mixture, REFPROP might not give a good answer to this particular problem.
In the problem as stated, the water (at least most of it) will precipitate out as ice since the final temperature is below 273.16 K.  REFPROP does not calculate solid phases.
