### ISSUE TITLE
Gasoline mixed with water mixture properties

### ISSUE THREAD

**Issue by sthakris** [usnistgov/REFPROP-issues#300]
Hello, I wanted to calculate the Gasoline mixture properties mixed with varying water content. The composition would be
n-heptane/iso-octane/toulene/ethanol/water. Is it possible to calculate these mixture with REFPROP 10. I tried with REFPROP 9.1 it gives me error as attached here.
![error_msg](https://user-images.githubusercontent.com/65964243/82919208-04943300-9f76-11ea-90f5-2f3b7ac49818.JPG)

**Comment by ianhbell** [comment]
Same problem still.  I've been looking into phase equilibria between binary mixtures of alkanes and water, and it is quite a challenging problem, not the least because of all the different phase equilibria you can end up with (LLE, VLE, detached LLE, etc.).  So this error message remains the status quo.  Do you have experimental data to check against?  If so, then you could check with some simple mixing rules whether you get anything reasonable.

**Comment by EricLemmon** [comment]
Take a look at issue #248, it will give you some information about the new features in Refprop 10 concerning mixture interaction parameters.

**Comment by sthakris** [comment]
@ianhbell, can you please suggest some of the simple mixing rules that i can use for calculating properties it would be helpful. We are planning to conduct experiments for few temperature points.

**Comment by EricLemmon** [comment]
I know I'm not Ian, but I'm still awake!  For starters, using 9.1 is a really bad idea for the mixture you are playing with.  With version 10, all of these fluids have alternative fluids for use in obtaining approximate interaction parameters, and the mixture will load automatically.  Below is a P-T diagram showing what I calculated after I loaded the mixture with equimolar compositions.  The part you have to be really careful about is the LLE, etc., that Ian referred to.  At some point the mixture will separate into two liquid phases and Refprop will not tell you where that happens.  That is a project we are working on now, and Ian can give you more information.  Be sure to read the bottom of #248 carefully about the GERG mixing rules with water.  The second picture below shows you  the Substance/View Mixing Parameters menu.  I asked for the toluene/water system, but it displayed the heptane/water system, which is used as the alternate.  But the mixing parameters are all ones, thus indicating that this mixture has not been fitted, even though it is included in the file HMX.BNC, which contains all of the mixture parameters.  

One other source of information is issue #298.

![image](https://user-images.githubusercontent.com/42392984/82989310-b7d14c00-9fb7-11ea-9bf6-5fdae9113b27.png)

![image](https://user-images.githubusercontent.com/42392984/82989807-79885c80-9fb8-11ea-97b1-f841a79e2c72.png)

**Comment by sthakris** [comment]
@EricLemmon you mean with REFPROP 10 with alternate interaction paramter. Is it possible to have approximate fluid properties for n/heptane/iso-octane/toulene/ethanol/water mixture. 
I also looked on #248 and #298. For now it is ok if i just get approximate values to have tentative values to look.

**Comment by EricLemmon** [comment]
That is correct.  Just be sure to find some backup means to verify that the answers are approximately correct and that the state point is either single-phase or in vapor-liquid equilibrium (in other words, not split into two liquid phases).

**Comment by ianhbell** [comment]
I cannot stress strongly enough how careful you should be when considering mixture values where you have water + hydrocarbon mixtures. Even "approximate" values could be off by orders of magnitude if you are in the liquid region if you have an LLE phase split instead of a homogeneous phase. If possible, I would start off with binary mixtures, in order to sanity check the values that you are getting.

**Comment by sthakris** [comment]
ok i will do so.

**Comment by sthakris** [comment]
Hello there, I purchased the REFPROP v10 and started to use. As per our previous discussion, I wanted to calculate the liquid mixture properties of ethanol/toulene/n-heptane/iso-octane/water with different composition. For the example case i have used same composition for all components. The steps of what i did is attached. It says it uses alternative parameter for similar molecules to calculate. The thermodynamic properties are calculated, however it can not calculate the mixture transport properties. How can i proceed forward as i also need transport properties of the mixtures. 
![Step_1](https://user-images.githubusercontent.com/65964243/83500686-63e6cb80-a4bf-11ea-921c-50fc0f4ffbaa.JPG)
![Step_2](https://user-images.githubusercontent.com/65964243/83500688-647f6200-a4bf-11ea-9f8c-1cac4bffa3fc.JPG)
![Step_3](https://user-images.githubusercontent.com/65964243/83500692-65b08f00-a4bf-11ea-9b72-ffe271b0c780.JPG)
![Step_4](https://user-images.githubusercontent.com/65964243/83500694-65b08f00-a4bf-11ea-8bbc-5256fbc70496.JPG)
![Step_5](https://user-images.githubusercontent.com/65964243/83500696-66e1bc00-a4bf-11ea-9167-d874a44790f0.JPG)

**Comment by EricLemmon** [comment]
Can you email me directly:  eric.lemmon@nist.gov

**Comment by sthakris** [comment]
I have e-mailed you.

**Comment by nist-aharvey** [comment]
It should be noted that the sample mixture given here, and any sort of "water/gasoline mixture" with more than maybe 0.1% water, will certainly form 2 liquid phases.  So any vapor-liquid equilibria coming out of REFPROP will be meaningless, because REFPROP is simply not designed for systems with 2 liquid phases (maybe someday it will be expanded with that capability, but not very soon).
Also of course it is meaningless to talk about the viscosity or thermal conductivity of a 2-phase system.

For systems with 2 liquid phases, some tool besides REFPROP is needed.  The major commercial process simulation software providers all do liquid-liquid (and vapor-liquid-liquid) equilibria.
The only reasonable thing you might be able to do with REFPROP would be to estimate properties of gasoline in the liquid phase with very small amounts of water, but you would need some independent way to figure out the limit of water content before a second liquid phase would form.

**Comment by EricLemmon** [comment]
Did Allan's response help resolve the questions you have?  Even if we provided a way to calculate the transport properties of this mixture, they would still be meaningless as Allan pointed out.  Where are you at now in regards to working with this mixture?

**Comment by sthakris** [comment]
Hello Eric, As my mixture contains far more water 10-30 %. For thermochemistry i used GERG 2008 natural gas mixing model and i am just comparing with the pure species thermodata if the results are resonable or bollox. The trend looks ok, however it gives warning as i said before. Transport properties can not be calculated. However, it would be good to see and compare as thermodata if you provide the was to calculate transport properties. The thermochemistry output results formixture in REFPROP is similar to the mole/mass averaged, which  i compared.
However, i also have one question. In REFPROP, there are lot of mixing model which can be seen in GUI. REFPROP automatically chooses the model based on the first two species in the mixture list. Is there any way, that can i choose different model to get data. If i choose two species lets say 1 and 4 species in list, it again goes back to 1 and 2.

**Comment by ianhbell** [comment]
I would reiterate the comments from my colleagues: _do not believe the numbers coming from REFPROP for this mixture_.  For the pure components, the models will probably be fine, but definitely not for the mixture.

**Comment by EricLemmon** [comment]
As per @Cottbus-BTU request, this issue has been resolved and I am closing it.
