### ISSUE TITLE
GUI REFPROP 10.0 Reports Negative Surface Tension for Saturated Liquid SO2

### ISSUE THREAD

**Issue by TE42** [usnistgov/REFPROP-issues#307]
GUI REFPROP 10.0 reports negative values for the surface tension of saturated liquid SO2 at temperatures slightly below the critical point (see attached Word file with screen shot). Negative values don't seem reasonable. I've also attached the paper by Mulero et al. 2012 that shows the regression is based on data from a paper published in 1929. I suspect the underlying data are of poor quality in this region.
[Liquid ST for SO2.docx](https://github.com/usnistgov/REFPROP-issues/files/4760268/Liquid.ST.for.SO2.docx)

**Comment by ianhbell** [comment]
My recollection is that the functional form is pinned to yield zero at the critical point, but a little wiggle in the critical region wouldn't be too surprising.  I think they just didn't constrain the function to be always positive.

**Comment by EricLemmon** [comment]
This appears to be caused by a negative coefficient in one of the three terms that Mulero et al. used in their surface tension fit.  The surface tension is negative over the last 12 degrees near the critical point.  I've put in a request to get it refit, please email Marcia Huber (marcia.huber@nist.gov) and she will send you an updated file when it is ready.

![image](https://user-images.githubusercontent.com/42392984/84304202-65df0900-ab15-11ea-9db7-a6b039351745.png)

**Comment by TE42** [comment]
Thanks! Please close out this issue at your convenience.
