### ISSUE TITLE
Failure to calculate Cv in 2-phase region

### ISSUE THREAD

**Issue by nist-aharvey** [usnistgov/REFPROP-issues#312]
This might be classified as either a bug report or a feature request.
For state points in the 2-phase region, if you ask for Cv REFPROP returns "not calculated".  But Cv is a perfectly valid quantity in the 2-phase region -- it is a fairly straightforward calculation for a pure fluid although I think it must be messier for mixtures.
The "old" NIST Steam properties program successfully calculated 2-phase Cv for water.

**Comment by ianhbell** [comment]
Yes, I think you mean the approach on the last page of this paper, right: https://doi.org/10.1007/s12665-013-2394-z

**Comment by EricLemmon** [comment]
Under the Special tab in the Options/Properties is an item labeled Cv2Phase.  Selecting this will give you the Cv values for 2-phase states.  This was done on purpose since very few people understand the concept behind two-phase Cv's, and we don't want them blindly using this property when they don't understand it.

**Comment by nist-aharvey** [comment]
@Eric: Thanks, just what I needed.
@Ian: Yes, and there are also several equivalent expressions given in this paper:
https://link.springer.com/article/10.1007/s10765-018-2414-z
I'll close this now.
