### ISSUE TITLE
Passing absolute path to HMX.BNC should always be used

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#313]
If I pass an absolute path to a particular HMX file in one call to ``SETUPdll`` (for backwards compat. with 9.1.1) to initialize a mixture, and then I pass a different HMX.BNC and a different set of fluids in a subsequent call to ``SETUPdll``, the new HMX path should always win, rather than using the old one.  I found I could get this to work by calling:

```
RP.FLAGSdll('Reset HMX', 1)
```
before I called the next one, but I don't think that should be necessary.

**Comment by EricLemmon** [comment]
The program is setup so that the HMX.BNC file is never read in a second time because of the lengthy process of parsing the file.  On the first call to setup, all parameters are stored internally.  They are then extracted from these large arrays into the working arrays when the mixture changes.  However, I can see your point that you sent the setup routine a different hardcoded path on the second call, and thus you expected it to be reread.  There's also the situation where the user might change the working path (via SETPATHdll) or send a path with the names of the fluid files.  I can imagine a scenario where a new fluid file should be loaded but the mixture parameters need not be changed, and thus re-parsing the HMX.BNC would greatly slow down the setup time if the user wishes to switch back and forth between two fluid files only.  I am not sure which is the correct path to follow.  Reading the HMX.BNC file is by far the slowest part of setting up a mixture and thus this flag was put in place for rare cases where one would actually wish to re-read it.

**Comment by ianhbell** [comment]
Yup, I see your point, and setting the flag is not too onerous.  I wish at least there was a warning if the absolute path to the file changes from what is currently in use.  If you had the ability to check hashes of files in FORTRAN, that would be the easiest situation; if the hash is different, reload, otherwise, the file contents are the same, don't reload.

**Comment by EricLemmon** [comment]
I added a simple check for this situation to determine if a path is sent, and if so to check if it is different from the original path where the HMX.BNC file was found.  If it is different, the following warning is sent back:
```[SETUP warning -916] Path to the HMX.BNC file may be different than the one used to first load this file.  Parameters have not been reread. Call the FLAGS routine with "Reset HMX" before calling SETUP to reload the parameters from the mixture file.```
