### ISSUE TITLE
Volumetric expansivity for saturated Methanol vapor may have errors?

### ISSUE THREAD

**Issue by John02139** [usnistgov/REFPROP-issues#322]
### Description

The volumetric expansivity for saturated methanol vapor appears to run up to 50% high for reduced temperatures between 0.47 (240 K) and 0.9 (460 K). The curve produced in REFPROP10 shows a hump between about 400 and 460 K, and the values from 250 to 460 are well above what a corresponding states correlation suggests they ought to be. 

Saturated liquid expansitivity behaves as expected.

### Versions

**REFPROP Version: 10** 
**Operating System and Version: Windows 10**  
**Access Method: Installed exe on PC** 

### Additional Information

Plot of REFPROP numbers is attached, together with comparison to multiple fluids.
<img width="589" alt="Methanol volumetric expansitivity REFPROP-10" src="https://user-images.githubusercontent.com/39748301/89348911-585c8000-d67b-11ea-96a3-a7da9cb2d4fa.png">
<img width="1003" alt="Screen Shot 2020-08-04 at 5 42 12 PM" src="https://user-images.githubusercontent.com/39748301/89348915-5c889d80-d67b-11ea-8891-44ce6f850583.png">

**Comment by ianhbell** [comment]
Interesting (and quite pretty) figure you put together.  It would certainly seem that this EOS is in error. I would concur from other studies I have done on other related properties.  There are active efforts underway to fit a new EOS for methanol, but until that is complete I am not sure I have a better solution to propose.  CoolProp also implements the EOS from Piazza and Span, which has different set of issues: http://www.coolprop.org/fluid_properties/fluids/Methanol.html#fluid-methanol and I would be curious to know if it is better or worse for this comparison.

**Comment by EricLemmon** [comment]
I thought I had left a response to this one, but it is not here nor in any of my sent emails.  Perhaps I accidently closed my browser and lost the message I was writing.  I don't know if github saves text or not, but if not, it's worthy of a "note-to-self" for writing responses.

Methanol is a very strange fluid and does some interesting things as it approaches the vapor phase.  Many years ago in one of my doubting moments I too looked at its equation of state and thought it was totally wrong.  I then learned from someone wiser (and of course older) that methanol is, again, a very strange fluid.  I looked into the publication and found discussion on some heat capacities in the vapor and was amazed at the incredible increase very near the saturation state.  The equation of state matched the data to within some sort of acceptable uncertainty.  However, the data were very old and questionable, and I have always wished for someone to redo those measurements to validate them.  I still believe the equation of state has some serious flaws in it and other methods could be used to help resolve the matter.  However, measuring the fluid's properties is the only sure way to truly validate the uncertainty in any equation.  We will soon start developing a new equation for this fluid, and with our current fitting techniques it may be possible to tease out some of the fluid's behavior in spite of the lack of data.  But I believe we will need other predictive techniques from my colleague Ian Bell or his associates to help resolve the matter in the end.

To help show how the equation of state performs, below are two pictures of the isobaric heat capacity in the vapor phase, the first is for methanol and the second for hexane (chosen because it is not a strange fluid and because its Tc is similar to that of methanol).  The upper line is the saturated vapor state and the other lines are isochores.  The methanol plot shows the very sharp increase in heat capacity in the vapor phase, whereas the hexane plot shows the typical behavior seen in most other fluids.

![image](https://user-images.githubusercontent.com/42392984/90670781-ec4c5100-e210-11ea-9370-ada6429b53bf.png)

![image](https://user-images.githubusercontent.com/42392984/90671208-975d0a80-e211-11ea-8c2c-cdef80781c98.png)

**Comment by John02139** [comment]
Very interesting, Eric!  Might vapor dimerization be a factor here?

**Comment by EricLemmon** [comment]
Most definitely (according to my very limited knowledge of dimerization).  Allan Harvey is probably the one who would really know.

In my ideal world, I like to think of water being in a similar boat (ha ha).  If you could produce a situation where water molecules act alone (as if they were not in the presence of other water molecules) the substance would be very normal, similar to most other non-polar substances, and you could make a simple equation of state for it without the need to account for any anomalies, such as ice floating, a maximum in density at 4 C, multiple melting points, and so.  But to represent the natural properties of water with this new equation you would need to make a second equation for what I call "di-water".  Basically it's just two associated water molecules that are present everywhere with no single molecules hiding in between or in the corners.  You would also need a quad-water equation of state and so on.  Then, combine the equations based on their natural abundance at any given temperature and pressure, add perhaps some limited mixing rules, and you have the real substance we all know.  

But, perhaps it's easiest to just use our current pseudo-pure fluid equation of state for water that gives the properties as they exist in nature and not go to all the hassle I described above.  The same would be true with methanol.

And for those of you reading this and think this is all nonsense, OK, I agree, but it's a fun little thought diversion to take every so often.  My post here is not meant to represent true science but to spark creative thinking and a little bit of fun.

**Comment by ianhbell** [comment]
There's a very large and growing body of work on water's anomalous behavior, which should inform discussions of methanol to a certain extent. Recent work has been looking at water's excess entropy (entropy minus the ideal gas entropy at the same temperature and density) anomalies, and how they relate to breakdowns in other thermodynamic and transport properties.  I would like to say that it is easy to identify the structure caused by the tetrahedral hydrogen bonding in the case of water, but that is not the case.  It isn't so easy to decouple the physics caused by hydrogen bonding and those caused by "classical" behavior.
