### ISSUE TITLE
Refprop 10 startup installation message issue

### ISSUE THREAD

**Issue by Lionnel189** [usnistgov/REFPROP-issues#339]
Hello,
I have an issue regarding Refprop 10. Currently when I launch refprop, I get the following window which stay open infinitely : 
![refproperror](https://user-images.githubusercontent.com/39225690/95045553-8f362d00-06e2-11eb-8028-f56ba26c7a95.png)

REFPROP Version:10  
Operating System and Version: Windows 10  
Access Method: launching .exe

Refprop has been working for months since January, and recently I tried to use it again and get this message.

1.	I uninstalled it and I have been trying the tips proposed in https://pages.nist.gov/REFPROP-docs/#installation-problems. But it remain the same.
2.	The IT manager uninstalled it with RevoUnistaller and cleaned the computer with Ccleaner : The same issue appear
3.	He has been redoing the same and then apply tips proposed in https://pages.nist.gov/REFPROP-docs/#installation-problems. But it remain the same
 
Could you please help me ? Thank you
 
Regards

Lionnel

**Comment by ianhbell** [comment]
I personally have never experienced this issue before.  Perhaps @EricLemmon might have some idea as he is our resident Excel Jedi.

**Comment by EricLemmon** [comment]
This is going to be a problem with your Windows software on your machine.  You have something old in there that Windows is finding and causing it to crash.  It could be from a Windows setup failure, a Refprop install/uninstall failure, or many other things.  There could be a *.msi file on your machine that it found and is causing the problem.  I think you will have to do a web search to see what the real guru's say about how to fix the problem.  If you find a solution, please post it here so that others can benefit as well.  If you can't find a problem, let us know and we'll see if we can further help you.

**Comment by EricLemmon** [comment]
Were you able to solve this problem?  If so, could you leave a note here about how you fixed it.  Others will benefit from what you found!

**Comment by Lionnel189** [comment]
No, unfortunately I did not find any solution.

**Comment by EricLemmon** [comment]
Can you send me a personal email at Eric.Lemmon@nist.gov
