### ISSUE TITLE
THFLSH warning -238 - Two solutions exist for the input values; the higher density root has been calculated.

### ISSUE THREAD

**Issue by CallieAYYC** [usnistgov/REFPROP-issues#35]
### Description

The above warning occurs when in REFPROP GUI entering value for Temperature and Enthalpy. Only option is to accept the higher density root calculation which does not provide the expected results. Is there an option to select the lower density root to be calculated instead?

### Steps to Reproduce

1. Mixture: Methane/Ethane/50/50
2. Pressure 50 bar, Temperature 20°C => Enthalpy = 742.4181 kJ/kg
3. Enthalpy 742.4181, Temperature 21°C => Warning + Pressure = 2151.8 bar

**Expected behavior:** 

Would prefer to have the calculation in the similar region.

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Win10 Pro, Build 17134
**Access Method:** Default REFPROP GUI

### Additional Information

![image](https://user-images.githubusercontent.com/39857380/43308798-995bee6c-917a-11e8-82f1-a46d2936959e.png)

**Comment by paarfi** [comment]
From the Specified State Points page of the help file:
_For state points that are double valued (see the Cautions menu for more information), the character ‘>’ or ‘<’ can be added to the number (before or after) to find the lower or upper root, respectively._

I tried it for your case, and using the > did return the higher density root and suppress the warning message box. Curiously, using the < returned the lower density root, but the warning message box still displayed. Not sure if this is the intended behavior or not.

**Comment by ianhbell** [comment]
That is the correct treatment, there are areas of the thermodynamic surface where two solutions are possible and you need to specify which one you want.  Thank you @paarfi for the input.  The fact that you get a warning when you have specified the desired density solution is a bug.

**Comment by EricLemmon** [comment]
The routines have now been modified so that an input of "TH" will always return the highest root when two roots exists, except for when the highest is out of bounds and then it will return the lower root.  In either case a warning message with the error numbers -238 and -239 will be returned to make you aware of which root was calculated.  For an input of "TH>" only the upper root will be returned when two roots exist, and an error message will only be returned in the case of failure to compute or the state is out of bounds.  The same is true for "TH<", except that only the lower root will be returned.  When using ">" or "<", the warnings -238 and -239 will never occur.  An updated DLL can be obtained by contacting us directly (eric.lemmon@nist.gov).
