### ISSUE TITLE
Fluid name prefix behavior not consistent between REFPROP 9 and 10

### ISSUE THREAD

**Issue by henningjp** [usnistgov/REFPROP-issues#351]
### Description

REFPROP 9.1 (and previous versions) calls to SETUP allowed (_required_?) the fluid string to be prepended with `"fluids\"`.  REFPROP 10(.0.0.0) does not allow this, even though the documentation says it should.  This may have been reported in issue #18 , I believe.

### Steps to Reproduce

1. Make a call from any code to SETUPdll with "fluids\\name.fld" as the fluid string.

**Expected behavior:** should open "hpath" + "\\" + "fluids\\name.fld"

**Actual behavior:** File not found, error 101

This works in REFPROP 9.1, but not in 10.  Of course, both work if the `"fluids\"` prefix is omitted, but the behavior is not consistent between the two versions.

NOTE: Setting the full path (e.g. "C:\\Program Files (x86)\\REFPROP\\fluids\\name.fld") **_does_** work in REFPROP 10.

### Versions

**REFPROP Version:** 10.0.0.0  
**Operating System and Version:** Windows 10  
**Access Method:** C++ wrapper >> direct calls to DLL

**Comment by ianhbell** [comment]
Whether or not this works, I wouldn't recommend it. The recommended approach is to EITHER provide an absolute path to the fluid file names (which has its own problems), or to use SETPATH, which is what I recommend. I recommend the SETPATH solution because it also helps to find the fluids needed for extended corresponding states. Otherwise the use of relative paths or absolute paths causes trouble to find the other fluid files needed.

**Comment by henningjp** [comment]
I'm 100% on board.  It makes sense.  Since version 7, however, the "fluids\" prefix was encouraged and the code comments and documentation (typo and all) should reflect the change.  It broke my code that worked with versions 7, 8, and 9.

![REFPROP Fluids](https://user-images.githubusercontent.com/17114032/98758241-4d14a100-239c-11eb-88a5-126aad7f3268.png)

So some comment/doc changes would help us old guys.  😃

**Comment by ianhbell** [comment]
I'm with you. I'll get the code in the legacy API updated so that the docs will get updated.
