### ISSUE TITLE
Nitrogen coefficients for alpha0 are rounded

### ISSUE THREAD

**Issue by ibell** [usnistgov/REFPROP-issues#356]
The PH0 block:
```
#AUX   !---Auxiliary function for PH0
PH0    !Ideal gas Helmholtz form for nitrogen.
?
?```````````````````````````````````````````````````````````````````````````````
?Span, R., Lemmon, E.W., Jacobsen, R.T, Wagner, W., and Yokozeki, A., 2000.
?
!```````````````````````````````````````````````````````````````````````````````
0.                 !
10000.             !
0.                 !
0.                 !
1 5  1  0 0  0 0 0 !Nterms:  ai*log(tau**ti); ai*tau**ti; ai*log(1-exp(bi*tau)); cosh; sinh
 2.5               1.0                 !ai, ti for [ai*log(tau**ti)] terms
-12.7695270805     0.0                 !aj, ti for [ai*tau**ti] terms
-0.0078416297      1.0
-0.0001934819     -1.0
-0.0000124774     -2.0
 0.0000000668     -3.0
 1.012941         -26.6578784709       !aj, ti for [ai*log(1-exp(ti*tau)] terms
```
has rounded coefficients, sometimes too many significant digits, others too few.  The correct ones are:
![image](https://user-images.githubusercontent.com/1859947/99907858-53b0eb80-2cad-11eb-8e9d-315a98e7c636.png)

```

**Comment by EricLemmon** [comment]
Ideal gas enthalpies and entropies are absolutely my favorite part of equations of state!  (For those of you who don't know me, don't believe this!!!)

First off, neither the PH0 nor PX0 coefficients in Version 10 or the parameters given in the Span et al. publication are correct.  To understand this, I brought up a table in the graphical interface, and first calculated the ideal gas density at 298.15 K and 0.101325 MPa (the reference state).  This gave me a value of 0.04087381159491120 mol/l.  (Note that I cannot simply enter 0.101325 in the pressure column, I must enter the ideal gas density, which produces a slightly different pressure due to the compressibility effects).  In the GUI, I requested the ideal gas enthalpy and entropy listed under the "Special" tab in the property selection screen (Options/Properties).  I then used 298.15 K and this value of the ideal gas density to calculate properties at the reference state, which returned exactly the values in the fluid file, as shown in the first row in the picture below.  I then switched the fluid file to use the PH0 setting, which gave the second line in the table.  For entropy, this reproduced the ideal gas value to nine digits.  When I changed the coefficients in the PH0 section of the nitrogen.fld file to match Span's values, I then obtained the calculated values in the fifth row in the picture, again with nine correct digits.  The error caused by the truncated digits occurs in the 11th spot.  Thus, neither the PH0 values nor those in Span's document give enough values to obtain full consistency.  Additionally, the error in the truncation of the digits in the fluid file is 100 times less than the error in simply not having enough digits in the first place.

I don't know what happened with the PX0 coefficients - most likely an issue dealing with the value of R.  The values in Version 10.0 for PX0 result in the calculations given in the third row, quite similar to the other ones.  By changing the coefficient in the PX0 section from -12.76952708046277 to -12.76952694950840, the h0 and s0 can be correctly replicated as shown in the fourth row.

As a side note on the reason for the introduction of PX0 in Refprop to replace PH0, the PX0 format uses the exact same coefficients and parameters given in the CPP section for the ideal gas heat capacity.  The only additional parts needed are the two integration constants, which can be identified as the coefficients with 12 or more digits.  For PH0, the coefficients have to be modified by the critical temperature, leading to inconsistencies depending on how many digits the person making the modification chooses to use in the fluid file.  At some point in time, we will probably remove the PH0 sections and keep the PX0 sections only.  However, the Fortran code in Refprop does not use by default either one of these sections, they are basically for information only.  The Fortran code instead calculates the integration constants each time a fluid is loaded, thus eliminating any human error that might be introduced when the PH0 or PX0 sections are added to the fluid file.  

As a second side note, for those who are interested in playing with these, you first need to change the reference state from OT0, NBP, IIR, or whatever, listed on line 22 of the fluid file to "NA" (meaning "not applicable").  If OT0 or OTH is used, you will also need to delete the line underneath it.  Then in the equation of state section, find the line with the comments "!Pointer to Cp0 model" and the text "CPP" that starts at the beginning of the line.  Change this to either PH0 or PX0 and it will then use the requested section.  You will need to restart the GUI to make the change happen.

And as a final note, I have changed the parameters listed in the fluid file in the PH0 section to match the values from Span et al, and I have changed the one coefficient under the PX0 section to that listed above.

 
![image](https://user-images.githubusercontent.com/42392984/102439030-b2326680-3fda-11eb-929a-b590d056f8cf.png)
