### ISSUE TITLE
Ethylene Glycol - enthalpy model

### ISSUE THREAD

**Issue by StephanThermo** [usnistgov/REFPROP-issues#359]
Which model is used for enthalpy calculations of ethylene glycol within refprop?

**Comment by ianhbell** [comment]
Do you mean neat ethylene glycol, or ethylene glycol + water?  If the pure fluid, then the properties in REFPROP come from a (so-far unpublished) equation of state (EOS) developed by our colleagues.  The reference to the equation of state is visible in the GUI under Substance->Fluid Information:

![image](https://user-images.githubusercontent.com/11966765/100765699-cadd3280-33c5-11eb-8a88-7256746a11f4.png)

**Comment by StephanThermo** [comment]
Thank you. 
One more question: Which model is used for binary mixtures of ethylene glycol and water? (enthalpy and density is of interest)

**Comment by ianhbell** [comment]
For ethylene glycol + water, the interaction parameters were fit by Eric Lemmon and myself.  Otherwise, the model formulation for ethylene glycol + water is the same as in the GERG model: https://www.gerg.eu/wp-content/uploads/2019/10/TM15.pdf .  The most accurate pure fluid EOS are used, along with interaction parameters to shape the thermodynamic surface.
