### ISSUE TITLE
Wrong thermal diffusivity at critical point

### ISSUE THREAD

**Issue by nist-aharvey** [usnistgov/REFPROP-issues#370]
For a few properties, REFPROP appears to have logic to recognize when it is being called exactly at the critical temperature and density so that it returns "infinite" (in the GUI) for a property that diverges there.  It correctly does this for the thermal conductivity, for example.  For definiteness, we can use the example of water with T of 647.096 K and density 322 kg/m3.
But it returns "infinite" for the thermal diffusivity at that point, which is wrong.  Thermal diffusivity contains thermal conductivity divided by Cp.  Both of those diverge at the critical point, but Cp diverges faster, so the thermal diffusivity goes to zero, not infinity.  You can see this by calculating a few points very near the critical point where you get small positive numbers.

It is also a little strange that some other properties that diverge to infinity at the critical point, like Cp and isothermal compressibility and viscosity (which diverges for the H2O formulation, but not for the formulations we use for some other pure fluids), don't have that logic, so they show very large positive numbers instead.

**Comment by EricLemmon** [comment]
I calculated all the available properties in Refprop to see which showed up as either infinite or zero at the critical point by either extremely large values, or, obviously, something nearly zero, and came across the following:

Infinite:

- Cp                                   
- Cp/Cv                                
- Thermal conductivity                 
- Isothermal compressibility           
- Volume expansivity                   
- Isothermal throttling coefficient    
- dD/dT [P]                  
- dD/dP [T]                  
- d<sup>2</sup>D/dP<sup>2</sup> [T]                        
- d<sup>2</sup>D/dT<sup>2</sup> [P]                        
- d<sup>2</sup>D/(dTdP)                          
- dh/dT [P]                            
- dh/dP [T]                            
- Riem                                 

Zero:

- Isothermal expansion coefficient     
- Isothermal bulk modulus              
- dP/dD [T]                            
- d<sup>2</sup>P/dD<sup>2</sup> [T]                        

I set flags for all of these so that their cells would show either the word "infinite" or the value zero.

Two properties didn't show up as such, even though we know that they fall into this category:

- Viscosity - Infinite
- Speed of sound - Zero

I'm sure there are a few others.  But I'm not sure if we should label them like the others since that would cause a discontinuity when plotting their properties on graphs.  For example, I put two pictures below of the speed of sound vs. temperature very close to the critical point for nitrogen.  The red lines are the saturation curves and all others are isobars.  In the second picture I put in a fake line that shows what the plot would look like if we forced the sound speed to be zero even though our equations can't do that.  First, it's ugly (and ridiculous looking) and second I think it's deceiving to imply that we finally have the ability to reach zero with our equations for the speed of sound.  It also may lead people to believe that the effect is instantaneous at the critical point, when in fact the saturation lines and all other states in this region should start heading to zero below the lower temperature limit of this plot.  In reality, the entire plot is wrong in this very limited range of 125 to 127 K, but we can't just blank out the whole thing.  The equations of state for carbon dioxide and water do a much better job at portraying this, but even they do not go to zero.

I'll put up a new exe for the GUI on the Q drive next time I log in.

![image](https://user-images.githubusercontent.com/42392984/113464080-5e138c80-93e7-11eb-902b-13f1fa98a1fd.png)

![image](https://user-images.githubusercontent.com/42392984/113464108-94510c00-93e7-11eb-8041-cca9e39027ad.png)

**Comment by nist-aharvey** [comment]
I agree that it does not make sense to give zero or infinity for the properties that diverge in reality but where our EOS are not capable of representing that divergence.  Sound speed and Cv are two examples.
Viscosity is a different case because some of our viscosity correlations diverge to infinity (like the one for water) but many of them don't.  Ideally it would print infinity or not depending on whether the correlation had a critical enhancement term or not, but I don't know how hard that might be to implement (probably not worth the trouble if it would be several hours work).
And thermal diffusivity (the subject of the original post) should also be in the list of things that go to zero, because the calculations go to zero so there isn't going to be any discontinuity.

**Comment by EricLemmon** [comment]
How did I miss that one, especially since you discussed it above.  It's fixed now.  I also went through some of the initial settings to find others set to "Infinity" and instead set them to "Not calculated".  That will only show up if no other logic in the code changes it to something else.

This viscosity item you mentioned is indeed a bit more complicated, and I'll let it stand as is.
