### ISSUE TITLE
Loading fld file into mini-refprop

### ISSUE THREAD

**Issue by arockiafenil** [usnistgov/REFPROP-issues#382]
Hello,
I am trying to load the mil-prf-23699 .fld file found in the NIST IR 8263 report into mini refprop (version 9.5). I get an error saying "Selected equation of state (NBS) not found for component 1.

I am attaching the snapshot of the error message for reference. 
![refprop error](https://user-images.githubusercontent.com/79581843/109103368-c6b87b00-7750-11eb-8065-dca0eb613ed3.JPG)

Is it possible to load additional fld files into mini-refprop

**Comment by EricLemmon** [comment]
If you download the 10.0 version of Mini-Refprop then this should be able to work for you.  You'll find it here:

https://trc.nist.gov/refprop/MINIREF/MINIREF.HTM

**Comment by arockiafenil** [comment]
Thanks for the reply. I downloaded the mini-refprop from the link you had given and replaced the refprop.exe with the latest version as mentioned in the website
![mini_refprop _version](https://user-images.githubusercontent.com/79581843/109109768-f02ad400-775b-11eb-8428-403f3c3a9e89.JPG)
 After installation it still shows that the version is 9.5. I tried loading the fld file and it gives the same error message.

**Comment by EricLemmon** [comment]
Ah, it looks like it has not been updated to the version 10.0 code.  In this case I changed the *.fld file for this fluid and made it work with 9.1, although I had to remove the viscosity equation because it was not compatible with that version.

Please send me a personal email and I will send you the file:  eric.lemmon@nist.gov
