### ISSUE TITLE
Abnormal behavior in mixture of ammonia/butane and some other mixtures with ammonia 

### ISSUE THREAD

**Issue by mina-shahrooz** [usnistgov/REFPROP-issues#394]
Hello

I have an issue regarding some mixtures in `REFPROP 10.0.0.92`. I am analyzing different mixtures whose interaction parameters are available in REFPROP. While mixing ammonia with many fluids, I get very abnormal behaviors. I call  `SATSPLN` routine at the beginning. I also check` r.ierr` not to be higher than `0`. I had the same problem with previous versions of `REFPROP 10`. 

For example, in the mixture of `ammonia/butane`, by changing the composition and plotting bubble and dew temperatures, it is observed that the dew temperature goes below bubble temperature which is clearly wrong.

What can I do to fix this issue?

Thanks.
![image](https://user-images.githubusercontent.com/46826765/112545453-83394700-8db8-11eb-9869-9b070fc533e9.png)

**Comment by ianhbell** [comment]
There are a few important points here:

1. A lot of the ammonia + X mixture models in REFPROP 10 need to be revised.  In particular, many of them predict LLE where only VLE should be found, or vice versa.  I would definitely not trust them without validation against experimental data
2. In this case, you have LLE, whereas REFPROP doesn't look for LLE.  You should consider (since you are already working in Python), to trace the isotherms of the phase envelope with this: https://github.com/usnistgov/isochoric .  That will highlight that you are running into instability of the VLE solution.
3. I am working on algorithms that will identify LLE and VLE behaviors in the same tracing process, but the algorithms are not yet ready.  They work in some cases, but not in others, and I don't yet have a general solution that is reliable in all cases.

**Comment by EricLemmon** [comment]
I looked at this issue last night and found that there seems to be two solutions (or more) to the problem, with these solutions coming from the equations of state in use.  One obviously is a false solution.  The other is perhaps not correct, as Ian pointed out.  Fixing the problem will probably require a new equation for butane, which is now about 18 years old and not up to our current standards (for example, the exponents on density are as high as 10, whereas we now limit that value to just 3 to avoid excessive loops in the two phase, which is where the problems come from).  A new mixture model will then be needed, but above all, new fluid measurements would be required to ensure that the model is correct.

One thing I noticed as I played with this is that different roots are found depending on the composition sent to the SATSPLN routine (i.e., calculating the full composition spectrum without calling SATSPLN at each composition).  I tried initial values of 50/50, 75/25, 25/75, 90/10, etc., and was able to see at least two solutions as I calculated the full P-x space, with the solution depending at the initial value sent to SATSPLN.  A good model should not do this because the roots are stable and the algorithms find them easily.  

There is much to be done in the area of equations of state, mixture models, and algorithms!

**Comment by ianhbell** [comment]
@Shahrooz87 Please show your code for future issue postings.

**Comment by mina-shahrooz** [comment]
Hi,

Regarding your statement @ianhbell, 

> A lot of the ammonia + X mixture models in REFPROP 10 need to be revised. In particular, many of them predict LLE where only VLE should be found, or vice versa.

How can I reference this statement in a paper? I am evaluating the performance of mixtures whose interaction parameters are available in REFPROP. For couple of mixtures of NH3 + X, binary interaction parameters are available, but the model does not work fine, same as the mixture in this issue.

On the other hand, I want to mention the results obtained by REFPROP for other mixtures, whose interaction parameters are obtained by experimental data, are reliable.

Could you please comment on this statement?

**Comment by ianhbell** [comment]
You could reference this issue thread I suppose.  It's not an ideal solution, but I don't have a better idea.
