### ISSUE TITLE
Isobar calculation failure for deuterium

### ISSUE THREAD

**Issue by nist-aharvey** [usnistgov/REFPROP-issues#397]
This bug occurs in the REFPROP 10.0 GUI
1) Choose deuterium as the fluid
2) Isoproperty tables, constant pressure.
3) Choose pressure 0.01 MPa, temperature from 20 K to 100 K in increments of 10 (these should all be vapor points)
4) Error from TPFLSH -- it apparently fails for the 20 K and 30 K points, then works fine for the points 40 K and above.

The strange thing is that if I go to Specified State Points and give it the same points (for example, 0.01 MPa, 20 K) it works fine.  So somehow it is calling TP flash differently from the isoproperty calculation, even though the TP conditions are identical.

**Comment by EricLemmon** [comment]
This one is fixed now.  The call to the saturation routine failed because the pressure was less than the triple point pressure and no sublimation equation is available below that.  This produced an error number, and the GUI did not recognize why.  But it does now!  When that error number comes back, it now knows that the point is in the vapor phase and continues calculations.

I'll upload a new exe to the Q drive next time I log in.
