### ISSUE TITLE
MILPRP23699.FLD not working

### ISSUE THREAD

**Issue by johnpula** [usnistgov/REFPROP-issues#399]
### Description

Referencing NISTIR 8263 (Thermophysical Properties of Polyol Ester Lubricants), I grabbed the MILPRP23699.FLD text, but cannot for the life of me get it to load into REFPROP v9.1. I get a series of FORTRAN errors. A colleague tried it in v10 and got SETUP Error 102. I suspect this is a syntax error in the fld file, but I can't find much in the way of guidance to help me debug it.

### Steps to Reproduce

1. Get text from aforementioned paper into a text file, save as MILPRP23699.FLD (also attached)
2. Place file in REFPROP/fluids
3. Open REFPROP
4. Substance->Pure Fluid->All Fluids->MIL_PRF-23699

**Expected behavior:** Ability to interrogate 23699 fluid properties

**Actual behavior:** Fortran error

### Versions

**REFPROP Version:** 9.1  
**Operating System and Version:** Windows 10  
**Access Method:** REFPROP.exe  

### Additional Information

If possible, please post examples and/or screenshots of the issue.

[MILPRF23699.FLD.txt](https://github.com/usnistgov/REFPROP-issues/files/6326738/MILPRF23699.FLD.txt)

![image](https://user-images.githubusercontent.com/82670514/115057466-f48c8700-9e98-11eb-8dfb-6ecf9a2b3a2d.png)

**Comment by ianhbell** [comment]
Well, for one make sure you give the file the extension .FLD.  Please try this one in v10 (won't work in v9.x):
[MILPRF23699.FLD.txt](https://github.com/usnistgov/REFPROP-issues/files/6327096/MILPRF23699.FLD.txt) (rename to .FLD)

**Comment by ianhbell** [comment]
In some places spacing is important.  We should have made all the files available as text files rather than in the report.

**Comment by johnpula** [comment]
Thanks @ianhbell . We'll give that a try. I renamed the file I attached to *.txt because Github didn't want to accept a fld file.

**Comment by ianhbell** [comment]
Yeah, I noticed that too.  If this still doesn't work, email me (ian.bell@nist.gov) and I can email you the .FLD directly.  I think the issue was the formatting of your FLD file, and I think it should be sorted now.

**Comment by EricLemmon** [comment]
The fluid file for this substance will not work in Refprop 9.1.  It uses a text style that allows us to enter any functional form for the transport equations.  This style was inspired by my years as a teenager when I wrote a word-processor in assembly language on a TRS-80 with a cassette recorder instead of a floppy disk (or even a hard drive!).  We found a program written in Basic in a magazine, typed it in, spent days finding our typos, and finally got it to work, only to be sorely disappointed by how slow it was.  I spent the next two years learning assembly language while rewriting the program into something useful.  That experience taught me a very different way of thinking, something that is quite similar to the old HP reverse Polish calculators.  

Below is the text I referred to for this substance, enjoy reading it if you are as nerdy as me...
```
!
!Dilute gas
$DG CNST CNST CNST TEMP * SQRT * * DC THRD2 POWR * OMEGAS /
!
!Residual function
$RF RED DR CNST POWR TR / =DEL SUMDEL:4 SUM:2 + DR THRD2 POWR *
!
!Coefficients
$CF
0.040785               0.   0.    0.  0
0.73267                0.   0.    0.  0
557.6                  0.   0.    0.  0
1.                   930.   0.439 0.  0
3.35                   0.   0.    0.  0
 3.03845876244641      0.5  1.0   0.  0

... (additional lines of coefficients not included here)

```

**Comment by johnpula** [comment]
That worked! Thanks @ianhbell and @EricLemmon . Verified against the values in the paper as well. I don't suppose there's a guide to writing these files that I missed upon first search to save you the time on this in the future?

**Comment by EricLemmon** [comment]
Glad to hear!  There are very few people who have ever tried to put these together, so we have not written anything up on it.  And in fact we don't encourage it all, as you have seen, even very small errors can result in wrong values or crashes.  It's best to request them from us and we are happy to send them along!
