### ISSUE TITLE
[TDFLSH error 224] Dew point calculation did not converge. 

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-issues#406]
Running RefProp 10.0 on Windows 10 64bit, calling the DLL from Modelica using a wrapper developed by Modelon.

For some inputs, I get the error message
`[TDFLSH error 224] Dew point calculation did not converge. `
Would it be possible to enhance this warning to also print the input values, including units?
`[TDFLSH error 224] Dew point calculation did not converge for input T=123K. `

**Comment by EricLemmon** [comment]
I tried the TQ input you showed but did not get the 224 message, rather a SATT message about the failure.  I then traced into the code and found it was simply a matter of numerical precision and changed it so that the tolerance (which was set to less than a part per billion) was changed slightly if things were not converging.  I also updated the 224 message so that it will return temperature or pressure input values when it occurs.

**Comment by thorade** [comment]
Thank you for the update and the code changes! I was getting the 224 message only from the Modelica wrapper; from the GUI I was also getting the SATT message.

**Comment by thorade** [comment]
Hi,
posting on this old/closed thread because I think it is related, not 100% sure.
R22 ph flash is failing close to the critical point, see below screenshot:
![image](https://user-images.githubusercontent.com/314571/143839121-c1819fb6-eb13-4947-a000-bc78edffd628.png)


For some inputs, the iterations seem to fail silently, no output is given but also no error message:
![image](https://user-images.githubusercontent.com/314571/143841058-bab4e26e-8856-4fb0-9aed-12491f58eb72.png)
