### ISSUE TITLE
Helium-4 property data generation in superfluid region

### ISSUE THREAD

**Issue by lnbusch** [usnistgov/REFPROP-issues#413]
First off: I am well aware that this is the directory for Refprop core issues.

BACKGROUND:

I am currently using ASPEN HYSYS as a wrapper for Refprop in order to investigate a helium process in which also He-II occurs.
So far, this mostly returned values matching literature data quite well.

To give a specific, simple example:
The expansion of a helium flow at 4.5 K and 130 kPa absolute pressure (saturated liquid) via a Joule-Thomson valve to 1.6 kPa yields a temperature of 1.79 K and a vapor quality of 0.46 - an absolutely reasonable result.

Now, when trying to cross-check this or similar state points with refprop.exe (DLL version number 10.0), I receive the following error:
[TPFLSH error 1] One or more inputs are out of range; Temperature below triple-point or minimum temperature: T = 1.80000 K, Tmin = 2.17680 K.

Thus, at first, I assumed that ASPEN would be extrapolating the data below the superfluid transition temperature ("Tmin") in some way.
However, after contacting their technical support about more details, I received the following answer:

"We were able to verify that all the data available when using RefProp fluid packages comes from NIST's code and at AspenTech that code is directly implemented in HYSYS and Aspen Plus. Since the code is not developed internally, we aren't able to explain how the data below the superfluid transition temperature is generated."

So, this brought me back here.

QUESTIONS:

How are data in the superfluid region of Helium-4 generated in Refprop?
Is there a way to bypass the lower temperature limitation for the output of refprop.exe?                                                                                             

### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Windows 10 64-bit 
**Access Method:** ASPEN HYSYS  V10, refprop.exe

**Comment by ianhbell** [comment]
Yes, this is the right place for this question. Fatal errors are usually error codes > 100, so you could try to ignore the error, but that might be a question for Aspen.

**Comment by lnbusch** [comment]
Ian: thank you for your reply.

If I ignore the error, the Refprop GUI does not return anything (see screenshots, example: slightly subcooled liquid in superfluid region).

Indeed, Aspen seems to ignore the error. 
However, according to their reply, Refprop must provide them with _some_ data in that region. 

This is why I had to draw the conclusion that the error in the Refprop GUI is merely an output barrier to avoid the return of potentially signigicantly inaccurate values below the transition temperature. 

Is this correct? And if yes, how are the values generated?

![issue_1](https://user-images.githubusercontent.com/85349737/120814237-f7c5fa00-c54e-11eb-835f-c3e2e38c4232.PNG)
![issue_2](https://user-images.githubusercontent.com/85349737/120814254-fbf21780-c54e-11eb-86ea-dbdddd364e9e.PNG)

**Comment by nist-aharvey** [comment]
The equation of state for helium used in REFPROP is not fitted to any data for superfluid helium and is not valid in the superfluid region.  However, since most thermodynamic properties (as opposed to other properties like viscosity) do not change drastically in that region, it is not surprising that the REFPROP EOS would give reasonable results when extrapolated a relatively short distance into that region.

As you surmised, the limit is there to prevent people from trying to perform calculations outside the range of validity.  It seems like Aspen is probably calling the underlying REFPROP routines in a way that bypasses or ignores that boundary check, whereas the REFPROP GUI treats it as a hard limit.
While it is not recommended, you could check to verify what was going on by editing the HELIUM.FLD file in the FLUIDS directory (be sure to keep a copy of the original so you can go back) and changing the "Lower temperature limit" associated with the equation of state.  My guess is that this will match what you get from Aspen (although an additional question would be whether Aspen is up to date with the latest REFPROP, since the helium EOS changed from REFPROP 9 to REFPROP 10).
Again, this would represent using the equation of state where it is not valid, but it seems like at least these results are not unrealistic.  The REFPROP code will still look to solve the equation of state using its normal algorithms if the limits are ignored, and will converge if you are lucky, but you (or Aspen) do so at your own risk.

EDITED TO ADD: That Error dialog that pops up in the REFPROP GUI is not asking whether to ignore the limits; I don't think there is any way from within the GUI to get it to ignore those limits.  The main purpose of that dialog box is if you ask REFPROP to compute multiple points -- when one point fails it is asking whether you want to "Continue" to try the subsequent points in the table.  Admittedly the way it is phrased is a little misleading if you have only asked for one point since there are no additional points to continue and calculate.

**Comment by EricLemmon** [comment]
The equation of state for helium is the only one in Refprop where you absolutely should _not_ extrapolate below the lambda line.  Helium does not have a triple point like all other substances, rather it goes superfluid at 2.1768 K at the saturated liquid state.  In the single phase the lambda line temperature drops some until it intersects the melting line.  The lambda line can be thought of as a line of critical points from the saturated liquid at 2.1768 K to the melting line.  At any state approaching this line, the heat capacity rises rapidly and other properties behave in a similar fashion to those at the critical point of any substance.

When we developed the equation of state, it was not possible for us to represent these properties right at the lambda point, but we were able to approximate the characteristics.  Take a look at the plot below, where I changed the lower limit to bypass the error message.  The red line is the 2.1768 K isotherm.  The black lines are isochores, the blue line is the saturated liquid line, and the yellow line is the melting line.  I forced the isochores to go into the solid phase as if they were liquid for those that intersect the yellow line.  The lambda line occurs at temperatures below the red line, except at saturation, however I don't have those values to be able to plot them here.  Each isochore should go to very high Cv values at the lambda line, whereas our equation begins that transition but is far from correct.  

Below the lambda line, the Cv values should drop, not continue to increase as shown in the picture.  Other properties from the EOS will behave incorrectly as well.  This is why any extrapolation below the lower temperature limit in Refprop should not be attempted for helium.  Eventually we will add an equation for super-fluid helium, but that is not ready now.

There are countless pictures on the web that show this behavior and other plots that are extremely useful.  Simply search for "helium lambda line" and you will have an endless supply of good reading to be done.

![image](https://user-images.githubusercontent.com/42392984/120908635-6ecfc100-c629-11eb-88bc-7e9def5a3d09.png)

**Comment by nist-aharvey** [comment]
Yes, Eric is right that for quantities that involve the derivatives that do funny things at the lambda line, like heat capacities and sound speeds, the properties in the superfluid region from the EOS in REFPROP will be very wrong and can't be trusted at all.  I should have been more negative about the possibility of extrapolation in my reply.

For quantities that are continuous across the lambda curve, like the vapor-liquid saturation pressure and the liquid density, short extrapolations may give reasonable results, but if anything of value depends on the answer you should check it against real data before trusting it.  And if it is important, you are MUCH better off not extrapolating at all and using real data for the superfluid phase to figure out what happens on the other side of the transition.
Perhaps you can do something like use REFPROP to expand down to 2.18 K, and then do some hand calculations (or maybe Aspen allows you to make a user-defined thermo routine and/or user-defined flash calculation?) to go the rest of the way.

For your expansion calculation, there are sort of two parts to the answer.  One is the saturation temperature of helium at 1.6 kPa.  This pressure/temperature relationship is actually a part of the definition of the international temperature scale ITS-90, so you can go to the equation in Section 3.1 of this paper to see how close your 1.79 K is to the right answer:
https://iopscience.iop.org/article/10.1088/0026-1394/27/1/002
[Looking at a table I have, it appears the 1.79 K is pretty close; 1.6 kPa corresponds to about 1.795 K.]
That equation can give you the saturation vapor-pressure relationship independently of REFPROP for doing rigorous calculations involving the superfluid.

The other part of the calculation is the enthalpy balance that will dictate the vapor-liquid ratio, which could be significantly in error because as Eric notes the superfluid heat capacity from REFPROP will be wrong.  That error would probably accumulate the farther into the superfluid region you go.  For correct enthalpy of the saturated liquid, you could use the recommended values from this 1998 paper:
https://aip.scitation.org/doi/abs/10.1063/1.556028
The enthalpy values for the saturated liquid are in Table 7.6.  Figure 7.6 is also informative in showing how extrapolating the enthalpy from above the lambda temperature would be in error.  That paper also gives original data sources for properties of liquid helium, both regular and superfluid.  I believe the heat capacity has been measured pretty well, which means the liquid enthalpy should be known well.

Unlike for the liquid, I think properties of helium vapor from REFPROP extrapolated below the lambda temperature should be OK, since the superfluid behavior and accompanying thermodynamic divergences only occurs in the liquid.

**Comment by lnbusch** [comment]
Allan, Eric,

thank you very much for your extensive answers that go beyond what I originally wanted to know, which I highly appreciate.

Allans recommendation of changing the .fld file in principle works well for me.
This way, I should be able to check what values ASPEN is using (it seems like the default enthalpy reference states in Refprop called by Aspen and Refprop GUI are somehow different which I will need to align).

As Eric's exemplary, yet thorough visualization shows, the property values can indeed differ significantly from the truth, which is what I intended to at least get a feeling for.

Allan, you are absolutely right about the expectations on the extrapolation accuracy of saturated liquid Helium's enthalpy below the lambda temperature arising from Figure 7.6 in:
https://aip.scitation.org/doi/abs/10.1063/1.556028

I would like to point out again, however, that for liquid-vapor ratio _approximations_, ASPEN HYSYS with Refprop as a fluid package to a seemingly significant extent returns satisfyingly accurate results. 
In comparison with HEPAK (based on NIST Technical Note 1334 (1989)), for example, flash calculations of vapor quality from 

1. 2.2 K and 1.3 bar(a) and
2. 3.0 K and 2.3 bar(a)

to 55 mbar are only 

1. ~0.4 % and
2. ~0.8 % 

off. I thought this might be some interesting initial input for you for future references as well.

Since my initial questions are more than answered, from my side, you can gladly close this issue.

**Comment by EricLemmon** [comment]
Thanks for the feedback and additional information.  We have much to do when it comes to helium!
