### ISSUE TITLE
How do I calculate %Liquid by Volume for a mixture

### ISSUE THREAD

**Issue by AndrewLindsay** [usnistgov/REFPROP-issues#427]
Similar to the issue below, maybe I'm just too long since I've done any meaningful chemistry, but when I calculate the state of my mixture at a given temperature and pressure, is there a way to calculate the %Liquid by volume easily?
It's been a long day trying to get my head back around Thermo, and any assistance would be appreciated.

**Comment by ianhbell** [comment]
Do you really want what you are asking for?  Volume fractions are always tricky because volumes are not exactly additive in the way that mass and moles are.  

But I could also imagine you have a cylinder of fixed volume and you just want to answer where the miniscus is.  In that case you can get it from 

vf_liq = V_liq/V_tot = (v_liq\*n_liq)/(v_tot\*n_tot) = v_liq/v_tot*x_liq

where:

v_tot = v_liq\*x_liq + v_vap\*(1-x_liq)

and x are mole fractions, and v are specific volumes (on a molar basis), and liq and vap correspond to the liquid and vapor, respectively.

**Comment by AndrewLindsay** [comment]
Yes, unfortunately that's what I'm after.  I am trying to create up updated brittle fracture model using updated thermodynamics, and one of the key elements of the model is the volume fraction of liquids in the pipeline.

**Comment by ianhbell** [comment]
In that case, see my response above

**Comment by AndrewLindsay** [comment]
Thanks. That’s greatly appreciated.
