### ISSUE TITLE
DSAT allows invalid densities

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#432]
For nitrogen, a saturation density to DSAT that is invalid does not return an error.  The density of the saturated liquid at the triple point is 867.2219931199292 kg/m^3, but an input of 1201 kg/m^3 doesn't cause an error.  The critical temperature of nitrogen is 126.2 K, so the returned value makes no sense.

```python
import os
import sys
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RPPREFIX = os.getenv("RPPREFIX")
RP = REFPROPFunctionLibrary(RPPREFIX)
RP.SETPATHdll(RPPREFIX)

print("SYSTEM", sys.platform)
print("VERSION", RP.REFPROPdll("", "", "DLL#", 0, 0, 0, 0, 0, [1.0]).hUnits)
print("")

# define unit system
UNITS_SI = RP.GETENUMdll(1, "SI").iEnum

# Confirm triple point (liquid) density
rt = RP.REFPROPdll("NITROGEN", "TRIP", "D", UNITS_SI, 0, 0, 0, 0, [1])
print("rho(trip liq)", rt.Output[0], rt.hUnits)

if __name__ == "__main__":
    fluid_str = "NITROGEN"
    density = 1201 # kg/m^3

    err_code = RP.SETFLUIDSdll(fluid_str)
    if err_code >= 100:
        raise ValueError("Error setting fluid")

    rt = RP.REFPROPdll("", "DSAT", "T", UNITS_SI, 0, 0, density, 0, [1])

    print("ierr", rt.ierr)
    print("T", rt.Output[0])
    print("Q, COMPUTED", rt.q)
```
yields
```
SYSTEM linux
VERSION 10.0.0.95d

rho(trip liq) 867.2219931199292 kg/m^3
ierr 0
T 212.17832156677915
Q, COMPUTED 0.0
```

**Comment by EricLemmon** [comment]
The temperature that was returned to you is the melting temperature, which is still a saturation state.  The picture below shows this.  In the GUI, I calculated the T and P for a saturated density of 1201 kg/m^3 and it returned the temperature you reported and a pressure of 1242 MPa, which is still in the valid range for the nitrogen equation of state.

Changing the code so that a person would be required to enter "Dmelt" instead of "Dsat" seems like a good alternative, but it would break existing code.  I use the Dsat command to find the lowest possible temperature for a given density, even if that density is along the melting line or along the sublimation line.  This way I am not required to know if the density I send to the code is VLE only, all I care about is how low in temperature can I go and still be single phase.  There are many more examples that would require code rewrite if such a change were made.

![image](https://user-images.githubusercontent.com/42392984/127724100-3b23a4e8-27fd-40d4-8f5b-9a8079bafb34.png)

**Comment by ianhbell** [comment]
Interesting! This is not documented anywhere that I can find. I'll add a line of docs to DSAT argument.

**Comment by ianhbell** [comment]
Now: ``DSAT``: Return the saturation properties for the input density. Returns saturated vapor, saturated liquid, or liquid for melting curve, depending on density.

**Comment by EricLemmon** [comment]
Add that it will also return the sublimation density.

**Comment by ianhbell** [comment]
Now: ``DSAT``: Return the saturation properties for the input density. Returns saturated vapor, saturated liquid, vapor for sublimation curve, or liquid for melting curve, depending on density.

**Comment by ianhbell** [comment]
Following on, the quality returned here in the case of DSAT with 1201 kg/m^3 should be 999 (because T > Tc and p > pc), not 0

**Comment by EricLemmon** [comment]
This is fixed now.  For those reading this thread and are curious about how Refprop determines the phase, see the text below taken directly from the code.  The modification I just made (and which I should have done earlier!) to the DSAT segment to output the correct value of q now calls the subroutine that contains the code below as is done with all other Refprop routines.

```
c  Calculate q based on T, P, and D.
      if (ABS(q).lt.100.) then
         !2-phase or single phase near saturation conditions.
      elseif (P.ge.Pc .and. T.ge.Tc) then
        q=999                        !Quality undefined
      elseif (P.ge.Pc) then
        q=-998                       !Subcooled
      elseif (T.ge.Tc) then
        q=998                        !Superheated
      elseif (D.ge.Dc) then
        q=-998                       !Subcooled
      elseif (D.le.Dc) then
        q=998                        !Superheated
      else
        q=999
      endif
```

**Comment by glinskyc** [comment]
Is there a reason quality is not consistently returned as -9999990 for invalid cases, e.g. negative density for DSAT?  By using 999 for both the supercritical and undefined/invalid cases, the user must check the error code to know if the result for quality is invalid (or use some other method of checking).

**Comment by ianhbell** [comment]
Well, you should be checking the ``ierr`` anyhow, so I think it is ok that an undefined value is returned.

**Comment by EricLemmon** [comment]
It's mostly for historical reasons, but as Ian pointed out, the error number should always be the first thing checked.  If it is greater than zero, then the value of q really doesn't matter.
