### ISSUE TITLE
Heat of Vaporization - inconsistent result

### ISSUE THREAD

**Issue by glinskyc** [usnistgov/REFPROP-issues#440]
### Description

For the Heat of Vaporization, the desktop app is computing incorrect values when certain _Special_ properties are also included in the table for saturation points. Other tables may also be affected, but I have not tested.

For example, the image below shows when including the _Special_ properties in the table, the result for Heat of Vaporization is zero. I don't know all the situations / properties in which this issue will arise, but I know that multiple _Special_ properties cause this.  I have not identified exactly which _Special_ properties cause this.

### Steps to Reproduce

1. Click on Options > Properties to set the appropriate properties (see image below for example)
2. Click on Calculate > Saturation Points (at equilibrium)
3. Enter a temperature of 100K (as shown in example image)

**Expected behavior:** The value for Heat of Vaporization should always be the same regardless of which properties are included in the table.

**Actual behavior:** The value of Heat of Vaporization is zero when including certain _Special_ properties in the table.

### Versions

**REFPROP Version:** 10.0.0.02
**Operating System and Version:** Windows 10 Pro
**Access Method:** Desktop app

### Additional Information

![image](https://user-images.githubusercontent.com/13897176/129934088-676b1084-88b5-4d74-bfb0-8863571f26cb.png)

**Comment by EricLemmon** [comment]
This happened because of an unusual circumstance where an error number did not get reset after making calls to either the throat mass flux routine or the critical flow factor routine.  Since heat of vaporization would generally not be used with those two properties, this error would never occur.  Simply selecting all properties on that "Special" tab would activate the path required for this to happen.  It's fixed now, if you want a new EXE, please contact Ian Bell (Ian.Bell@nist.gov).
