### ISSUE TITLE
Fugacity - saved table headings

### ISSUE THREAD

**Issue by glinskyc** [usnistgov/REFPROP-issues#441]
### Description

When including the Fugacity property in a table (saturation points in the example here), the exported table headings are not structured as expected.

### Steps to Reproduce

1. Set predefined Air as the substance
2. Set _Temperature_ and _Fugacity_ properties to be displayed
3. Click on Calculate > Saturation points (at equilibrium)
4. Set temperature to 100K in table cell
5. Save the table (File > Save Tables)
6. Review saved table file for issue

**Expected behavior:** The table headings should be consistent, with each row displaying specific data, e.g. phase, property name, units, etc.

**Actual behavior:** The _Fugacity_ heading is included in the top row, which is normally the row that defines phase, e.g. liquid, vapor, or bulk.  The Fugacity units (MPa in this case) is included in the second row, which is normally the row that defines the property name.  Lastly, the mixture component, e.g. Nitrogen, is included in the third row, which is normally the row that defines the units.

This issue seems to arise due to there not being a row designated for _component_ of the mixture, e.g. Nitrogen.  Instead, mixture component is being displayed on the units row, thus pushing all the headings up a row.  This can actually be observed with other properties, such as _Composition_, which corrects for the issue by excluding a heading for units (but I'm suggesting it should still display a units label, even when unitless, to achieve consistency in data structure).

### Versions

**REFPROP Version:** 10.0.0.02
**Operating System and Version:** Windows 10 Pro
**Access Method:** Desktop app

### Additional Information

Exported table file:
```
25: Air (dry): Saturation points (at equilibrium) (75.57/1.2691/23.16)

Liquid Phase Vapor Phase  Fugacity     Fugacity     Fugacity
Temperature  Temperature  (MPa)        (MPa)        (MPa)
(K)          (K)          (Nitrogen)   (Argon)      (Oxygen)
100.00       100.00       0.51654      0.0032102    0.056507
```

**Comment by EricLemmon** [comment]
This is an interesting situation, but I'm not sure that I would call it a bug.   As far as I can tell, fugacity is the only property in Refprop that has both a unit and requires a component name, but does not require a phase identifier.  All others can be set up to put the fluid name in the units spot when needed because they have no unit (sort of, composition is really mol/mol (misleading and confusing), but that isn't really correct either since it's supposed to be "mole of pure component/total number of moles in mixture", but that doesn't fit.)  Those that don't need a phase identifier also don't need the fluid name, and are thus of no concern.

To keep the headers at three lines only, I must have purposefully moved this one problematic property up (decades ago) so that everything still fit within three lines.  I have never had anyone complain about this before and had even forgotten that the issue exists.

Changing the code to fix this is a serious amount of work that could easily introduce many new errors.  Now is not the time to invest the work needed to fix it for a few reasons that I won't discuss, but I have added the "feature request" label so that we can find it later when we go back to either fix problems or make requested updates that are not currently under consideration.

**Comment by glinskyc** [comment]
Other properties that lead to inconsistencies with the table headings:

- Fugacity Coef.
- K value
- Composition

As I mention before:  _"This issue seems to arise due to there not being a row designated for **component** of the mixture..."_

The reason it has come up as an issue is due to my attempts to use exported tables programmatically, in which I also need to make use of the table headings.  Due to the inconsistencies pointed out here, these properties (columns in the table) would need to be treated with special conditions to correctly parse the headings.

**Comment by EricLemmon** [comment]
At this point in time, I think adding the special conditions to your code for parsing the headings is the only way to go, and I apologize for not being able to fix it to avoid these problems.  You've probably already done this anyway with the need to complete the work you are doing.
