### ISSUE TITLE
D0 is not returned properly

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/REFPROP-issues#443]
The ideal-gas density is not returned properly from ``REFPROPdll``.  The input of 'D0' is accepted as an input (at least no output error about the term is returned), but the value is incorrect

``` python
"""Script to demonstrate issue with calculating ideal gas density for a saturated point.

Issue reported on:
    SYSTEM: linux
    REFPROP: 10.0.0.95d
"""

import os
import sys
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RPPREFIX = os.getenv("RPPREFIX")
RP = REFPROPFunctionLibrary(RPPREFIX)
RP.SETPATHdll(RPPREFIX)

print("SYSTEM", sys.platform)
print("REFPROP", RP.REFPROPdll("", "", "DLL#", 0, 0, 0, 0, 0, [1.0]).hUnits)
print("")

# inputs
fluid = "NITROGEN"
temperature = 100
i_units = RP.GETENUMdll(1, "SI").iEnum

# set fluid
err_code = RP.SETFLUIDSdll(fluid)
if err_code >= 100:
    raise ValueError("Error setting fluid")

# compute saturation data
result = RP.REFPROPdll("", "TQ", "D0", i_units, 0, 0, temperature, 0, [1])

# validate per desktop results, v10.0.0.02
print("OUTPUT", result.Output[0])  # desktop = 26.222
print("I_ERR", result.ierr)
print("H_ERR", result.herr)
```

yields
```
SYSTEM win32
REFPROP 10.0.0.02

OUTPUT -9999990.0
I_ERR 0
H_ERR 
```

**Comment by EricLemmon** [comment]
The code shows that the line for this calculation has been commented out, and thus not available as you discovered.  However, I believe there is a good reason for that.  Since temperature and density are independent variables to the equation of state, returning the ideal gas density when the real gas density is given may not be wise.  From the ideal gas law, P = D * R * T, if P (actually P0) is the ideal gas pressure, then T and D are just the conditions of the gas, being ideal or real.  From this, all other properties would be based on T and D.  But if one were to calculate D0 from T and P (not P0), with P being just the condition of the gas, and then use D0 to obtain all other properties, those properties would not be the same as done in the first case.  To make matters worse, if pressure and density are inputs, that would imply that the calculated temperature would be an ideal value.  And even more perplexing, if H and S are inputs, which set should be calculated, (P0 and D) or (P and D0)?  (...or T0 and...)

I have removed "D0" as a possible output to the REFPROP subroutine.  Error 811 will now be returned stating that the input string is not recognized.

**Comment by ianhbell** [comment]
I'm with you.  Please ensure the same behavior is enforced in the GUI.

**Comment by EricLemmon** [comment]
Done!
