### ISSUE TITLE
Dielectric constant (DE) is missing error code

### ISSUE THREAD

**Issue by glinskyc** [usnistgov/REFPROP-issues#444]
The dielectric constant is not returning an error code and error message properly from `REFPROPdll`.

```
"""Script to demonstrate issue with calculating dielectric constant for a pseudo-pure fluid.

Issue reported on:
    SYSTEM: linux
    REFPROP: 10.0.0.95d
"""

import os
import sys
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RPPREFIX = os.getenv("RPPREFIX")
RP = REFPROPFunctionLibrary(RPPREFIX)
RP.SETPATHdll(RPPREFIX)

print("SYSTEM", sys.platform)
print("REFPROP", RP.REFPROPdll("", "", "DLL#", 0, 0, 0, 0, 0, [1.0]).hUnits)
print("")

# inputs
fluid = "AIR.PPF"
temperature = 100
i_units = RP.GETENUMdll(1, "SI").iEnum

# set fluid
err_code = RP.SETFLUIDSdll(fluid)
if err_code >= 100:
    raise ValueError("Error setting fluid")

# compute saturation data
result = RP.REFPROPdll("", "TQ", "DE", i_units, 0, 0, temperature, 0, [1])

# validate per desktop results, v10.0.0.02
print("OUTPUT", result.Output[0])  # desktop = Not calculated
print("I_ERR", result.ierr)
print("H_ERR", result.herr)
```

yields

```
SYSTEM linux
REFPROP 10.0.0.95d

OUTPUT -9999990.0
I_ERR 0
H_ERR 
```

**Comment by ianhbell** [comment]
To be clear, the issue here is that an error code should be returned if the property is invalid for the given fluid.

**Comment by EricLemmon** [comment]
I was a bit surprised to learn why an error message is not being returned.  Back in 1998 I was a young engineer just beginning my career at NIST and added that routine to version 6.0.  I unfortunately did not include the error number or message in the list of outputs.  It's a bit odd that it took 23 years before anyone noticed!

Since the routine name, inputs, and outputs cannot be changed at this point in time, I added a new routine and changed the old one to call it.  The old routine was labeled as:

     subroutine DIELEC (T,D,z,de)

The new one is similar:

      subroutine DIELCNST (T,D,z,de,ierr,herr)

No change will occur when calling the old routine in order to not break active code.  Moving forward, the new routine should always be used.  Error 501 will be returned when no equation is available, for both pure fluids and mixtures.

**Comment by ianhbell** [comment]
What are the values of ``ierr`` and ``herr`` now when you make the call to ``REFPROP`` given in the original post?

**Comment by EricLemmon** [comment]
It's the same as with all the ancillaries:

       [DIELCNST error 501] Equation not available.

**Comment by ianhbell** [comment]
Excellent, thanks for the confirmation.
