### ISSUE TITLE
Question for the ethylene glycol + water mixture

### ISSUE THREAD

**Issue by yoong0316** [usnistgov/REFPROP-issues#47]
Description :
I tried to get properties for the coolant (ethylene glycol + water mixture) which has been newly added in REFPROP 10.0. I can get density and heating capacity of the mixture. but for the properties like thermal conductivity and dynamic viscosity, i got 'Not calculated' msg instead of the values. Are there any physical reasons that the properties cannot be computed? Can you recommend any text to explain the background knowledge about that? Thank you very much

Steps to Reproduce :
I defined 'new mixture', and use the 'specified state points' 

Expected behavior :
Properties of the cooalnt

Actual behavior:
I get error msg, 'Not calculated'

Versions
REFPROP Version: 10
Operating System and Version: Windows 10
Access Method: refprop software

Additional Information
-

Thank you in advance

**Comment by ianhbell** [comment]
Yup, that is because there is no model available for these properties yet for this mixture.  Transport properties of mixtures are hard, and for mixtures with water, especially so.  For now, I will leave this as a feature request and direct this question to our transport property expert.

________________________________

**Comment by jeffkshaw** [comment]
Just to add my name to this feature request, I would like to be able to calculate densities of different mixtures of glycol and water at different temperatures.  Thank you.
