### ISSUE TITLE
Refrigerant R407C_MIX

### ISSUE THREAD

**Issue by HenryRudolph** [usnistgov/REFPROP-issues#475]
Hi Eric and Ian Bell,
i think I have found a mistake in the ASHRAE Diagram for R-407C.
I have programmed in Visual Basic-6 my own diagram and used the latest Update REFRION *.DLL Files.
The "ENTHROPY" Lines are designated for sample with the values 1.80 / 1.90 / 2.00 / 2.10
With **-20 oC** at Saturated vapor I can calculate **1.90** instead to the ASHRAE Value 1.80 aso.
I send enclosed my diagramm and a calculation for a refrigaration cycle.
I think you can confirm my message.
greetings from Austria
Henry
[R407C_00.pdf](https://github.com/usnistgov/REFPROP-issues/files/7411463/R407C_00.pdf)
[R407C_01.pdf](https://github.com/usnistgov/REFPROP-issues/files/7411465/R407C_01.pdf)

**Comment by ianhbell** [comment]
Note: In English, the spelling is Entropy rather than Enthropy

What version of REFPROP do you use? How did you set the reference state?

**Comment by HenryRudolph** [comment]
Hi ianhbell,
I have set the following:
O = 1000#
'iU = 3
'iMass = 1
and I use the following
REFPROP.DLL    28.09.2021
REFPRP64.DLL   28.092021 
DoIhave a mistake insettings,
please help me with the "reference state ?" setting, what must I check ?
Thank you

**Comment by ianhbell** [comment]
You can obtain the version of REFPROP from the ``RPVersion`` function, or with the ``DLL#`` input to REFPROPdll function: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/REFPROPdll

I ask because we have some bugs in setting reference states introduced since version 10.0.  Normally you would do something like this: https://github.com/usnistgov/REFPROP-tests/blob/0b82749ff5645a638832bd423d65b8b843ffbbfc/src/XLS.cpp#L65

**Comment by HenryRudolph** [comment]
Should I send my VisualBasic-6 Source Code for my Subroutines regarding diagram drawing program and singele point calculation. I also can send the diagram for R134a.Mix which is absolut similar to the ASHRAE Diagram.
I work with WINDOWS 7-32 and still with VisualBasic -6 (not with VisualBasic-NET)

**Comment by ianhbell** [comment]
When you make a bug report, we need a small, concise example that demonstrates the problem.  Pages of code in the example will mean that we will need longer to understand what is going on and we may never get around to it.  We made the issue template for exactly this purpose because it shows what information we need and how it should be presented. Here is a decent example: https://github.com/usnistgov/REFPROP-issues/issues/445
