### ISSUE TITLE
Determining Solubility of Gases in an Insulating Liquid

### ISSUE THREAD

**Issue by cnsvert** [usnistgov/REFPROP-issues#489]
### Description

I am attempting to find the solubility of "Non Condensable" gases into insulating liquids.   Specifically to determine what the solubility of Dry Air will be into Novec-649 for a temperature of 75F and 120 F and total pressure of 14.7 psia.  Novec 649 is in the Refprop database.

### Steps to Reproduce

1. See attached State Point properties attempt....when I enter the Composition, is this the overall composition of the whole system?   Vapor plus Liquid?    If  I have an open drum of Novec 649 exposed to the dry air in a room, how do I define the overall composition?
2. [Second Step]
3. [and so on...]

### Versions

**REFPROP Version:**DLL version 10.0
**Operating System and Version:** Windows 10

### Additional Information

If possible, please post examples and/or screenshots of the issue.
![RefpropNovec649O2N2](https://user-images.githubusercontent.com/95445393/144507111-9f9b53ee-d719-4017-8b04-ed7d17a3bcb4.JPG)

**Comment by ianhbell** [comment]
I think you still need to specify the concentration of "air" in the vapor phase (probably you would want to consider nitrogen+Novec649). Then you do a dewpoint calculation. Though to me this has always been a bit mysterious anyhow.  @EricLemmon do you have any idea?

In any case, you need to specify another concentration somehow. Your problem is under-specified as stated.

**Comment by cnsvert** [comment]
It would be great if I could use Refprop for doing this.   I use other software including EES and FlowNex that interface with Refprop, and I could call Refprop from those applications.

I do have one solubility data point  from a Spec sheet of 54 cm^3/100 ml at 25 C for reference.

**Comment by ianhbell** [comment]
Solubility of what? Nitrogen in Novec-649? That's at one atmosphere?

P.S. Make sure you reply in the web interface

**Comment by cnsvert** [comment]
Solubility of Dry Air in Novec-649 as a function of Pressure and Temperature...  Pressure from~10 psia to 30 psia and temperature in the range of 40 F to 130 F.     The solubility data point is for Dry Air / FC3284 at 25C and 1 atmosphere.   FC3284 and Novec-649 are very similar from a thermodynamic standpoint per 3M.

**Comment by ianhbell** [comment]
"Air" is not something that can have solubility. Can you share the link to the data sheet?

**Comment by cnsvert** [comment]
Trying to attach the spec sheet with solubility.
[Boeing_Distribution_3M_Fluorinert_Liquids_Flyer.pdf](https://github.com/usnistgov/REFPROP-issues/files/7650617/Boeing_Distribution_3M_Fluorinert_Liquids_Flyer.pdf)

See the table on the final page.


I see this as similar to the solubility of CO2 into water for soft drinks etc.

**Comment by cnsvert** [comment]
Here is another properties Sheet from 3m, but it does not have solubility in this.

[3M Fluorinert Electronic Liquid FC-3284 TDS_FINAL.pdf](https://github.com/usnistgov/REFPROP-issues/files/7650658/3M.Fluorinert.Electronic.Liquid.FC-3284.TDS_FINAL.pdf)

**Comment by ianhbell** [comment]
My paper gets at the numerics of the problem: https://doi.org/10.1016/j.ijrefrig.2017.10.001

**Comment by cnsvert** [comment]
Thanks Ian ,    That is beyond my level of comprehension....I did take PChem, but that was 40 years ago.      Do you think Refprop can provide the answer to a question like.....if I have a open drum of Novec 649 exposed to the atmosphere at 60 F 50%RH , what are the equilibrium molar concentrations of O2, N2 and H2O in the liquid?

**Comment by ianhbell** [comment]
We should be able to answer a question like this: what is the molar composition at the bubble-point for a binary mixture of NOVEC649 and nitrogen at 25 C at one atmosphere.  My colleague reminded me that you want to make sure you use the most updated interaction parameters in REFPROP 10.  

My attempt to try to solve for nitrogen solubility in NOVEC649 is below. The point is that you need to solve for the amount of nitrogen in the liquid phase of a mixture to yield the atmospheric temperature (let's say of 25 C).  The results below suggest the nitrogen solubility predicted in REFPROP is approximately 0.0023 mole fraction of nitrogen. 

```python
import os
import pandas
import numpy as np
import matplotlib.pyplot as plt

# Import the main class from the Python library
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
print(RP.RPVersion())

for z0 in np.geomspace(1e-4, 1e-2):
    r = RP.REFPROPdll('NITROGEN*NOVEC649','PQ','T', RP.MASS_BASE_SI, 0, 1, 101325, 0, [z0, 1-z0])
    if r.ierr == 0:
        print(z0, r.Output[0]-273.15, '°C')
print(RP.GETKTVdll(1,2))
```
yielding
```
10.0.1.19
0.0001 48.372126453891724 °C
0.00010985411419875583 48.30463049165331 °C
0.00012067926406393288 48.23028623376564 °C
0.00013257113655901095 48.148376872978986 °C
0.00014563484775012445 48.05810588449674 °C
0.00015998587196060574 47.95858715354552 °C
0.00017575106248547912 47.848833665037375 °C
0.00019306977288832496 47.727744499235826 °C
0.00021209508879201905 47.59408982312323 °C
0.00023299518105153718 47.446493497935876 °C
0.0002559547922699536 47.28341283403381 °C
0.0002811768697974231 47.10311491471458 °C
0.00030888435964774815 46.903648763573756 °C
0.000339322177189533 46.6828124475291 °C
0.0003727593720314938 46.43811395683207 °C
0.0004094915062380423 46.16672438785707 °C
0.0004498432668969444 45.86542151532058 °C
0.0004941713361323833 45.53052126055309 °C
0.0005428675439323859 45.15779375970601 °C
0.0005963623316594642 44.74235962336405 °C
0.0006551285568595509 44.27856040916947 °C
0.0007196856730011522 43.75979507496601 °C
0.0007906043210907702 43.17831088799909 °C
0.000868511373751352 42.524932344955175 °C
0.0009540954763499944 41.78870415422102 °C
0.0010481131341546852 40.95641255159643 °C
0.0011513953993264468 40.01193021810593 °C
0.0012648552168552957 38.93529832771014 °C
0.0013894954943731374 37.7014041497477 °C
0.0015264179671752333 36.2780125477214 °C
0.0016768329368110067 34.622717911790176 °C
0.0018420699693267163 32.677991107765536 °C
0.0020235896477251557 30.362629217602603 °C
0.0022229964825261957 27.555797388118663 °C
0.0024420530945486497 24.063943599587162 °C
0.0026826957952797246 19.541027460541898 °C
0.0029470517025518097 13.24353047883858 °C
0.0032374575428176433 2.7957035180089633 °C
0.0035564803062231283 169.14166764534275 °C
0.003906939937054613 169.16070108870207 °C
0.004291934260128779 169.18125243213302 °C
0.00471486636345739 169.2034175701748 °C
0.005179474679231213 169.22729612641325 °C
0.005689866029018293 169.25299191965945 °C
0.0062505519252739694 169.28061375202213 °C
0.006866488450042998 169.31027663810642 °C
0.007543120063354615 169.3421036319864 °C
0.008286427728546842 169.39048429966329 °C
0.009102981779915217 169.42718347734296 °C
0.01 169.46653383773236 °C
GETKTVdlloutput(hmodij='XR0', fij=array('d', [0.94032, 1.6186, 1.0, 1.0, 0.0, 0.0]), hFmix='HMX.BNC', hfij='BetaT   GammaT  BetaV   GammaV not usednot used', hbinp='Nitrogen/Novec649\r\nI.H. Bell, NIST (2020) unpublished MARE: 5.34% from 20 bubble-point pressures', hmxrul='XR0  Reducing functions only')
```

**Comment by nist-aharvey** [comment]
If I may chime in, it is common to talk about the solubility of "air" at a given condition as the sum of the solubilities of N2, O2, etc. in a fluid when exposed to air.

I think the easiest way to get the equilibrium solubility of air would be to create a mixture that was half solvent and half the composition of air.  Be sure you work in molar units.  Dry air is .7812 mole fraction N2, .0092 argon, .2096 O2.  So you could divide all these by 2 and add the solvent at 0.5 mole fraction.  You could add an appropriate amount of water and renormalize if you wanted to consider humid air (although REFPROP is not optimized at all for H2O/Novec mixtures so I would not particularly trust that part of the answer).
Then you can simply do a vapor-liquid flash calculation at your P,T of interest, and the equilibrium liquid phase will give you the information you need for the solubility.  You will have some work to do for the units if you want to check against that product sheet, The "54 cm3" dissolved in 100 ml of solvent must refer to the volume of air at 25 degC and 1 atm, so you could do a separate calculation to figure out how many moles that corresponds to, and another calculation to find out how many moles of the solvent corresponds to 100 ml.

IMPORTANT: As far as I know, no mixture optimization has been performed in REFPROP for these gases with this solvent.  This means that, while the solubilities will probably be qualitatively correct, they could easily be off by a factor of 2 or something.  So you should check against the one data point you have.  If you trust that data point, then you can use that to rescale the result from REFPROP -- so for example if REFPROP gives you 27 cm3/100 ml instead of 54 at that condition, you could multiply all REFPROP solubilities by 2 to get a better estimate (the trends with T and P from REFPROP should be roughly correct even if the absolute solubility is off).

I just tried that calculation, and see one thing that makes me question what you are trying to calculate.  The vapor pressure of Novec 649 is pretty high at 75 F and especially 120 F.  So if you have an open drum in a room full of air, the "equilibrium" will have much (maybe all) of what is in the drum evaporating (how much would depend on the relative sizes of the drum and the room).  So in that sense your question is not well-specified.
I would also note that, if the drum of liquid is not stirred or anything, it could take a LONG time for the air to reach its equilibrium solubility throughout the drum.  At that point you have a mass transfer problem that is outside the realm of thermodynamics.  Similarly it could take a long time for the Novec to evaporate to reach equilibrium in the vapor phase, depending on non-thermodynamic factors like the air flow in the room.

**Comment by ianhbell** [comment]
Thanks @nist-aharvey for the comprehensive answer. I should comment that the internal report from Huber includes parameters for NOVEC649+N2: https://nvlpubs.nist.gov/nistpubs/TechnicalNotes/NIST.TN.2132.pdf

**Comment by cnsvert** [comment]
Thanks Allen and  Ian,   I will digest this over the weekend.  This is an important question for liquid cooling of servers at the current time.

**Comment by cnsvert** [comment]
![FC3284 Shipping Drum](https://user-images.githubusercontent.com/95445393/144924544-fdb08713-6084-458d-aaf7-736ece366c30.jpg)

See this picture of the Drum that the FC3284 (simialar to Novec 649 ) is shipping in.   The sealing cap is fairly light construction plastic.   This leads me to believe that the drum is not expected to go into a hard vacuum or much positive pressure is reasonable shipping /storage temps.     say 40 F to 120 F.      The vapor pressure of FC3284 at room temperature is 5 psia.  So the air partial pressure may be ~ 10 psia at 75F.   Does this help to provide a state point that the total composition can be determined from?   The drum has 12 Kg of FC3284 in it.

**Comment by nist-aharvey** [comment]
The calculation I described previously (maybe using nitrogen as a proxy for "air" since REFPROP has optimized parameters for that binary) should give you the equilibrium composition.  As long as the total amounts that you give it yields a 2-phase condition (you might have to put more or less Novec into the initial composition if you get an answer that is all vapor or all liquid), the liquid phase in equilibrium will be the equilibrium solubility at that T and total P.
You should check that answer against the one data point you have (as I mentioned, careful attention to units is required), but since some parameters have been fitted to the N2/Novec binary I would expect it to be in the ballpark (maybe within a factor of 2).

BUT, what REFPROP can't tell you, because it isn't a thermodynamic question, is whether getting all the liquid in the container to that equilibrium concentration when it is open to the air will take 5 minutes or 500 years.  So if you need to get an idea of how close it will get to that saturation concentration after a given amount of time, you'll need to find other expertise.
If the liquid is still, you will start getting near-saturated liquid near the opening once you expose it to air, with the air gradually diffusing into the liquid and the far corners getting effectively to saturation some time later.  But we have no expertise to guess how fast that diffusive process is.
And, further complicating things, simultaneously you will have liquid evaporating into the air after you open the container, which is also a process whose rate is outside the realm of thermodynamics.
My guess is that, if the vapor pressure is 5 psia, the evaporation of the liquid would be faster than the diffusion of air into the liquid (at least if the room has any ventilation).  But that's just a guess and you shouldn't base anything important on it.
