### ISSUE TITLE
Graph of how water vapor content in a defined gas stream varies with pressure and temperature

### ISSUE THREAD

**Issue by EcoVaporRS** [usnistgov/REFPROP-issues#496]
### Description

This isn't an issue per-se, but a request for help in how to accomplish this. I'm trying to model how water vapor content varies within a gas stream based off of a pressure and temperature (basically a multiphase diagram for a composition of a gas that can be defined). The intent is that if I know the existing water amount, pressure and temp, then I would like to know how much of that water is liquid, how much is gas, and if I lower the temp, how much water can I expect to produce

### Steps to Reproduce

1. Define gas mixture (in this case: CO2: .01999, CH4: .95596, N2: .0199, O2: .000039998, H2O: .0039998 (normalize to 1)
2. Plot >> Other diagrams >> change to match what I have in the screenshot
3. Adjust Plot zoom window as necessary for better resolution
4. Take the sample pressure steps offered (40 to 150 psig and 40 to 200 F) and enter into Calculate >> Specified State Points

**Expected behavior:** I was hoping to be able to clearly identify that for a given pressure, I need "XYZ" temperature to reduce the water vapor concentration to "ABC" amount. I normally work with lb/MMSCFD, but that's not the end of the world to change from some other meaningful concentration (ppm, lb/ft^3, etc.)

**Actual behavior:** I have a graph, but I'm not entirely sure it displays what I'm after. Could use a little interpretation guidance if this does what I believe it might. Otherwise, from PennWell publication, I'm looking for something that could somewhat mimic this, but for any gas that can be modeled within REFPROP.

### Versions

**REFPROP Version:** REFPROP DLL version 10, NIST Standard Reference Database 23
**Operating System and Version:** Windows 10 Home, version 21H2, OS build 19044.1415
**Access Method:** Through REFPROP 

### Additional Information

If possible, please post examples and/or screenshots of the issue.
[Water Content Chart.pdf](https://github.com/usnistgov/REFPROP-issues/files/7804556/Water.Content.Chart.pdf)
<img width="1240" alt="water vapor" src="https://user-images.githubusercontent.com/97067881/147992383-ebabfc7f-98ad-48fd-aa03-7a667f1e3b48.png">

**Comment by nist-aharvey** [comment]
A side issue related to your question is that you should be aware that the mixture models in REFPROP are not well optimized for vapor-liquid equilibria of water-gas systems.
So before you put too much faith in any results, you should check against real data for the water-methane system (since your gas is mostly methane), like the data in this paper:
https://pubs.acs.org/doi/10.1021/j100847a064
I think you are at low enough pressure that the vapor-phase water content should be reasonably accurate (because the nonideality won't be very large), but I'm not sure about that.

**Comment by EcoVaporRS** [comment]
Understood, so I need to test it. Are you aware of other programs that might do what I'm looking at a bit more effectively?

**Comment by nist-aharvey** [comment]
Commercial process simulation software (we government people can't recommend or mention brands) could probably do a decent job with such calculations, although it would still be a good idea to check against real data.

In terms of the actual calculation (leaving aside the question of accuracy), I think it should be pretty easy with REFPROP.  It would just be the following steps:
1) Define mixture.
1a) Put in dry gas composition
1b) Put in enough water that you get a vapor and a liquid phase at your T and P (an equal amount of moles to the gas should do it, I think).  Normalize.
2) Do Specified State Points at your T and P of interest.
3) Make sure it is two-phase, and then the fraction of water in the equilibrium vapor phase (you may have to work out unit conversions if you want units like pounds of water per some amount of gas) is the saturated amount of water at that T and P.

If you want to go in the other direction, what temperature do you need in order to reduce the water in the gas to a certain amount, the steps would be:
1) Entered desired gas-phase composition, including the water amount. Again you may have to work out unit conversions (make sure you pay attention to whether you are working in molar or mass units).
2) Go into Properties and turn on display of Composition so you can be sure you are doing the right calculation.
3) Do Calculate, Saturation Points at equilibrium
4) Enter your pressure in the Vapor Phase Pressure column
5) **IF** the calculation converges (sometimes REFPROP has problems with such highly asymmetric mixtures), it will give you the dew-point temperature at that pressure and vapor composition, which is what you want.  The Vapor Composition should be what you originally entered (Liquid Composition will show a little gas dissolved in liquid water, which I gather you don't care about).

Any chart drawing for this calculation you would probably have to do yourself, but this should generate the numbers you need for such a chart without too much trouble.

**Comment by EcoVaporRS** [comment]
I started the steps for what temp do I need to gain a resultant ppm in water concentration and I have an interesting error. My first thought is that I should be able to assume that an in-process separator mist pad should remove enough free water to get me below 5%, but... does it? Not entirely sure. Does said mist pad typically remove free "large" water droplets? Yes. Can I quantify it with data to better calibrate this... no. Needless to say, I'm a bit stuck, other than trying a different gas composition I suppose. Otherwise, yes, you're correct, a small amount of gas dissolved in liquid water is irrelevant to the process. Thoughts?

<img width="616" alt="Water vapor error" src="https://user-images.githubusercontent.com/97067881/148172700-cc946ce4-2764-4d84-9c14-85fa15eeb63e.png">

**Comment by ianhbell** [comment]
Turn off transport properties and this error will go away.

**Comment by nist-aharvey** [comment]
That error suggests that you are asking it to calculate transport properties (like viscosity or thermal conductivity).  Go into Properties and uncheck those boxes and you shouldn't have the error anymore, and can do the thermodynamic calculation.

**Comment by EcoVaporRS** [comment]
Thank you both! I might have the wrong thing checked under thermodynamic properties, as I don't see one for a dew point column. However, I believe that the vapor phase density is effectively trying to tell me the dew point. I'm not sure what I should take as the lbm/ft^3 for "dry" gas (7 lb/MMSCFD), my knee-jerk is 7*10^-6 lb/SCF, but effectively this appears that the gas simply can't get dry (I even ran this down to 0 F and I got a vapor phase density of .018870). Perhaps either I'm misinterpreting REFPROP or perhaps this is one of those "highly asymmetric" mixtures you mentioned earlier in this post? Perhaps I could compare the vapor phase density at a specific temperature without water and compare that to this iteration with water, and the difference is the total weight of water I can remove (and then convert to lb/MMSCFD). Thoughts?

<img width="1280" alt="Vater vapor looking for dew point" src="https://user-images.githubusercontent.com/97067881/148250567-a03eb6b6-1169-4b46-94c6-da13c652c033.png">

**Comment by nist-aharvey** [comment]
First, it would be easier if you turned off all the extra properties that are irrelevant to the calculation you are trying to do, like Cp, Cp/Cv, molar mass, Compressibility factor, critical flow factor (and everything under the "Transport, Misc." tab).  Actually for your purpose you don't even need enthalpy or entropy.  But be sure you turn on Composition under the Mixture tab.
There is no "Dew Point" column -- if you ask for a "Saturation points at equilibrium" calculation, and enter your pressure into the "Vapor phase pressure" column, the temperature of the resulting calculated point will be the dew-point temperature at that pressure and your defined composition.  
You don't need to work with the density to do that calculation; you just need to be able to input your desired final composition in sensible units (we are not in a position to debug any conversions you might have to do from non-standard units like lb/MMSCF).  That would be the number of moles (or mass) of each of the gas components and of water.

**Comment by EcoVaporRS** [comment]
Ok, you're right, removing all the extra garbage makes it easier to see. Thanks! Just so I can work through an example: I'm taking 1.5 MMSCFD at 85 psig of vapor pressure, which yields a dew point of 71.5 F. However as you begin to drop water out, the dew point changes, because the gas mixture has now changed. I'm probably missing the trees for the forest, but I'm not sure how to do the last part... the liquid phase mole fraction of water tells us what we'd expect: that the resulting liquid is mostly water, but it doesn't give me something useable like how much of the original water is remaining as a vapor, etc.


<img width="1135" alt="Water vapor dew point sample" src="https://user-images.githubusercontent.com/97067881/148277108-b0c54882-c3e9-4b4e-8ae8-86254d1af7fe.png">
.

**Comment by nist-aharvey** [comment]
The relevant thing that tells you about the water left in the vapor isn't the liquid phase composition; it is the vapor phase mole fraction.  I am still not 100% clear on what you want to do in terms of sequential calculations, so I'll give you 2 workflows and I hope one will fit.

1) If you want to see how the dew-point temperature changes as you drop out water, you could do a series of dew-point calculations with different compositions.  So with a certain amount of water you might have a dew-point temperature of T1 at your given pressure.  Then you could make a new mixture with 90% of the original water amount, do a similar dew-point calculation, and get the dew point temperature T2 of that mixture, etc.

2) Probably an easier way to generate the information because you would not have to keep changing the mixture composition.  Define a mixture with enough water that you know some liquid will drop out.  Then do a series of specified state points: first point at (P,T1), second at (P,T2), etc.  The composition of the vapor in equilibrium at each point will tell you the amount of water in the gas phase corresponding to the dew-point temperature of T1, T2, etc.

By the way, for exploratory calculations until you have figured out exactly what you want to do, I'd strongly suggest working with a simplified system like water and pure methane.  That will save you work entering mixture compositions and will also make a more readable table with fewer columns.

**Comment by EcoVaporRS** [comment]
Sorry, I got tied up for a couple of days. The question I'm trying to answer is what temp do I need to get my gas to to drop out enough water to meet 7 lb/MMSCFD as a dryness specification, typically in ANSI 150# pressures. The only thing that comes to mind is the somewhat onerous iterative process of re-estimating the dew point like option 1 you gave that involves a lot of conversions to units I don't typically use and increases the chance for an error. I think the issue with option #2, is that I probably am just ignorant of a reliable way to define this mixture. An additional question: is it possibly easier to define what full water saturation looks like within REFPROP given a set of P/T and composition conditions? I'll try to play around with the second method this weekend.

**Comment by nist-aharvey** [comment]
The calculation you describe should be easy, once you translate your 7 lb/MMSCFD into less weird units that REFPROP can deal with.  Sounds like that may be the hurdle.  To do that, you figure out how many moles 7 lb of H2O is, and how many moles 1 MMSCF of your gas is, put those into your mixture definition in REFPROP (making sure you are using molar units in the mixture definition), and normalize.  That gives you the mixture composition you need.
Then you can just do a dew-point calculation with that composition, as described in the 2nd part of my post above that starts "Commercial process simulation".  That will give you the temperature (at whatever pressure you input) at which all of the water will have dropped out except for the remaining 7 lb/MMSCF you specified in the saturated vapor.

I'm not sure exactly what you are asking with your additional question, because it is overspecified.  If you fix T and P and composition, it will either be saturated or not, so you can't also specify saturation.  If what you mean is determining what is the saturated vapor composition at a given T and P, that is exactly my calculation #2 above.  Where again you might have some work to translate the composition from REFPROP into these nonstandard units, but maybe you could program that conversion into a spreadsheet so you didn't have to do it every time..

**Comment by EcoVaporRS** [comment]
Ok, I had to pull off this to work on a different project. I cut the columns down, simplified the mixture to just CH4 and H2O and added the Composition box under mixture. The saturation points at equilibrium only lets you either put in a vapor pressure or vapor temp, but this doesn't change the composition like I was hoping to see. However, I'm wondering if I convert the vapor phase density into my preferred units (varying vapor temp only) and compare this to pure methane at the same initial pressure, that I can tease out how much water is supposed to drop out at these explicit temps. In messing with this method, pure methane gives me Cricondentherm errors at the temps I'd be interested in. I wonder what composition is "supposed" to show me that it's currently not (unless this is the liquid phase mole fraction of methane, which isn't a helpful value).

This is me varying the pressure to some random numbers after starting with 130 psig
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/97067881/150239284-6e153d5f-afec-4b16-92e4-871d27e2743b.png">


This is me varying the temp to some random numbers after starting with 130 psig (initial pressure I'm stuck with)
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/97067881/150238949-17fb4a52-60f6-426d-9185-6ec8e958ae03.png">

Going back to specified state points and entering in the pressures and temps I want yields this:

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/97067881/150240065-83142e73-37d7-4baf-b384-85fdbba883c2.png">

I'm not trying to be annoying, but I think I'm missing something to get the #2 commercial. Thoughts? I have T, P, density, volume, phase, critical flow factor and composition checked for display properties.

**Comment by nist-aharvey** [comment]
I think your first 2 pictures actually do what you need to do (at least as you expressed in your next-to-last message).  You asked what temperature you need to drop to (at a given pressure) to drop out enough water to meet a certain dryness specification.
If the composition you created for the mixture corresponds to that specification, then (looking at your first table) these saturation calculations tell you that at 130 psig you need to go to 81.33 degrees F, at 75 psig you would need to drop it to 67.626 degrees F, etc.

The 3rd picture is not telling you anything as given, because it is all gas phase with the conditions and composition you entered and therefore does not tell you the saturation condition.  If you want to know the saturated moisture content at a given T and P, you need to put enough water in the system when specifying the mixture composition to have a vapor and a liquid phase at equilibrium (you can tell from the Phase column if you have a 2-phase condition).  Roughly 50-50 gas/water in terms of moles should give 2 phases at the sort of conditions you are looking at.  If you do that, the vapor-phase mole fractions in a T/P specified state points calculation at your 2-phase conditions will be at saturation, so that will tell you the saturated vapor moisture content at the entered T and P.

A side comment is that "psig" is a dangerous unit to use, because it is not fully thermodynamic but instead is a relative measure of pressure (relative to atmospheric pressure wherever the gauge is located).  REFPROP defaults the basis for gauge pressure to standard sea-level atmospheric pressure (about 14.696 psi), but that will be in error by some amount if you are not at sea level (or having a weather front that gives you unusually low pressure or temperature, though those fluctuations might be small enough to ignore in many contexts).  For example, here in Boulder, CO, the atmospheric pressure is closer to 12 psi, so using the default with gauge pressure would put all pressures in error by 2.5 psi or so.  If the system you are analyzing is at altitude, you would want to go in under Units and change the reference pressure.  But if possible it is better to use absolute pressure, which is unambiguous and will give consistent results regardless of location or weather.

**Comment by EcoVaporRS** [comment]
Ok. I was hoping that option #2 (commercial process simulation) could be done to where I can estimate an amount of moles of water that drop out, and an amount of moles of water that remain in the vapor state based on P/T given. I'm guessing that manually recalculating/iterating this is as close as I'm going to get for that? Part of the issue is that pretty often, I have no idea how much water will fall out naturally, but assuming a saturated vapor stream is technically a stretch also.

No argument that the third picture is true but useless, but noted that reducing the water until the mixture isn't 2-phase exists.

Fair point on the psig vs psia. We ship these all over and have altitudes ranging from 6000' to 100'. I'm aware that there's an error associated with using psig, but for the efforts towards water removal, we'd normally tack on at least a 20% safety factor, because at the end of the day, we committed to a certain water concentration and our customers expect that.

**Comment by nist-aharvey** [comment]
I think you can get the amount of water that drops out at (T,P) without too much trouble.  You need to add the property "Quality".  For a 2-phase system (using molar units), the Quality is defined as the ratio of the number of moles in the vapor to the total number of moles.
So you can start with your initial stream where you know the total amount of everything.  Then you do the calculation at (T,P).  If you are in a 2-phase region, that means some water has dropped out.  Since you have the compositions of both phases, and from the Quality you have the fraction of the moles remaining in the vapor, with a little arithmetic you should be able to calculate how much water has dropped out and how much remains in the vapor.
Probably a good idea to double-check your math by making sure the moles you calculate in the vapor and in the liquid at the end add up to what you started with.

**Comment by EcoVaporRS** [comment]
Unfortunately, quality doesn't change on a molar basis regardless of what P/T I use (that's somewhat realistic for what the system would see). Well... it changes the methane quality, but that doesn't get me any closer to how much water (even on a molar basis) falls out at that specific P/T. The third one was from me clicking around and I chose Specify Saturation Table, vapor at dew point with coexisting liquid, composition at fixed p. So the vapor phase mole fraction of water the first number (.0516) is the estimated water content on a mole fraction basis and then the ending .00333 is the desired output on a mole fraction basis in terms of dryness. I find it difficult to believe the temp is so high based off of interfacing with a lot of vendor proposals to this effect, but let's run with it for now. Why does it leave the temp so high? I'm assuming that's because it's directly predicting the dew point for this simple 2-ph gas while holding the pressure in psig constant? The other options in Saturation tables haven't gotten me this close. Here's the formula I used to get the mol fraction in MMSCF:
https://www.cheresources.com/invision/topic/4541-how-to-convert-mol-fraction-to-lb-watermmscf/
Pic if you can't use the URL: 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/97067881/150588703-94cce749-269e-4f60-a634-a55dbc33ce27.png">

In the process of checking my math, because the temp to hit my "required" mol of water makes no sense against commercial applications.

Saturation points at equilibrium:
<img width="918" alt="image" src="https://user-images.githubusercontent.com/97067881/150585258-25e3fa76-f646-4d55-b096-50139380475b.png">

Specified State Points:
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/97067881/150585695-66f6ceec-6422-44bb-931f-81741bc737c2.png">

Saturation Tables:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/97067881/150587777-59d290b7-cc5b-45b5-8d44-3587935cd840.png">

**Comment by nist-aharvey** [comment]
Well rats, that should have worked.  If the dew point at 130 psig is 82 degF (that result looks right to me), then a T,p calculation at 130 psig and a lower temperature should be a two-phase condition (the quality might be 0.995 or something).
I think you are probably running into some sort of convergence problem -- REFPROP can have a hard time with mixtures where the components have very different volatility.
So you may have to do that calculation in a more roundabout way -- but your 3rd table with dew points at varying composition looks like it solves the problem nicely.  It connects the remaining water content in the vapor to how low you have dropped the temperature at a fixed pressure.  You could repeat the calculation at different pressures.  Those dew-point numbers look right to me. [Whether you have correctly converted to mole fraction from lb/MMSCF units is a different question that I have no time or inclination to delve into -- but you could check it by figuring how many moles of gas are in a SCF (you could use REFPROP for that if you know what "standard" T and p are for whatever definition of SCF you are using) and how many moles of water are in a lb.]

Meanwhile, maybe @ianhbell will have some thoughts on the failure of the mixture (T,p) calculation -- he's the expert on REFPROP mixture VLE calculations.  Ian, I stripped the problem down to something simple: the following Specified State Points with T and p specified, for a methane-water mixture with the molar composition that you see in the mole fraction cells, should produce a 2-phase condition, but it doesn't:
![image](https://user-images.githubusercontent.com/45049145/150602250-934cc8b8-12e0-4feb-af85-6d5e6613d1b6.png)

**Comment by EcoVaporRS** [comment]
Yeah, the 130 psig and 82 F seemed correct. I the third table is more or less what we're both after, now I'm working through making sure I have the math down on mol% since my first answer was off so badly and making sure I can get an approximate lb/MMSCFD and vice-versa in mol% using more than one source. I've been reading for a few hours now, and at STP (60 F, 14.696 psi) 1 mol of gas is ~380 SCF. Understood on @ianhbell being the expert on VLE calcs. I really appreciate your patience and diligence!

**Comment by nist-aharvey** [comment]
I verify from REFPROP that, for pure methane, 1 lb-mol of gas at those conditions is about 379 ft3.  Or if you do things in g-moles, a mole is about 0.820 ft3.

As an aside, I believe that's the STP for the natural gas industry in the U.S., but other industries and/or other parts of the world use different definitions.  I believe in Europe the temperature used is 15 degC (about 59 F).  Some industries in the U.S. use 14.7 psia.  In the past, there were even several different definitions used for STP for natural gas among different states in the U.S. (I seem to recall at least one state used 14.5 psi), but I think they may have finally gotten rid of those variations.
But if you are building 20% margin into your devices, those differences are not of practical importance.

**Comment by EcoVaporRS** [comment]
Wonderful (how do you do that in REFPROP)?

Yeah, we usually just define how we did it, and if they want, we can revisit in their STP.

**Comment by nist-aharvey** [comment]
In REFPROP, choose pure methane as the fluid (or you could define a natural gas), choose Volume as a Property to display, make sure you are in molar units, and choose other appropriate units like ft3, then do Specified State Points at 60 degF and 14.696 psia.  The Volume column will tell you how many cubic feet per mole for the gas at that T and P.  Choose lb/lbmol in Units for mass if you want lb-moles, or g/gmol for g-moles.

**Comment by EcoVaporRS** [comment]
I did pure methane just for simplicity's sake, but not seeing quite what you have going on. Under properties I have T, P, V and Composition selected. Under units for Volume, I changed to molar composition (I'm always in ft3), which gives me a value, but it's wrong (around half the value that's expected). Thoughts?

<img width="754" alt="image" src="https://user-images.githubusercontent.com/97067881/150823791-ba32368f-c9ac-4eb8-8535-9215bfcae378.png">

**Comment by nist-aharvey** [comment]
Standard pressure is 14.696 *PSIA*.  You still have pressure units set to psig.

**Comment by EcoVaporRS** [comment]
Fair, but in the units section I have psia selected and I'm not sure how to change the psig in the top column (right clicking it just brings up a way to change how the units are displayed and the column order). Interestingly enough, if I run at .001 psig, it gives the correct answer, so that's close enough.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/97067881/150828156-331a0818-fa03-4e47-8c9d-55313d275bb8.png">

**Comment by nist-aharvey** [comment]
The way to get psia (or absolute pressures in general) is to uncheck the "Use Gage Pressure" selection in the Pressure part of the window below the unit selections.

**Comment by EcoVaporRS** [comment]
Thanks! That's neat that you can just enter the elevation too. less work my excel sheet needs to do.

**Comment by EcoVaporRS** [comment]
I have a follow-up question. At very low pressures (< 0.5 psig and I'm 259' ASL) I think REFPROP loses some accuracy. My understanding is that (this is based on meteorology) for a gas mixture (in this case somewhere around 90+% nitrogen) the solubility of water vapor should closely mimic air. Balance of gases are ~1.5% O2 and water vapor. However, I don't think it's possible to have roughly 9% water vapor, but I'm not sure how to validate this overall solubility within REFPROP. Currently, I use the method I have already described (Calculate, Saturation Tables, vapor at dew point with coexisting liquid, then vary only the final water content and specify your pressure and how many data points you want, I typically use 20). I am concerned that because the pressures I'm using are only barely positive pressure (i.e. 0.04 psig, 0.12 psig and so on), this will radically change my thermodynamic properties for using heat exchangers, and calculated temperature rise via wonky specific heat numbers that have too much water present, etc.

**Comment by nist-aharvey** [comment]
Quick partial answer is that you are not using "very low pressures" in the context of REFPROP (or of thermodynamics in general).  Thermodynamics (and REFPROP) deals with ABSOLUTE pressures (not gauge pressure).  So REFPROP calculations should be just as good at 0.01 psig (or -0.01 psig) as they are at 1 psig, 5 psig, etc.  Nothing will change radically as you near (or cross) 0 psig.

If you are close to atmospheric pressure, 9% water in the gas phase is realistic if your system is around 45 degrees C (roughly 110 degrees F).
At fairly low absolute pressures like you describe, it is actually easy to estimate the amount of water in the vapor phase at saturation to see if you are getting reasonable answers. Just look up or compute the (absolute) vapor pressure of pure water at your temperature of interest.  Dividing that by the total pressure (ABSOLUTE pressure!) will give you approximately the mole fraction of H2O.  There are small corrections based on the gas composition, but those corrections will be on the order of 1% on a relative basis (in other words, if my simple calculation gives 5% H2O, the rigorous answer might be 5.05% or something).

You are correct that there will not be much difference between H2O solubility in air and in a stream that is mostly nitrogen.  At pressures near atmospheric, the gas phase will be nearly ideal and it won't make much difference what the gas is (so pure O2 or CH4 would also be about the same as pure N2). As the pressure gets higher, you get more gas-phase interactions between H2O molecules and gas molecules so the differences between gases become more important.

**Comment by EcoVaporRS** [comment]
Ha... ok, fair, we basically never deal with vacuum pressures and we rarely use inches of water either. Ok, so using engineering toolbox as a quick and dirty example at 44 C they list a vapor pressure of 1.3216 psi. Because in this problem I want to validate, I'm extremely close to sea level, I'm going to approximate 259' ASL with 14.696 psi. This gives me 16.017 psi divided by 14.816 for 1.085. and that remainder of 0.085*100 = 8.5 is a high-level estimate of how much water I have present at saturated conditions (meaning 8.5% water)? If so, thank you - the high-level answer is sufficient for what I need. I have no idea how I'm going to calculate transport equations in REFPROP for this much water, but I guess that's a problem for another day.

**Comment by nist-aharvey** [comment]
Almost.
Saturating a gas stream with water doesn't pump up the pressure. So if your process is at atmospheric pressure the total pressure will still be 14.696.  So the water content in your example would be 1.3216/14.696, which is 9.0%.  Or if your process is at 0.12 psig you'd have 1.3216/14.816.

If you are just doing vapor-phase calculations, I would expect the models used in REFPROP for viscosity and thermal conductivity to give you reasonable results for mixtures like that. But whether there is some way to bypass REFPROP's guard rails to get it to calculate at those compositions I don't know -- you could search this site and open up a separate inquiry if necessary.
You might need to do something like a mole-fraction weighted average of the pure-component properties, which I expect would get you within 10% or something.  If you do that, be sure to get your "water" values at a vapor state, which will mean a low pressure.  So in your example you might use the viscosity of water vapor at 1 psia and 44 degC.  This works because vapor-phase viscosity and thermal conductivity are nearly independent of pressure at low pressures.
