### ISSUE TITLE
Refrigerants R1336mzz(E) and R1130(E)

### ISSUE THREAD

**Issue by choeges** [usnistgov/REFPROP-issues#509]
### Description
Hello,
I just read a paper (https://doi.org/10.1016/j.enconman.2020.113752) about high temperature heat pumps. The authors use REFPROP to evaluate (among others) the fluids **R1336mzz(E)** and **R514A** (mixture of R1336mzz(Z) and R1130(E) ). In the REFPROP version I use (10 - with the current Beta Version 10.0.0.97), however, the pure fluids R1336mzz(E) and R1130(E) are not included.

Did you develop new substance models for the mentioned pure fluids and updated the REFPROP installer? 
In case these substance models are within the developing phase still, is it possible to get them anyway?

Thank for answering!
Best regards
Christoph

**Comment by ianhbell** [comment]
I would be very curious what fluid file they used for R-1130(E). We have a fluid file for R-1336mzz(E) that I can share (email:ian.bell@nist.gov).  I would also be curious what mixture model was used for this mixture, since I am not aware of any experimental data for it: https://doi.org/10.1021/acs.jced.1c00192
