### ISSUE TITLE
Dielectric Constant for Some Pure Fluids but not All

### ISSUE THREAD

**Issue by ceshghs** [usnistgov/REFPROP-issues#527]
### Description

Hello, I had a general question

I'm trying to understand the dielectric constant for refrigerant mixtures, namely R507a.

The more I've looked in the background of NIST's data and API, it appears NIST does not calculate Dielectric Constants for Mixtures. That being said, there seems to be references out there for empirical data of some mixtures, however, I wanted to verify the individual components of the R507a mixture (R125/R143a) to see if my calculated data was in the ballpark.  

I quickly noticed that its not available for various refrigerants such as Ammonia, R22, R125, R134a, R143a; but is reported for some other fluids such as hydrocarbons and carbon dioxide.

So my question is - why does it not provide it or is there a specific option I need to turn on to access these?

Any help is appreciated

Regards,
Stephen

### Steps to Reproduce

1. Select Pure Fluid - Ammonia (or others as listed above)
2. Calculate - Saturation Tables
3. Type: Vapor-Liquid Saturation, Vary: Temperature
4. Initial Temp = -70.0 C, Final Temp = 130.0 C, Increment = 5.0 C
5. "OK"

**Expected behavior:**

Available Dielectric Constant for Liquid Ammonia over the Range of Temperatures

**Actual behavior:** 

Dielectric Constant shows "Not calculated"

### Versions

**REFPROP Version:** DLL Version 10.0
**Operating System and Version:** Windows 10
**Access Method:** Standalone Refprop.exe Application

### Additional Information

![image](https://user-images.githubusercontent.com/89589014/165548120-55a3cad9-dbd6-4734-9d8d-3a3db852bad6.png)

**Comment by ianhbell** [comment]
Dielectric permittivity models are only implemented for a few fluids. We can only implement correlations that exist, and the data coverage is sparse at best (except for water). I searched the fluid files for ``#DE`` and found only 27 matches. Ammonia is not one with a model.

**Comment by nist-aharvey** [comment]
The fluids in REFPROP that have formulations for the static dielectric constant are almost all models that were developed for components of natural gas, where there was interest for a specific application, as described in this article:
https://link.springer.com/article/10.1007/s10765-005-2351-5

As you mention, some experimental data exist for many refrigerants of interest, including some mixtures.  So it would be possible to construct correlations for those pure refrigerants (and then once you had pure-component correlations Refprop could calculate a pretty good estimate for a mixture).  But it would be a significant amount of work to develop such correlations, and it is unlikely that we will do so in the near future unless we get some major interest from industry (and perhaps funding).  As it is, we get maybe one inquiry like this a year, and that just isn't enough interest to justify applying our limited resources.

One question I would raise is whether the dielectric constant is really the property you need.  There have been some papers published (unfortunately including one by NIST) that list "Dielectric constant" as an important refrigerant property for industrial design, when what they really meant was "Dielectric STRENGTH".  The dielectric strength refers to how strong an electric field a fluid can take before ionizing or otherwise breaking down, and can be important if your fluid is going to be around motors, etc.  That is a completely different property from the dielectric constant, and REFPROP does not deal with dielectric strength at all (nor do I know of any effort at NIST about data for dielectric strength of fluids).

**Comment by ceshghs** [comment]
Thanks for the feedback everyone, this answers my question on why they aren't calculated. A colleague of mine was looking to get the dielectric constant for applications with capacitance based liquid level probes.  I've utilized some of the experimental data I found for guidance.

I'll definitely look more into the dielectric strength when I get some time.
