### ISSUE TITLE
Question: Does full REFPROP version include equation definitions?

### ISSUE THREAD

**Issue by matthewkindig** [usnistgov/REFPROP-issues#550]
I've downloaded the free miniREFPROP version and am considering purchase of the full REFPROP version. One thing I cannot tell from the online documentation and FAQs: are the equations of state themselves (the ones that are used to generate the thermodynamic plots) available to the end user? I ask because I'm trying to define some material models in a custom software program which cannot be easily linked to the DLL version of the REFPROP software.

**Comment by ianhbell** [comment]
It depends what precisely you mean by "available to the end-user".  That is non-trivial in the general case.  If all you want is to evaluate properties as a function of temperature and density, then implementing the EOS yourself is painful but possible. If you need other kinds of calculations, you need REFPROP/CoolProp/teqp (a different software library that can handle the iterative calculations)

**Comment by EricLemmon** [comment]
For a limited number of fluids, there is code available here:

https://pages.nist.gov/AGA8

It works for temperature and density inputs because they are the independent variables.  An iterative routine is available for T and P inputs as well.

The equations that it uses are not always the default equations in Refprop, but are those from the GERG model (a whole different topic!).  The uncertainties are similar, at least for temperatures above 250 K.
