### ISSUE TITLE
ECS fluid saturation state convergence difference Linux vs Windows (REFPROP10)

### ISSUE THREAD

**Issue by cyrilpic** [usnistgov/REFPROP-issues#56]
We are doing thermodynamical optimization where we generate new fluids for the ECS model.

This works well on Windows, but for the same fluid on linux (or Mac OS) we get a convergence error:

`[SATT error 124] Iteration for saturation state did not converge for T = 303.000 K.`

Calculations are done using REFRPOP 10 and the python `ctREFPROP` wrapper on both OSs. The linux version has been compiled using `REFPROP-cmake`. Do you have any idea where the issue could come from?

Here are the steps to reproduce the issue (the fluid file is attached with wrong extension to cope with GitHub and you might need to adjust the path):

[RANDOMFLUID_FWSYN1UX.txt](https://github.com/usnistgov/REFPROP-issues/files/2468726/RANDOMFLUID_FWSYN1UX.txt)

``` python
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
RP.SETPATHdll(os.environ['RPPREFIX'])
MOLAR_BASE_SI = RP.GETENUMdll(0,"MOLAR BASE SI").iEnum

r = RP.REFPROPdll("RANDOMFLUID_FWSYN1UX.fld","TQ","P",MOLAR_BASE_SI, 0,0,303, 0, [1.0])
print(r.ierr, r.herr, r.Output[0])
```

On Windows, this return the saturation pressure (22787.26586505662). On linux, we get the aforementioned 124 error.

**Comment by cyrilpic** [comment]
Both Windows and Linux machines are 64-bit.
I installed REFRPOP from the EXE installer on windows and used the FORTRAN code inside this install to compile it on linux. So, I guess it is the same (but I did not compile the windows DLL).

**Comment by ianhbell** [comment]
Yeah, that is what I would have proposed, and if you used our binaries, they were built with the FORTRAN files that were provided alongside the DLL.  So it sounds like you are as close to agreement as possible in terms of the build.


There will always be slight differences though because different compilers are used, and the compilers can do slightly magical things with floating point operations and might not yield exactly the same output.  Have you tried to see whether you get the same results with the Intel compiler on OSX?  Do you have access to it?

**Comment by cyrilpic** [comment]
I have access to an Intel compiler on linux, but I face a few compile issues as in the `CMakeLists.txt` the flags passed to the intel compiler are for Windows only (`/threads /libs:static /MT`). Once I fix this, I will give it a try and update you.

**Comment by ianhbell** [comment]
How have you located your fluid files?  I have personally had issues with case-sensitivity of fluid files, and especially in the case of ECS, case-sensitivity of the name of the reference fluid.  I'm doing something similar myself, and that was a stumbling block for me...

**Comment by ianhbell** [comment]
I see you have r113.fld as the name of the reference fluid.  I try to keep everything consistent and always use uppercase with REFPROP FLD files.  On windows it doesn't matter, but on linux it does.  OSX should work fine.  Another useful check is to provide the ABSOLUTE path to the FLD file, which will force you to have the reference fluid in the *same* directory as the ECS fluid file, which is annoying, but better, because then you aren't surprised.

**Comment by cyrilpic** [comment]
Oh, yes, I completely forgot about the reference fluid. That was it! The reference fluid is, as for all others in refprop, written in uppercase. I changed it to all caps in the fluid file and copied it to the same directory as the ECS fluid file and now it works perfectly fine. Thank you!
