### ISSUE TITLE
Properties of Ethylène glycol mixture: what is the closer to the truth?

### ISSUE THREAD

**Issue by Gawel13** [usnistgov/REFPROP-issues#561]
Hi every one,

I am using Refprop with the Excel Extension.
I have recently updated to version 10 to get the properties of Ethylène glycol and water. So far, I was using Coolprop for that, and refprop for every other fluids. 
When I tried to change the formulaes from refprop to coolprop, I noticed differences arising in density, cp and enthalpy (from what I saw). Other sources correlate more with coolprop than with refprop. Difference are not huge, but have a big impact on my calculations.
So what is the reason? does it means Refprop is the most advanced model? Are there experimental correlations out there ?

Thanks in advance,

Examples:
20%vol ethylene glycol at 1 bar and 20°C: 
For refprop: d=1023kg/m3, cp=3.86kJ/kg/K
For coolprop and other sources d= 1030kg/m3, cp=3.90 kJ/kg/K

(other sources examples:
https://detector-cooling.web.cern.ch/data/Table%208-3-1.htm
https://corecheminc.com/ethylene-glycol-water-mixture-properties/
https://www.engineeringtoolbox.com/ethylene-glycol-d_146.html )

**Comment by ianhbell** [comment]
For one, volumetric composition is a horrible way of specifying mixture composition because volumes are not additive (in general), while mass or moles are. How did you do the conversion from volumetric to molar composition? For good reason REFPROP does not support volumetric composition.

That said, it is entirely possible that the mixture model for EG + water in REFPROP (so too for PG + water) might need to be updated. A 1% difference in specific heat is probably about the best you can hope for.  The mixture model in REFPROP was built primarily based on VLE data, so I am quite surprised that the density is only off by 1%.

**Comment by Gawel13** [comment]
Indeed, volumetric composition feels like a sacrilege. I considered that mixing glycol with water in practice was relatively close to an addition of mass (e.g 1 container of glycol for 4 of water), so a mass fraction should describe well the mixture. I tried different Normal pressure and temperature conditions but it does not change much. 

So, how should I interpret your answer? Do you expect ANY model to be within1% difference? or Refprop is a bit more off? 
May be you can direct me toward measurements of actual properties?

Thanks for your time and answer.

**Comment by ianhbell** [comment]
There are copious experimental data available for this mixture. The REFPROP model agrees pretty well with the experiments available in the literature available through the NIST ThermoData Engine tool:

![image](https://user-images.githubusercontent.com/11966765/204682137-7f837692-556a-4cc6-a587-b3da79d0e722.png)

**Comment by ianhbell** [comment]
So my read is that the REFPROP model is really quite good in this case.

**Comment by Gawel13** [comment]
Thank you, that should remind us all that absolute truth is not hidden behind the tenth decimal of any model results!
