### ISSUE TITLE
Composition issues with mole percent, mass percent, and volume percent

### ISSUE THREAD

**Issue by ghost** [usnistgov/REFPROP-issues#58]
I was trying to calculate something with Cp of Ethylene glycol/Water (50% vol / 50% vol); however, I noticed Cp from REFPROP is relatively lower than other sources from the internet (I put one of the sources below and pasted a few data points from that source).  

http://msdssearch.dow.com/PublishedLiteratureDOWCOM/dh_010e/0901b8038010e413.pdf

Could you please verify the properties of Ethylene glycol/Water mixture?

Ethylene glycol/Water: p =   1.0 bar (0.5/0.5)
 Temperature | Pressure | Cp
 (C) | (bar) | (kJ/kg-K)
   |   |  
 -30 | 1 | 2.2995
 -20 | 1 | 2.4663
 -10 | 1 | 2.5693
 0 | 1 | 2.6462
 10 | 1 | 2.711
 20 | 1 | 2.7688
 30 | 1 | 2.8216
 40 | 1 | 2.8705
 50 | 1 | 2.9161

**Comment by e191** [comment]
The three most common methods used to express the concentrations of components in a mixture are the mole fraction, mass fraction, and volume fraction (or percent).  Refprop allows the first two, but not the later for reasons explained below.  One of the biggest mistakes made while using Refprop is selecting mole fractions when mass fractions are desired, or vice versa.  It is very important to look at the input dialog while entering your compositions to make sure it specifies “mole” or “mass” as the input basis.  Likewise, when calculating properties, be sure to look at the header of the columns for the basis used to display the concentrations.  One other property that is often used incorrectly is the quality.  This property can be displayed (or used as an input) on either a mole or mass basis, meaning units of mol/mol or kg/kg.  Although it seems that these should cancel, the kg/kg nomenclature refers to one kilogram of species A in the total mass of the mixture.  For example, a quality of q=0.1 kg/kg for a methane/propane mixture would mean 1 kg of methane in 10 kg of sample.  This is NOT the same thing as 1 mole of methane in 10 moles of sample, and thus q is not equal to 0.1 mol/mol in this case. 
The conversion from mass fraction to mole fraction requires only the molar mass of the components.  This conversion is x(i)=[z(i)/M(i)]/ZM, where x is mole fraction, z is mass fraction, M is molar mass, and ZM is the sum of z(i)/M(i) over all components.  For example, 0.4/0.6 mass fraction of ammonia/water would convert to mole fractions with the following (where the 1 refers to ammonia and 2 refers to water):
z1=0.4, z2=0.6, both units of kg/kg (or kg of the component per kg of the total mixture)
M1=17.031 g/mol, M2=18.015 g/mol
ZM=0.4/17.031+0.6/18.015=0.056792
x1=0.4/17.031/0.056792=0.41356 mol/mol
x2=0.6/18.015/0.056792=0.58644 mol/mol

The concentrations can be converted from volume fraction to mole fraction by multiplying the individual volume fractions by the molar densities of each pure fluid at some reference state, and then normalizing the values so that they sum to one: x(i)=[VF(i)*D(i)(T,P)]/Y, where x is the mole fraction, VF is the volume fraction, D is the molar density, T is the temperature, P is the pressure, and Y is the sum of VF(i)*D(i) over all components.  Often the reference state is chosen as 25 C and 1 bar, but other states can be used as well.  For this reason, the ability to convert volume fractions to mole fractions is not available in Refprop.  As an example, 0.4/0.6 volume fraction of ammonia/water would convert to mole fractions with the following:
VF1=0.4, VF2=0.6 (both units of m^3/m^3)
D1(25 C, 1 bar)=35.405 mol/dm^3, D2(25 C, 1 bar)=55.345 mol/dm^3
y1=0.4*35.405=14.162, y2=0.6*55.345=33.207, Y=14.162+33.207=47.369 mol/dm^3
x1=14.162/47.369=0.29897 mol/mol
x2=33.207/47.369=0.70103 mol/mol
The use of volume fractions assumes ideal mixing of the components.  If that were really true, we wouldn't be making equations of state for you!  The use of volume fractions is discouraged and either mole or mass fractions should be used for all applications.

**Comment by EricLemmon** [comment]
The three most common methods used to express the concentrations of components in a mixture are the mole fraction, mass fraction, and volume fraction (or percent). Refprop allows the first two, but not the later for reasons explained below. One of the biggest mistakes made while using Refprop is selecting mole fractions when mass fractions are desired, or vice versa. It is very important to look at the input dialog while entering your compositions to make sure it specifies “mole” or “mass” as the input basis. Likewise, when calculating properties, be sure to look at the header of the columns for the basis used to display the concentrations. One other property that is often used incorrectly is the quality. This property can be displayed (or used as an input) on either a mole or mass basis, meaning units of mol/mol or kg/kg. Although it seems that these should cancel, the kg/kg nomenclature refers to one kilogram of species A in the total mass of the mixture. For example, a quality of q=0.1 kg/kg for a methane/propane mixture would mean 1 kg of methane in 10 kg of sample. This is NOT the same thing as 1 mole of methane in 10 moles of sample, and thus q is not equal to 0.1 mol/mol in this case.
The conversion from mass fraction to mole fraction requires only the molar mass of the components. This conversion is x(i)=[z(i)/M(i)]/ZM, where x is mole fraction, z is mass fraction, M is molar mass, and ZM is the sum of z(i)/M(i) over all components. For example, 0.4/0.6 mass fraction of ammonia/water would convert to mole fractions with the following (where the 1 refers to ammonia and 2 refers to water):
z1=0.4, z2=0.6, both units of kg/kg (or kg of the component per kg of the total mixture)
M1=17.031 g/mol, M2=18.015 g/mol
ZM=0.4/17.031+0.6/18.015=0.056792
x1=0.4/17.031/0.056792=0.41356 mol/mol
x2=0.6/18.015/0.056792=0.58644 mol/mol

The concentrations can be converted from volume fraction to mole fraction by multiplying the individual volume fractions by the molar densities of each pure fluid at some reference state, and then normalizing the values so that they sum to one: x(i)=[VF(i)D(i)(T,P)]/Y, where x is the mole fraction, VF is the volume fraction, D is the molar density, T is the temperature, P is the pressure, and Y is the sum of VF(i)D(i) over all components. Often the reference state is chosen as 25 C and 1 bar, but other states can be used as well. For this reason, the ability to convert volume fractions to mole fractions is not available in Refprop. As an example, 0.4/0.6 volume fraction of ammonia/water would convert to mole fractions with the following:
VF1=0.4, VF2=0.6 (both units of m^3/m^3)
D1(25 C, 1 bar)=35.405 mol/dm^3, D2(25 C, 1 bar)=55.345 mol/dm^3
y1=0.435.405=14.162, y2=0.655.345=33.207, Y=14.162+33.207=47.369 mol/dm^3
x1=14.162/47.369=0.29897 mol/mol
x2=33.207/47.369=0.70103 mol/mol
The use of volume fractions assumes ideal mixing of the components. If that were really true, we wouldn't be making equations of state for you! The use of volume fractions is discouraged and either mole or mass fractions should be used for all applications.
