### ISSUE TITLE
Calculate uncertainty of methane density in REFPROP9.1

### ISSUE THREAD

**Issue by ttttmmd** [usnistgov/REFPROP-issues#589]
If measured temperature and pressure have uncertainties of 0.1 K and 0.03MPa respectively. how can we acquire the uncertainty of methane density in REFPROP9.1? I see the EOS of methane gas used in REFPROP9.1 is so complicated.

reference: Setzmann, U. and Wagner, W.,
"A New Equation of State and Tables of Thermodynamic Properties for Methane
Covering the Range from the Melting Line to 625 K at Pressures up to 1000 MPa,"
J. Phys. Chem. Ref. Data, 20(6):1061-1151, 1991.

**Comment by nist-aharvey** [comment]
If you look in "Fluid Information" under the Substance menu, there is a description of the uncertainty of the EOS in terms of percent in various regions (that description should match information in the paper you cited -- in some cases the paper might have a more detailed description).
You would combine that (in quadrature, so the square root of the sum of the squares of the independent uncertainty components) with additional density uncertainty due to uncertainty in your temperature and pressure measurements, but that part is easy.  Just perturb your temperature by 0.1 K and see how much the density changes, and similarly for the 0.03 MPa pressure uncertainty.

**Comment by ttttmmd** [comment]
I got it. Thank you for your reply.
