### ISSUE TITLE
REFPROP ver.10 - Water Fluid Density

### ISSUE THREAD

**Issue by StoneRockSteel** [usnistgov/REFPROP-issues#594]
I'm struggling to find the density of water in EXCEL using VBA.

P: 2.5barg, T: 10degC
In REFPROP program, it shows 999.82kg/m3 of water density.
In EXCEL using VBA, 1079.86kg/m3 of water density is shown.
(In other property calculation program, 1017kg/m3 of water density was calculated.)

I don't know why there is difference between two methods.
I think the water density value which is close to 1000kg/m3 is reasonable.
There seem to have high density value at the given condition in EXCEL.

How can I get the correct density value of water?

Versions
**REFPROP Version: REFPROP ver.10
**Operating System and Version: Windows10 64bit
**Access Method: EXCEL/VBA

**Comment by ianhbell** [comment]
Could depend on what atmospheric pressure is considered. It is for that reason always recommended to use absolute pressure. I think the correct value is the 999.82 kg/m3. It is what is calculated with CoolProp (same EOS):
```python
import CoolProp.CoolProp as CP
print(CP.PropsSI('Dmass','T',283.15, 'P',3.5e5,'WATER'))
```
yielding
```
999.8212899597099
```

**Comment by ianhbell** [comment]
Can you show your VBA code?

**Comment by nist-aharvey** [comment]
The 999.xx kg/m3 is definitely the right number.  A little bit of pressure, like 2.5 bars (gauge or absolute) will not make much difference for liquid water which is nearly incompressible.  

I would guess that the "other" program that gave 1017 probably is using some general method (like Peng-Robinson) rather than an equation of state specific to water. 
1079 for that condition is either a bug or a mistake in the VBA. I wonder if you have a units mistake for your pressure in the VBA? You would get that density at your temperature with a pressure of about 205.3 MPa (2053 bars).

**Comment by StoneRockSteel** [comment]
Thanks for your advice. The main problem of water density difference was the EOS use of Peng-Robinson.
So, there is another problem with me.
I'd like to apply different EOS to each fluids in the same EXCEL sheet.

For example, 
LNG fluid: Peng-Robinson.
Water fluid: Default or other EOS

Please advise me.

**Comment by ianhbell** [comment]
Simply put, I think that is impossible. You will have to use a more powerful environment like Python or MATLAB to do this as you need to be able to call low-level routines for each call.
