### ISSUE TITLE
Calculation of viscosity and thermal conductivity of mixtures containing water vapor - calculation issue

### ISSUE THREAD

**Issue by youushi64** [usnistgov/REFPROP-issues#613]
We are investigating the viscosity and thermal conductivity of a mixture of approximately 13 mol% CO2, 13 mol% water, approximately 73% N2, and approximately 0.002% hexadecane under conditions of a pressure of approximately 5.1 MPa and a temperature of approximately 2000 K.
We use the desktop application.
Unfortunately, the presence of water prevents the calculations from working correctly, but if you remove the water, everything is fine.

**Comment by ianhbell** [comment]
REFPROP does not allow for the calculation of such properties because the transport property calculations for water-containing mixtures are very difficult to model and we do not have confidence in our models, and therefore do not allow them. I am afraid I do not have a good alternative recommendation.

**Comment by nist-aharvey** [comment]
There are ways to combine the pure-component values of viscosity that should give you a reasonable estimate.  Seems like I have seen people do things like a mole-fraction weighted average of ln(viscosity), but you should check for yourself as I may not be remembering correctly.  At those extreme conditions, I might expect answers for viscosity from such a scheme to be within 50%, maybe even 25% since your stream is mostly N2 which is pretty well known.

There are probably similar schemes for the thermal conductivity, but I would not trust them in your particular case. The reason is that H2O begins to dissociate significantly by 2000 K. The dissociation reaction creates another path to store energy, which can significantly change the thermal conductivity, and this reaction is not included in the H2O thermal conductivity correlation that is used in REFPROP (which has an official upper limit of 1173 K). Extrapolating viscosity of H2O to 2000 K is probably OK because the dissociation has only a small effect on the viscosity, but it has a major effect on the thermal conductivity.

Of course your hexadecane will also dissociate long before you get to 2000 K, but the mole fraction is so small that it should not make a difference in the viscosity or thermal conductivity.
