### ISSUE TITLE
Difference in the property values for Enthalpy, Entropy, Internal Energy, Gibbs between REFPROP v9.1 & 10.0 version for GERG 08 method.

### ISSUE THREAD

**Issue by msuresh20** [usnistgov/REFPROP-issues#62]
Hello NIST team,

I have created two test cases which contain lighter hydro carbon components and some light gas components using GERG 2008 method.

I could see difference in the property values for these two test case results between REFPROP v9.1 & 10.0 versions.
Both these versions are showing different property results for these properties--> Enthalpy, Entropy, Internal Energy, Gibbs.
FYI - refer to the attached excel document where in compared the results between REFPROP v9.1 & 10.0.
[Results REFPROP 9.1 vs 10.0.xlsx](https://github.com/usnistgov/REFPROP-issues/files/2514205/Results.REFPROP.9.1.vs.10.0.xlsx)

Used the consistent detault settings between these versions. 
[nist_email_query.zip](https://github.com/usnistgov/REFPROP-issues/files/2514216/nist_email_query.zip)

Refer to the attached zip for test cases and results comparison. 

Regards,
Suresh.

**Comment by EricLemmon** [comment]
The reference state for enthalpy and entropy for the GERG-2008 model was changed in version 10 so that the values would be identical to those calculated from the new AGA-8 Part 2 document, the ISO 20765 document, and the original GERG-2008 manuscript.  These values are based on a zero value of enthalpy at 25 C and 0 MPa and a zero value of the ideal gas entropy at 25 C and 0.101325 MPa.

Unfortunately a mistake was left in the fluid files for isopentane through decane and for water when the GERG-2008 is selected.  Because the reference state of 25 C and 0.101325 MPa is in the liquid phase for these eight fluids, the calculated values for the reference enthalpy and entropy were not entered correctly into the PHK part of the fluid files (which contains the ideal gas Helmholtz energy correlation for the GERG model).  (Note:  most users will not be affected by this, only those who have specified the use of this alternative model available under Options/Preferences).

_It is important to emphasis that absolute values of enthalpy and entropy are meaningless.  It is only the difference in enthalpy or entropy between two states that has any meaning.  None of the changes made in this bug fix have any impact on the properties that matter.  Please see the following for more information:_

https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences

Please contact us if you would like the updated fluid files for these eight fluids. (eric.lemmon@nist.gov or ian.bell@nist.gov)
