### ISSUE TITLE
Real-World Compatibility and Blending of Zeotropic Mixtures for Kalina Cycle Applications

### ISSUE THREAD

**Issue by atit-sut** [usnistgov/REFPROP-issues#633]
I'm currently using MATLAB to model the Kalina cycle, specifically focusing on optimizing net power output by varying the mass fraction of zeotropic mixtures, such as R134a/R245fa, R1234ze/R245fa, and R123/R245fa. Through this process, I leverage REFPROP to accurately determine fluid properties (e.g., enthalpy, entropy, specific volume) based on these varying compositions. My simulations have successfully identified promising mass fractions for different heat source temperatures.

However, a question arises regarding the practical aspect of blending these fluids. For instance, if REFPROP provides properties for a R134a/R245fa mixture with a mass fraction of 0.3/0.7, does this indicate that such a mixture can be physically and chemically blended in real-world applications? I am looking for insights into whether the mixtures' compatibility in REFPROP extends to practical feasibility in terms of stability, miscibility, and chemical interaction.

I would greatly appreciate any guidance or references that could confirm the real-world blendability and compatibility of these zeotropic mixtures.

Versions
**REFPROP Version:**10.0
Operating System and Version: Microsoft Windows 11 Home
Access Method: Python wrapper to connect between MATLAB R2022a to REFPROP.

Example of code used to determine the properties is as follows:
RP = py.ctREFPROP.ctREFPROP.REFPROPFunctionLibrary('C:\Program Files (x86)\REFPROP');
wf = 'ammonia;water';
z_NH3 = .82;
z1 = z_NH3;
z2 = 1 - z1;
z_wf = {z1  z2};
% Calculate T of ammonia and water mixture at 3 points
T_wf1 = refp(wf, 'PH', 2.994947230156076e+06, 5.779440672670845e+05, 'T', RP, z_wf)

and here is the content of refp:
function answer = refp(fluid,input,parameter1,parameter2,output,RP,z)
MOLSI = RP.GETENUMdll(int8(0),'MASS base si').iEnum;
iMass = int8(1); % 0: molar fractions; 1: mass fractions
iFlag = int8(0); % 0: don't call SATSPLN; 1: call SATSPLN
r = RP.REFPROPdll(fluid,input,output ,MOLSI,iMass,iFlag,parameter1,parameter2 ,z);
G = double(r.Output);
answer = G(1);
end

**Comment by ianhbell** [comment]
This an interesting question but mostly out of scope for REFPROP. In a sense REFPROP is "dumb". It will happily do calculations on whatever you ask, with no regard for whether the calculations are correct (though we do our best on that front). Also, the calculations in REFPROP _explicitly_ do not look for other phase equilibria like LLE.

**Comment by nist-aharvey** [comment]
To add to Ian's remark, the thermodynamic properties for the mixtures you mention should be pretty close to correct (with his caveat that it does not check for liquid miscibility).
In reference to the question you asked, issues like materials compatibility, chemical reactions, and chemical stability are completely outside the Scope of REFPROP.  So for example you may get REFPROP to do calculations for some organic compound at 800 K and it will not complain, but maybe in real life the compound would decompose at 700 K.

**Comment by atit-sut** [comment]
Dear Ian and Allan,

Thank you both for your insightful responses regarding the capabilities and scope of REFPROP concerning the blendability and chemical compatibility of mixtures. 

Understanding that REFPROP focuses on calculating thermodynamic properties without assessing the physical or chemical feasibility of mixing substances, I'm reaching out again to seek your advice or suggestions on alternative approaches. Specifically, I am interested in methodologies or tools that could help in predicting the blendability, miscibility, and chemical stability of such mixtures without resorting to immediate physical experimentation.

Are there any resources, software, databases, or forums that you would recommend for theoretically assessing the compatibility of refrigerant mixtures? Any guidance on how to approach this challenge, or references to literature and studies that might offer some direction, would be incredibly valuable.

Thank you for your time and assistance. 

Best regards,

Atit

**Comment by ianhbell** [comment]
I'm afraid I don't have much to offer here. Miscibility is all about phase equilibria, so you need a good thermodynamic model (such as those in REFPROP) to assess miscibility, but you *also* need routines that will look for different phase equilibria than REFPROP does. Stability is about kinetics, and that is far from my expertise. I know of a study or two about siloxanes, but I would unfortunately recommend googling.

**Comment by nist-aharvey** [comment]
I don't have much to offer either.  Miscibility (I don't know what you mean by "blendability" which seems like an identical word) is about thermodynamics, as Ian says both the model and then computationally looking for liquid-liquid equilibria which is not trivial.  The mixtures you name in your original message are all similar sorts of compounds, so I think liquid immiscibility is unlikely.
There are databases that contain data for liquid-liquid equilibria (NIST TDE, DDB, maybe others), so looking in those if you have access can be useful. Although if those databases do not have any LLE it does not guarantee that the substances are miscible, since it is also possible that the system has just not been measured at those conditions.  In general it is difficult to predict liquid-liquid phase separation without at least a few experimental measurements.

The substances you name are all pretty standard refrigerants so they would pretty certainly be stable both in the sense of not reacting with each other and not thermally decomposing at typical temperatures of use. [Edited to add that if you are looking at power cycles at temperatures above their typical use in refrigeration cycles, then you probably would need to think about thermal stability, and I don't know offhand where to look for such information.] Stability in the sense of reacting with other materials in your system, and in the sense of flammability, will be specific to each chemical.  The MSDS for a compound may give a little of that information; certainly it will talk about flammability.
