### ISSUE TITLE
Syntax conversion Between REFPROP 10 and 9.1

### ISSUE THREAD

**Issue by starkerm** [usnistgov/REFPROP-issues#65]
Within our company we use the REFPROP program. But we have the following issue:
 
The majority of the colleagues use the REFPROP Version 9.1. For the colleagues, who started recently in the company, licenses for the REFPROP 10 version were bought.  REFPROP 10 includes a macro to convert the “old” REFPROP commands into the REFPROP 10 syntax. This is nice for the new colleagues, who can easily convert the older files into the new commands.
 
Now my concern:
Is there a macro within the system, that can convert commands the other way around? Speaking of the conversion from the REFPROP 10 into the 9.1 command?  Or is there a dynamic program where both syntaxes are readable? Right now, whenever I open e.g. an EXCEL-file with the command of the other version, the cell shows the value #NAME, because the command is unknown for the installed version.

### Steps to Reproduce

1. Open Excel with the REFPROP 9.1
2. try to read a command written in REFPROP 10
3. Cell shows #NAME due to unknown command

### Versions

**REFPROP Version:** 9.1 and 10  
**Operating System and Version:** WIndows 10
**Access Method:** VBA (Excel)

**Comment by EricLemmon** [comment]
There are three ways that we have come up for dealing with this issue, these are:

1. Use the CoolProp interface for Excel.  Internally it uses the legacy interface to REFPROP, and while it will be slower than the REFPROP Excel interface, it should yield the same function calls for both REFPROP 9.x and REFPROP 10:  
http://www.coolprop.org/coolprop/wrappers/Excel/index.html#excel

2. If you have not included cell pointers for the first input in the REFPROP call, but rather retained the property string to indicate what to calculate, then a new macro just written would work to back convert everything.  Thus, if your cells still use this format:
=REFPROP("T",… 
Then the new macro would work, however, the following would not be back convertible:
  =REFPROP(C2,…
The macro looks for the first line above and changes it to "=Temperature(".  Basically, the macro that came with Version 10 was inverted so that it does the backward conversion for the situation above (and for all other inputs).  The updated XLS and XLA files can be found here:  
https://trc.nist.gov/refprop/10-PATCH/REFPRP91.XLA
https://trc.nist.gov/refprop/10-PATCH/REFPROP.XLS
If using version 10, you will also need the old Refprop 9.1 XLA so that the back-converted routines will still work, this is found here:
https://trc.nist.gov/refprop/10-PATCH/REFPROP.XLA
If the macro doesn't show up in your macros section, go to the VBA code (press Alt-F11), then go to the ConvertRefprop9to10 section, and change the first line from "Function" to "Sub" for the two routines in that module.  (We did this to avoid issues with hungry virus scanners.)

3. Method 3 has not yet been implemented, but is something we could put together in about 30 minutes of work.  It would require a new subroutine that would check what the input is and then call the 9.1 or 10 routines.  Thus, if cell C2 in the example above contained "T", it would then call the "Temperature" subroutine from 9.1.  This would allow a spreadsheet to work with version 10 or 9.1 without any changes and could be transferred back and forth to different people.  If you are reading this and would like this routine, please let us know (eric.lemmon@nist.gov).

**Comment by EricLemmon** [comment]
If the answers here have resolved the issues, could you please close it?
