### ISSUE TITLE
Error with ammonia water mixtures

### ISSUE THREAD

**Issue by JulianRodriguez10** [usnistgov/REFPROP-issues#659]
Hello.
I am working with  ammonia water mixtures. 
I have had problems determining thermodynamic properties from pressure and entlapy values. The REFPROPdll function returns incorrect results.

Below is an example:

Mixture = 'Ammonia;Water'         
iMass = 0                                
iFlag = 0                       

P2       =  1166536.0629814928
h2       =  106688.80880036196
x2mol = 0.6385660290489588

State2 = RP.REFPROPdll(Mixture, 'PH', 'T,P,D,H,S', RP.MASS_BASE_SI, iMass, iFlag, P2, h2, [x2mol, 1-x2mol])
T2R = State2.Output[0]
P2R = State2.Output[1] 
D2R = State2.Output[2]
h2R = State2.Output[3]
s2R = State2.Output[4]

Obtaining the following results:

![image](https://github.com/usnistgov/REFPROP-issues/assets/165821331/71a98604-220d-45fa-a954-a80b604f7f99)

The results obtain the API of REFPROP are:

![image](https://github.com/usnistgov/REFPROP-issues/assets/165821331/e8537da2-a042-4e0e-804e-396e53054f8e)

What could be happening?

REFPROP Version: Version 10
Operating System and Version: Windows 11
Access Method: Python

**Comment by ianhbell** [comment]
The GUI and the DLL use different reference states by default. Make sure you check differences in enthalpies rather than going in directly with enthalpy.

**Comment by nist-aharvey** [comment]
You can also, in the GUI, go to Options, Reference State, and select Apply reference state to "Each pure component".
I believe this will make the GUI match the DLL in its handling of reference states, so that your absolute numbers for entropy and enthalpy should match.
But Ian is right that only differences in entropy and enthalpy between states are physically meaningful, so one should never look only at single points.
