### ISSUE TITLE
What is the difference between ammonia/water mixtures in Refprop 9.1 and 10.0?

### ISSUE THREAD

**Issue by ghost** [usnistgov/REFPROP-issues#68]
What is the difference between ammonia/water mixtures in Refprop 9.1 and 10.0?

**Comment by EricLemmon** [comment]
The equation of state for ammonia in Refprop 9.1 by Tillner-Roth had a 6 percent error in the speed of sound, and thus we started refitting the equation about six years ago.  We had hoped to release it with Refprop 9.1, but due to the association in ammonia and certain data sets with uncertain uncertainties, we never finished the equation and left the Tillner-Roth equation in version 9.1.  

The ammonia/water mixture, also done by Tillner-Roth and Friend, uses a functional form that is not compatible with all other forms in Refprop, and we never developed code to handle the calculation of the splines (see the FAQ page about the subroutine SATSPLN).  Because of this, calculations often failed and was a cause of frustration for many.  Shortly after version 9.1 came out, we finished a very preliminary equation for ammonia and for the ammonia/water mixture.  The fluid file was called AmmoniaL.fld.  The mixture model was intended to work with the Kunz and Wagner equation of state for the natural gas mixture model called GERG-2008, but this was not well documented.  To our surprise, the difference between the use of a different water equation of state was much more than we had expected, and the uncertainties were much larger.  However, the convergence was much better, so a trade-off was necessary between accuracy and convergence.  This preliminary model was not distributed widely, but there are a number of people who used it.

In version 10, we spent several years developing a new ammonia equation of state, during which time we added a term with a new functional form never used in equations of state before.  This new term made it much easier to fit the association that occurs in ammonia.  Once that was done, we developed a mixture model for ammonia/water and distributed it with version 10.  The uncertainties in the new mixture model are not quite as good as those from the Tillner-Roth model, but the convergence is much higher and the model performs much better now.  We will continue to develop new mixture forms that will allow us to finally be able to fit the data to within their uncertainties, and that will then become the final model that we will publish.

The new mixture model is valid to 2000 MPa (2 GPa), with an upper temperature limit between 725 K and 2000 K (basically a mole averaged Tmax based on the Tmax of the pure fluids; the 725 K upper limit is for ammonia).  No documentation is available yet for the new equations, but the Tillner-Roth publications are given below.  The publication for ammonia is extremely difficult to obtain (or not possible at all), please contact us if you would like to receive a copy of it.

Tillner-Roth, R., Harms-Watzenberg, F., and Baehr, H.D., Eine neue Fundamentalgleichung fuer Ammoniak, DKV-Tagungsbericht, 20:167-181, 1993.

Tillner-Roth, R. and Friend, D.G., A Helmholtz free energy formulation of the thermodynamic properties of the mixture {water + ammonia}, J. Phys. Chem. Ref. Data, 27(1):63-96, 1998.
