### ISSUE TITLE
REFPROP v10 Viscosity for Fluoromethane (CH3F)

### ISSUE THREAD

**Issue by AndrewPrice775** [usnistgov/REFPROP-issues#680]
I'm wondering if there is a mistake in the REFPROP viscosity output for CH3F (R41), Fluoromethane.

**REFPROP OUTPUT =** 
mu = 10.955 uPa*s
P= 0.1 MPa
T = 298.15 K

From [1,2]:
mu = 11.79 uPa*s

A ~7.5% difference between the values. 

### Versions

**REFPROP Version:** Version 10.0. Reference Database #  23
**Operating System and Version:** Windows 10
**Access Method:** Coolprop Python with REFPROP backend and REFPROP in Excel.

### References:
[1] Dunlop, Peter J. (1994). "Viscosities of a series of gaseous fluorocarbons at 25 °C". The Journal of Chemical Physics. 100 (4): 3149–3151. [doi](https://en.wikipedia.org/wiki/Doi_(identifier)):[10.1063/1.466405](https://doi.org/10.1063%2F1.466405)
[2] https://en.wikipedia.org/wiki/List_of_viscosities#Organohalides:~:text=Fluoromethane,%5B12%5D

**Comment by nist-aharvey** [comment]
If you look in the GUI under Substance, Fluid Information, to see the method used to compute viscosity, you will see that it is just using a corresponding-states model because there was not enough experimental data to make a real correlation (it looks to me like there are no experimental liquid-phase viscosities at all, and only a few points for the vapor).  It gives the deviations of the few experimental data sources, including 7.2% from Dunlop.  That amount of difference would not be unexpected from a corresponding-states estimation technique.
Since you do have some vapor-phase data, it might not be unreasonable to shift the REFPROP results up by 7% or something if you were using the vapor viscosities (especially if the data from other sources like Casparian and Kochubey deviate similarly). 

Edited to add: I see that the paper of Dunlop reported measurements for a number of fluids, including well-known things such as methane. So the accuracy of his methane and ethane values would be a good indication of whether you should trust his result for fluoromethane enough to adjust REFPROP vapor values to match it.

**Comment by ianhbell** [comment]
I should mention in this discussion that the entropy scaling approach works very well for refrigerants: https://pubs.acs.org/doi/full/10.1021/acs.jced.0c01009 . That's not (yet) implemented in REFPROP, but the code is provided in the SI of the paper.

**Comment by AndrewPrice775** [comment]
Thank you both for your comments.
Looking forward to the new scaling technique in REPROP. I'll implement that technique and see if it matches our expectations.
