### ISSUE TITLE
R32 transport properties at the critical point

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-issues#689]
Hi,
when I try to calculate transport properties of R32 exactly at the critical point, I get below error message:
![image](https://github.com/user-attachments/assets/739c12fc-3715-4783-8dae-6b3cb651d182)
After clicking OK, reasonable values are displayed in the table.
Running the same input again does not generate a warning anymore.

R32 thermal conductivity is shown as Not calculated, while other fluids like e.g. Propane show Infinite exactly at the critical point.
![image](https://github.com/user-attachments/assets/51661f24-6a3f-4446-bc7b-0ca9bacf503d)

Is that possibly fixed in newer versions of the DLL, or with a newer correlation of R32 thermal conductivity?
Thanks and best regards,
Matthis

**Comment by ianhbell** [comment]
The thermal conductivity actually is infinite at the critical point. The viscosity, according to theory, also is infinite at the critical point, but many empirical models do not include the critical enhancement in viscosity because it is relevant for such a small region around the critical point that it is not very important for technical applications
