### ISSUE TITLE
Negative CP and Prandtl values

### ISSUE THREAD

**Issue by schreibfheler** [usnistgov/REFPROP-issues#698]
### Description

I get negative Prandtl and Cp values for certain fluids and T, D combinations.

### Steps to Reproduce

``` python
  fluid='Ethane;Cyclopropane~0.5;0.5'
  Ts = np.linspace(14, 15, 50)
  Ds = np.linspace(80, 90, 50)
  for T in Ts:
      for D in Ds:
          # this is a custom function, but basically doesn't do anything except for calling the ALLPROPSdll
          CP = RP_allprops(fluid, 'CP', T, D, units)
          print('CP', CP)
```

### Expected behaviour

Sensible (positive) values like in the GUI version

### Versions

**REFPROP Version:** 10.0.0.02
**Operating System and Version:** Windows 10
**Access Method:** Python wrapper

**Comment by ianhbell** [comment]
Without additional info it is impossible to help. Please show which inputs cause the problem.

**Comment by schreibfheler** [comment]
> Without additional info it is impossible to help. Please show which inputs cause the problem.

All the the temperature and density inputs from the original post lead to negative values. Sorry if I wasn't clear. So, e.g. the following leads to a negative CP (and also Pr):

``` python
    units='MASS BASE SI'
    fluid='Ethane;Cyclopropane'
    z = [0.5, 0.5]
    RP.SETFLUIDSdll(hFld=fluid)
    RP.SETREFdll(hrf="NBP", ixflag=2, x0=z, h0=-1, s0=-1, T0=-1, P0=-1)
    iUnits = RP.GETENUMdll(0, units).iEnum
    T = 14.712973141235011 + 273.15
    D = 84.97913769399052
    out = RP.ALLPROPSdll(hOut='CP', iUnits=iUnits, iMass=0, iFlag=1, T=T, D=D, z=z)
    print(out.Output[0])
    # this prints -8311.831573468866
```

**Comment by nist-aharvey** [comment]
When I try your point in the GUI (actually I was lazy and did the slightly different point with T = 288 and D = 85 in mass-based SI units), it tells me Cp is "Undefined" and that the point is in the 2-phase region.  REFPROP does not calculate CP in the 2-phase region (which is undefined for a pure fluid -- can in principle be calculated for a mixture but REFPROP does not do it).  
I can also note that even if you could get Cp for these points (say, from a finite-difference calculation), the Prandtl number would be undefined because the viscosity and thermal conductivity are undefined for 2-phase states.

It is possible that the negative number you see coming back is actually an error code (or perhaps an error code to which a unit conversion has been applied).

**Comment by schreibfheler** [comment]
Thanks a lot, that makes sense!
I don't think it's an error code, because it gradually changes with changing T,D inputs. Anyways, I guess by checking the sign of Cp I can detect if it accidentally went into the 2p region.

On another note, how can I get the liquid/vapour values of e.g. Prandtl or Cp with ALLPROPSdll? I don't see it mentioned anywhere in the documentation

**Comment by nist-aharvey** [comment]
You could also (more directly) check the "Quality" variable.  If I remember correctly, it is 0 for a liquid, 1 for a vapor, and a number in between for a 2-phase condition.

I don't use the DLLs myself, so I think @ianhbell will have to tell you how to access properties for the saturated liquid and saturated vapor.

**Comment by schreibfheler** [comment]
For computational reasons I need to keep the number of DLL calls to a minimum, but yes, I could directly check for the quality variable

**Comment by ianhbell** [comment]
More info on the inputs/outputs here: https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html#f/_/ALLPROPSdll
