### ISSUE TITLE
Unexpected results near saturation curve

### ISSUE THREAD

**Issue by acupello** [usnistgov/REFPROP-issues#73]
### Description

Good morning team,
I would like to have your precious support with some results I have not expected with RefProp regarding vapour saturation and isothermal curves inside saturation bell.
My work is aimed to evaluate centrifugal compressor performances for a Customer of mine.

Thanks for your help.

**Expected behavior:**
Operating point in superheated state.
Isothermal curve at constant pressure as enthalpy increases inside saturation bell.

**Actual behavior:**
Operating point in 2-phase state.
Isothermal curve decreases as enthalpy increases inside saturation bell.
### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Windows 10
**Access Method:** Directly on Refprop application.

### Additional Information
Find attached below my report with pictures and detailed issue description:
https://github.com/usnistgov/REFPROP-issues/files/2609832/Unexpected_Results_From_RefProp.pdf

**Comment by EricLemmon** [comment]
Hi,

You ask some very important questions in the pdf you attached.  Your questions are given in italics below with my answers beneath them.

_1. Is the above behavior (not constant pressure for isothermal curve inside the bell) possible in thermos-dynamics?_

The thermodynamics of mixtures are extremely complicated and strange, and can differ substantially from the simple pure fluids that we are used to.  Your Refprop P-h plot that you included demonstrates how the enthalpy drops as the fluid goes from liquid to vapor.  This is the correct behavior for mixtures.  Try something as simple as nitrogen+oxygen and you will see the same behavior.  When you are in a saturation table and you enter a temperature under the liquid column, it will return the bubble point pressure, and this pressure is quite different from the dew point pressure, which you get when you enter the temperature under the vapor column.

_2. What is the error that Refprop calculation may have done with such gas composition?_

The only error that might be in this calculation would be that some of the binary mixtures have not been fitted to experimental data, and thus Refprop is using estimation schemes to get the parameters, and these could be quite different from the actual behavior of the fluid.  To fix this, we would need experimental data and then fit each binary pair (that has not already been fitted) one at a time until all are done, and then the calculated values will represent the true behavior more accurately.

_3. Why does my Customer obtain a superheated fluid at same condition instead of 2-phases (note that my Customer is one of the most credited centrifugal compressor manufacturer worldwide)?_

Your mixture has a lot of propylene glycol in it, and it does not make sense that this substance is a vapor at 50 C and 9 bar.  It would require a pressure of less than 0.0001 bar to move it all to the vapor phase, or a temperature above 183 C to make it superheated.  The values would be different for the mixture, but not so much that it could be all in the vapor phase.

_4. What are your suggestion to carry on with my work on this activity?_

The comments under the 3rd question need to be carefully evaluated to determine why the customer is not seeing any liquid.

**Comment by acupello** [comment]
Thank you very much for supporting me at late time in the night, your replies are very clear and I will ask my Customer a confirmation of his calculation as well as the EOS he used to fill the datasheet.

**Comment by EricLemmon** [comment]
Can this issue be closed?

**Comment by acupello** [comment]
Yes, thanks for your support.

Best Regards

Andrea Cupello
