### ISSUE TITLE
Unexpected Heating Values

### ISSUE THREAD

**Issue by JJBarley** [usnistgov/REFPROP-issues#78]
### Prerequisites
REFPROP 9.1 Installed 
Attached B2.mix file deployed.

### Description

I am a little confused by the results for the GCV and NHV produced by REFPROP for a fluid we are analyzing (mix file attached).

When computing the GCV there appears to be a temperature dependence.
 
My understanding is that the heating value should be constant regardless of the temperature as it is the usable heat energy of combustion and only dependent on the conditions at which the combustion was being performed.

My understanding of the GCV is probably best summarized by the Wikipedia entry (edited a little)
The quantity known as gross calorific value (GCV) is determined by bringing all the products of combustion back to the original pre-combustion temperature, and in particular condensing any vapor produced. Such measurements often use a standard temperature of 15 °C (59 °F; 288 K). This is the same as the thermodynamic heat of combustion since the enthalpy change for the reaction assumes a common temperature of the compounds before and after combustion, in which case the water produced by combustion is condensed to a liquid. The gross heating value takes into account the latent heat of vaporization of water in the combustion products, and is useful in calculating heating values for fuels where condensation of the reaction products is practical (e.g., in a gas-fired boiler used for space heat). In other words, GCV assumes all the water component is in liquid state at the end of combustion (in product of combustion) and that heat delivered at temperatures below 150 °C (302 °F) can be put to use.
(See Table1.png) 

I thought that perhaps what was being reported was the GCV & NHV assuming the combustion is performed at the specified temperature rather at a defined reference temperature. However, I am not sure this is the case as a calculation at 473.15 K still shows a difference between the GCV and NHV. 473.15 K is well above the dew point of water.
(See Table2.png)

Is my understanding of the GCV is incorrect? If so I would appreciate it if you could explain, or point me at a reference that would explain, the above results.
I look forward to your response.

### Steps to Reproduce
Using fluid B2 create a table as per the included graphics

**Expected behavior:**
GCV independent of temperature

**Actual behavior:**
GCV temperature dependence

### Versions

**REFPROP Version:** 9.1
**Operating System and Version:** Win 7 
 
**Access Method:**
REFPROP program

### Additional Information

If possible, please post examples and/or screenshots of the issue.
![table 1](https://user-images.githubusercontent.com/45692499/49655017-4c956200-fa31-11e8-9eb1-1388d10198d4.png)
![table2](https://user-images.githubusercontent.com/45692499/49655018-4c956200-fa31-11e8-99ed-9658809829c9.png)

[B2.zip](https://github.com/usnistgov/REFPROP-issues/files/2657696/B2.zip)

**Comment by EricLemmon** [comment]
Your definition that you gave here is the scientific definition that we scientists love (especially because it's all in SI), but the world has it's own set of preferences.  Just a bit of background first:  The U.S. gas industry has set their reference state to 60 F, and much of Europe uses 15 C.  They wish to know the heating values at these conditions, not at the reference state where the measurements are taken and/or reported in the literature.  To do this, industry adds the enthalpy change from the 25 C published values to the state they would like to use, and then bill their customers accordingly.  This is seen in standards such as GPA-2145, GPA-2172, AGA-5, ISO-6976, and many others.  We are currently working on a merger of GPA-2172 and AGA-5, and will be giving even more explanation to this process in the new release scheduled to come out in the next year or two.  Refprop follows these standards accordingly, and the heating values it returns are those for the input temperature.  This allows all of industry to obtain heating values at any condition other than those published in the standards, which is especially important for countries that use, for example, 20 C for their reference state.

The lower and higher heating values differ by the contribution from the heat of vaporization of water at the input temperature and from the enthalpy change between the ideal gas and the vapor saturation state.  Thus the 473.15 K limitation you discussed is not really a limit since both of these can be calculated from an equation of state at any condition from the triple point to the critical point.  The enthalpy change of the vapor is often neglected since the contribution is quite small at lower temperatures.

Eric

**Comment by JJBarley** [comment]
Many thanks for your explanation Eric, much appreciated.
Best Regards
Jon
