### ISSUE TITLE
Observed phase fluctuations and use of error numbers in calls to the DLL.

### ISSUE THREAD

**Issue by msuresh20** [usnistgov/REFPROP-issues#91]
### Description
Observed phase fluctuations (alternatively changes) with respect to increasing temperature (300-450K) and pressure(300-450KPa). 

[Description of the issue]
Phase alternatively changes with respect to increasing temperature (300-450K) and pressure(300-450KPa). (Binary Mixture specific case: chlorobenzene, monoethanolamine)

### Steps to Reproduce

1. [First Step]
Create a binary mixture using these components: chlorobenzene, monoethanolamine

2. [Second Step]
Configure Enthalpy, Entropy, Density, Internal Energy properties , selected the default Equation of state i.e., NIST23 method.

3. Evaluate the properties with increasing temperature (300-450K) and pressure(300-450KPa)

**Expected behavior:** [What you expect to happen]
Phase fluctuations should not happens. 
**Actual behavior:** [What actually happens]
An alternative change in phase from superheated to subcooled was observed (range of 350-370K and 350-370KPa) with increase in temperature and pressure. 

### Versions

**REFPROP Version:** [REFPROP version 10.0.0.02]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [Standalone NIST application]  

Additional Information
Please refer to the attached zip file 
[4_Phase_Error.zip](https://github.com/usnistgov/REFPROP-issues/files/2781989/4_Phase_Error.zip)
 where in attached the REFPROP input, output result files.

**Comment by EricLemmon** [comment]
When you define a mixture of these two components, the Refprop executable returns a message that the two fluids cannot be used in a mixture because the fluids are too dissimilar to obtain an estimated interaction parameter.  How did you get Refprop to allow you to calculate properties of this mixture?

**Comment by a-kash-1** [comment]
The message returned by Refprop is this: 

![image](https://user-images.githubusercontent.com/16415991/52839571-9e86f200-311c-11e9-8a71-c3a6e235d110.png).

Despite the error, Refprop still allows us to go ahead and do calculations at the specified state points.

**Comment by EricLemmon** [comment]
Regardless of whether a point converged or failed, Refprop always returns numbers from calls to any subroutine in the program; sometimes the values are simply those at the critical point and sometimes they are values such as T=300, P=0, and D=0.  Users must check the value of ierr (the error number) to make sure that the calculation was successful or that the setup procedure did not fail.  If this is not done, completely wrong numbers might be used in calculations.  This is one of the most critical pieces that must be implemented in all applications that call the Refprop routines.

(I hope this is OK with you: I changed your title so that people searching for similar answers will be able to find this issue.)

**Comment by EricLemmon** [comment]
Can this issue be closed now?
