### ISSUE TITLE
spinodal curves in PT diagrams

### ISSUE THREAD

**Issue by mamomove** [usnistgov/REFPROP-issues#98]
Dear all,

I am working on some nice experiments on the detection of metastable states during
the operation of two phase devices.

I tried to derive the spinodal curves from the Van der Waals equation and it works good
for small molecules (i.e. nitrogen) but not so good for refrigerants (i.e. fluorinert, FC-72).

I was wondering if REFPROP implements a more suitable state equation for "big molecules"
and if there is a way (I am using refprop 9) to draw the spinodal limits, for instance in the P-T diagram,
using FC-72.

Thank you in advance for the help and best wishes!

**Comment by ianhbell** [comment]
Ummm - in a PT diagram the spinodal will be right on top of the vapor pressure curve for pure fluids.  Do you mean a DT diagram?

**Comment by EricLemmon** [comment]
Assuming you are doing as Ian asked, do you want to just draw them or actually calculate the spinodal values?  For big molecules, take a look at the following publication, it shows the amount of work we go to in order to develop equations with the lowest uncertainty possible:

https://trc.nist.gov/refprop/FAQ/R125.PDF

**Comment by EricLemmon** [comment]
Can this issue be closed now?
